import assert from "node:assert/strict";
import { createHash, createHmac } from "node:crypto";
import { createServer } from "node:http";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import {
  APIGatewayClient,
  CreateDeploymentCommand,
  CreateResourceCommand,
  CreateRestApiCommand,
  FlushStageCacheCommand,
  GetResourcesCommand,
  GetStageCommand,
  PutIntegrationCommand,
  PutMethodCommand,
  UpdateStageCommand,
} from "@aws-sdk/client-api-gateway";
import { CloudWatchClient, GetMetricStatisticsCommand } from "@aws-sdk/client-cloudwatch";
import { AttachRolePolicyCommand, CreatePolicyCommand, CreateRoleCommand, IAMClient } from "@aws-sdk/client-iam";
import { AssumeRoleCommand, STSClient } from "@aws-sdk/client-sts";
import { TestClock } from "../src/core/clock.js";
import { StackSim } from "../src/server.js";

const adminCredentials = { accessKeyId: "admin", secretAccessKey: "password" };
const sdkOptions = (simulator: StackSim) => ({ endpoint: `http://127.0.0.1:${simulator.port}`, region: "eu-west-1", credentials: adminCredentials });

function signedHeaders(urlValue: string, credentials: { accessKeyId: string; secretAccessKey: string; sessionToken?: string }, date: Date): Record<string, string> {
  const url = new URL(urlValue); const amzDate = date.toISOString().replace(/[:-]|\.\d{3}/g, ""); const shortDate = amzDate.slice(0, 8); const payloadHash = createHash("sha256").update("").digest("hex"); const values: Record<string, string> = { host: url.host, "x-amz-content-sha256": payloadHash, "x-amz-date": amzDate }; if (credentials.sessionToken) values["x-amz-security-token"] = credentials.sessionToken; const names = Object.keys(values).sort(); const canonicalHeaders = names.map(name => `${name}:${values[name]}\n`).join(""); const canonicalQuery = [...url.searchParams.entries()].map(([key, value]) => [encodeURIComponent(key), encodeURIComponent(value)] as const).sort((a, b) => a[0].localeCompare(b[0]) || a[1].localeCompare(b[1])).map(([key, value]) => `${key}=${value}`).join("&"); const canonicalRequest = `GET\n${url.pathname}\n${canonicalQuery}\n${canonicalHeaders}\n${names.join(";")}\n${payloadHash}`; const scope = `${shortDate}/eu-west-1/execute-api/aws4_request`; const stringToSign = `AWS4-HMAC-SHA256\n${amzDate}\n${scope}\n${createHash("sha256").update(canonicalRequest).digest("hex")}`; const hmac = (key: string | Buffer, value: string) => createHmac("sha256", key).update(value).digest(); const signingKey = hmac(hmac(hmac(hmac(`AWS4${credentials.secretAccessKey}`, shortDate), "eu-west-1"), "execute-api"), "aws4_request"); const signature = createHmac("sha256", signingKey).update(stringToSign).digest("hex"); const headers = Object.fromEntries(Object.entries(values).filter(([name]) => name !== "host")); headers.authorization = `AWS4-HMAC-SHA256 Credential=${credentials.accessKeyId}/${scope}, SignedHeaders=${names.join(";")}, Signature=${signature}`; return headers;
}

test("API Gateway response caching varies keys, expires, persists, invalidates, flushes, authorizes cache control, and emits metrics", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-apig-cache-")); const clock = new TestClock(Date.now()); const backend = createServer((req, res) => { const url = new URL(req.url ?? "/", "http://backend"); const count = ++backendCount; res.setHeader("content-type", "application/json"); res.setHeader("x-backend-count", String(count)); res.setHeader("x-cache-secret", "header-secret-dug-02"); res.end(JSON.stringify({ count, variant: url.searchParams.get("variant") ?? "" })); }); let backendCount = 0; let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1", clock, authMode: "enforce", cdkBootstrap: true }); let clients: Array<{ destroy(): void }> = []; const previousOutbound = process.env.STACKSIM_ALLOW_OUTBOUND_HTTP; const previousPrivate = process.env.STACKSIM_ALLOW_PRIVATE_HTTP; process.env.STACKSIM_ALLOW_OUTBOUND_HTTP = "true"; process.env.STACKSIM_ALLOW_PRIVATE_HTTP = "true";
  try {
    await new Promise<void>((resolve, reject) => { backend.once("error", reject); backend.listen(0, "127.0.0.1", () => { backend.off("error", reject); resolve(); }); }); const backendPort = (backend.address() as any).port;
    await simulator.start(); let apigateway = new APIGatewayClient(sdkOptions(simulator)); let iam = new IAMClient(sdkOptions(simulator)); let sts = new STSClient(sdkOptions(simulator)); let cloudwatch = new CloudWatchClient(sdkOptions(simulator)); clients.push(apigateway, iam, sts, cloudwatch);
    const api = await apigateway.send(new CreateRestApiCommand({ name: "response-cache" })); const rootResource = (await apigateway.send(new GetResourcesCommand({ restApiId: api.id! }))).items!.find(resource => resource.path === "/")!; const items = await apigateway.send(new CreateResourceCommand({ restApiId: api.id!, parentId: rootResource.id!, pathPart: "items" })); await apigateway.send(new PutMethodCommand({ restApiId: api.id!, resourceId: items.id!, httpMethod: "GET", authorizationType: "NONE", requestParameters: { "method.request.querystring.variant": false } })); await apigateway.send(new PutIntegrationCommand({ restApiId: api.id!, resourceId: items.id!, httpMethod: "GET", type: "HTTP_PROXY", integrationHttpMethod: "GET", uri: `http://127.0.0.1:${backendPort}/items`, cacheNamespace: "items", cacheKeyParameters: ["method.request.querystring.variant"] })); await apigateway.send(new CreateDeploymentCommand({ restApiId: api.id!, stageName: "dev" })); await apigateway.send(new UpdateStageCommand({ restApiId: api.id!, stageName: "dev", patchOperations: [
      { op: "replace", path: "/cacheClusterEnabled", value: "true" }, { op: "replace", path: "/cacheClusterSize", value: "0.5" }, { op: "replace", path: "/*/*/caching/enabled", value: "true" }, { op: "replace", path: "/*/*/caching/ttlInSeconds", value: "2" }, { op: "replace", path: "/*/*/caching/dataEncrypted", value: "true" }, { op: "replace", path: "/*/*/caching/requireAuthorizationForCacheControl", value: "true" }, { op: "replace", path: "/*/*/caching/unauthorizedCacheControlHeaderStrategy", value: "SUCCEED_WITH_RESPONSE_HEADER" },
    ] })); const stage = await apigateway.send(new GetStageCommand({ restApiId: api.id!, stageName: "dev" })); assert.equal(stage.cacheClusterStatus, "AVAILABLE"); assert.equal(stage.cacheClusterSize, "0.5"); assert.equal(stage.methodSettings?.["*/*"]?.cacheDataEncrypted, true);
    const invoke = (variant: string, headers: Record<string, string> = {}) => fetch(`http://127.0.0.1:${simulator.invokePort}/${api.id}/dev/items?variant=${variant}`, { headers }); const body = async (response: Response) => ({ response, value: await response.json() as any });
    let first = await body(await invoke("a")); let hit = await body(await invoke("a")); let varied = await body(await invoke("b")); assert.deepEqual(first.value, { count: 1, variant: "a" }); assert.deepEqual(hit.value, first.value); assert.deepEqual(varied.value, { count: 2, variant: "b" }); assert.equal(backendCount, 2); const ignored = await body(await invoke("a", { "cache-control": "max-age=0" })); assert.deepEqual(ignored.value, first.value); assert.match(ignored.response.headers.get("warning") ?? "", /not authorized/i); assert.equal(backendCount, 2);
    clock.advance(2_001); const expired = await body(await invoke("a")); assert.equal(expired.value.count, 3); assert.equal(backendCount, 3); const cacheEntries = Object.values(simulator.store.regionState("eu-west-1").apiGatewayResponseCaches).flatMap(cache => Object.entries(cache.entries)); const encrypted = [...cacheEntries].reverse().find(([, entry]) => entry.encrypted); assert.ok(encrypted?.[1].encrypted && encrypted[1].deploymentId && !("response" in encrypted[1])); const persistedState = await readFile(join(root, "state.json"), "utf8"); const knownBody = JSON.stringify({ count: 3, variant: "a" }); assert.doesNotMatch(persistedState, /header-secret-dug-02/); assert.ok(!persistedState.includes(Buffer.from("header-secret-dug-02").toString("base64"))); assert.ok(!persistedState.includes(knownBody)); assert.ok(!persistedState.includes(Buffer.from(knownBody).toString("base64")));
    const [tamperedKey, tamperedEntry] = encrypted!; assert.ok(tamperedEntry.encrypted); tamperedEntry.envelope.ciphertext = `${tamperedEntry.envelope.ciphertext[0] === "A" ? "B" : "A"}${tamperedEntry.envelope.ciphertext.slice(1)}`; await simulator.store.save(); const entriesBeforeTamper = cacheEntries.length; const tamperedMiss = await body(await invoke("a")); assert.equal(tamperedMiss.value.count, 4); const entriesAfterTamper = Object.values(simulator.store.regionState("eu-west-1").apiGatewayResponseCaches).flatMap(cache => Object.entries(cache.entries)); assert.equal(entriesAfterTamper.length, entriesBeforeTamper - 1); assert.ok(!entriesAfterTamper.some(([key]) => key === tamperedKey), "only the unauthenticated cache entry is evicted"); const refilledAfterTamper = await body(await invoke("a")); assert.equal(refilledAfterTamper.value.count, 5); assert.equal(backendCount, 5); const beforeRotation = Object.values(simulator.store.regionState("eu-west-1").apiGatewayResponseCaches).flatMap(cache => Object.entries(cache.entries)).find(([key]) => key === tamperedKey)?.[1]; assert.ok(beforeRotation?.encrypted); const oldKeyId = beforeRotation.envelope.keyId; const newKeyId = await simulator.apigateway.rotateResponseCacheKey(); assert.notEqual(newKeyId, oldKeyId); const rotationHit = await body(await invoke("a")); assert.equal(rotationHit.value.count, 5); const afterRotation = Object.values(simulator.store.regionState("eu-west-1").apiGatewayResponseCaches).flatMap(cache => Object.entries(cache.entries)).find(([key]) => key === tamperedKey)?.[1]; assert.ok(afterRotation?.encrypted); assert.equal(afterRotation.envelope.keyId, newKeyId, "the next valid hit lazily migrates an old-key envelope"); assert.equal(backendCount, 5);
    clients.forEach(client => client.destroy()); clients = []; await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1", clock, authMode: "enforce", cdkBootstrap: true }); await simulator.start(); apigateway = new APIGatewayClient(sdkOptions(simulator)); iam = new IAMClient(sdkOptions(simulator)); sts = new STSClient(sdkOptions(simulator)); cloudwatch = new CloudWatchClient(sdkOptions(simulator)); clients.push(apigateway, iam, sts, cloudwatch); const afterRestart = await body(await invoke("a")); assert.equal(afterRestart.value.count, 5, "an authenticated stage-cache envelope must survive restart"); assert.equal(backendCount, 5);
    await apigateway.send(new UpdateStageCommand({ restApiId: api.id!, stageName: "dev", patchOperations: [{ op: "replace", path: "/*/*/caching/unauthorizedCacheControlHeaderStrategy", value: "FAIL_WITH_403" }] })); const refilled = await body(await invoke("a")); assert.equal(refilled.value.count, 6); const denied = await invoke("a", { "cache-control": "max-age=0" }); assert.equal(denied.status, 403); assert.equal(backendCount, 6);
    const roleArn = "arn:aws:iam::000000000000:role/cache-invalidator"; await iam.send(new CreateRoleCommand({ RoleName: "cache-invalidator", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { AWS: "arn:aws:iam::000000000000:root" }, Action: "sts:AssumeRole" }] }) })); const policy = await iam.send(new CreatePolicyCommand({ PolicyName: "InvalidateResponseCache", PolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Action: "execute-api:InvalidateCache", Resource: `arn:aws:execute-api:eu-west-1:000000000000:${api.id}/dev/GET/items` }] }) })); await iam.send(new AttachRolePolicyCommand({ RoleName: "cache-invalidator", PolicyArn: policy.Policy!.Arn! })); const assumed = await sts.send(new AssumeRoleCommand({ RoleArn: roleArn, RoleSessionName: "cache-test" })); const credentials = { accessKeyId: assumed.Credentials!.AccessKeyId!, secretAccessKey: assumed.Credentials!.SecretAccessKey!, sessionToken: assumed.Credentials!.SessionToken! }; const signedUrl = `http://127.0.0.1:${simulator.invokePort}/${api.id}/dev/items?variant=a`; const authorized = await body(await fetch(signedUrl, { headers: { ...signedHeaders(signedUrl, credentials, new Date(clock.now())), "cache-control": "max-age=0" } })); assert.equal(authorized.value.count, 7); assert.equal(backendCount, 7);
    await apigateway.send(new CreateDeploymentCommand({ restApiId: api.id!, stageName: "dev" })); const redeployed = await body(await invoke("a")); assert.equal(redeployed.value.count, 8, "changing deployments must invalidate cached responses"); const redeployedHit = await body(await invoke("a")); assert.equal(redeployedHit.value.count, 8); await apigateway.send(new FlushStageCacheCommand({ restApiId: api.id!, stageName: "dev" })); const flushed = await body(await invoke("a")); assert.equal(flushed.value.count, 9); assert.equal(backendCount, 9);
    const statistic = async (metricName: string) => (await cloudwatch.send(new GetMetricStatisticsCommand({ Namespace: "AWS/ApiGateway", MetricName: metricName, Dimensions: [{ Name: "ApiName", Value: "response-cache" }, { Name: "Stage", Value: "dev" }], StartTime: new Date(clock.now() - 3_600_000), EndTime: new Date(clock.now() + 1), Period: 60, Statistics: ["Sum"] }))).Datapoints?.reduce((sum, point) => sum + (point.Sum ?? 0), 0) ?? 0; assert.equal(await statistic("CacheHitCount"), 5); assert.equal(await statistic("CacheMissCount"), 9);
    const beforeConcurrent = backendCount; const concurrent = await Promise.all([invoke("parallel"), invoke("parallel")].map(async responsePromise => body(await responsePromise))); assert.ok(backendCount === beforeConcurrent + 1 || backendCount === beforeConcurrent + 2); const afterConcurrent = backendCount; const concurrentHit = await body(await invoke("parallel")); assert.ok(concurrent.some(value => value.value.count === concurrentHit.value.count)); assert.equal(backendCount, afterConcurrent, "concurrent fills must leave one authenticated usable entry");
    await apigateway.send(new UpdateStageCommand({ restApiId: api.id!, stageName: "dev", patchOperations: [{ op: "replace", path: "/cacheClusterEnabled", value: "false" }] })); assert.deepEqual(simulator.store.regionState("eu-west-1").apiGatewayResponseCaches, {}); const disabled = await body(await invoke("a")); assert.equal(disabled.value.count, afterConcurrent + 1, "disabled cache clusters must not serve durable entries");
  } finally { clients.forEach(client => client.destroy()); await simulator.stop().catch(() => undefined); await new Promise<void>(resolve => backend.close(() => resolve())); await rm(root, { recursive: true, force: true }); if (previousOutbound === undefined) delete process.env.STACKSIM_ALLOW_OUTBOUND_HTTP; else process.env.STACKSIM_ALLOW_OUTBOUND_HTTP = previousOutbound; if (previousPrivate === undefined) delete process.env.STACKSIM_ALLOW_PRIVATE_HTTP; else process.env.STACKSIM_ALLOW_PRIVATE_HTTP = previousPrivate; }
});
