import assert from "node:assert/strict";
import { createServer } from "node:http";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import {
  APIGatewayClient,
  CreateAuthorizerCommand,
  CreateDeploymentCommand,
  CreateResourceCommand,
  CreateRequestValidatorCommand,
  CreateRestApiCommand,
  DeleteAuthorizerCommand,
  DeleteIntegrationCommand,
  DeleteIntegrationResponseCommand,
  DeleteMethodCommand,
  DeleteMethodResponseCommand,
  DeleteResourceCommand,
  FlushStageAuthorizersCacheCommand,
  GetAuthorizerCommand,
  GetAuthorizersCommand,
  GetIntegrationCommand,
  GetIntegrationResponseCommand,
  GetMethodCommand,
  GetMethodResponseCommand,
  GetResourcesCommand,
  PutIntegrationCommand,
  PutIntegrationResponseCommand,
  PutMethodCommand,
  PutMethodResponseCommand,
  TestInvokeAuthorizerCommand,
  TestInvokeMethodCommand,
  UpdateAuthorizerCommand,
  UpdateIntegrationCommand,
  UpdateIntegrationResponseCommand,
  UpdateMethodCommand,
  UpdateMethodResponseCommand,
} from "@aws-sdk/client-api-gateway";
import { DescribeLogStreamsCommand, CloudWatchLogsClient, FilterLogEventsCommand } from "@aws-sdk/client-cloudwatch-logs";
import { CreateTableCommand, DynamoDBClient, GetItemCommand } from "@aws-sdk/client-dynamodb";
import { CreateRoleCommand, IAMClient, PutRolePolicyCommand } from "@aws-sdk/client-iam";
import { CreateFunctionCommand, LambdaClient } from "@aws-sdk/client-lambda";
import { TestClock } from "../src/core/clock.js";
import { StackSim } from "../src/server.js";

const credentials = { accessKeyId: "admin", secretAccessKey: "password" };

async function resource(client: APIGatewayClient, apiId: string, parentId: string, pathPart: string): Promise<string> { return (await client.send(new CreateResourceCommand({ restApiId: apiId, parentId, pathPart }))).id!; }

test("API Gateway method, integration, and response control-plane commands support complete CRUD", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-apig-pipeline-crud-")); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, authMode: "off"}); let apig: APIGatewayClient | undefined;
  try {
    await simulator.start(); apig = new APIGatewayClient({ endpoint: `http://127.0.0.1:${simulator.port}`, region: "eu-west-1", credentials });
    const api = await apig.send(new CreateRestApiCommand({ name: "pipeline-crud" })); const rootResource = (await apig.send(new GetResourcesCommand({ restApiId: api.id! }))).items!.find(item => item.path === "/")!; const item = await resource(apig, api.id!, rootResource.id!, "item");
    await apig.send(new PutMethodCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", authorizationType: "NONE", operationName: "initial", requestParameters: { "method.request.querystring.id": false } }));
    await apig.send(new UpdateMethodCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", patchOperations: [{ op: "replace", path: "/operationName", value: "updated" }, { op: "replace", path: "/apiKeyRequired", value: "true" }] }));
    const method = await apig.send(new GetMethodCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET" })); assert.equal(method.operationName, "updated"); assert.equal(method.apiKeyRequired, true);

    await apig.send(new PutIntegrationCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", type: "MOCK", passthroughBehavior: "WHEN_NO_MATCH", cacheNamespace: "items", cacheKeyParameters: ["method.request.querystring.id"], requestTemplates: { "application/json": "{\"statusCode\":200}" } }));
    await apig.send(new UpdateIntegrationCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", patchOperations: [{ op: "replace", path: "/timeoutInMillis", value: "250" }, { op: "replace", path: "/contentHandling", value: "CONVERT_TO_TEXT" }] }));
    const integration = await apig.send(new GetIntegrationCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET" })); assert.equal(integration.timeoutInMillis, 250); assert.equal(integration.contentHandling, "CONVERT_TO_TEXT"); assert.deepEqual(integration.cacheKeyParameters, ["method.request.querystring.id"]);

    await apig.send(new PutMethodResponseCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", statusCode: "200", responseModels: { "application/json": "Empty" } }));
    await apig.send(new UpdateMethodResponseCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", statusCode: "200", patchOperations: [{ op: "replace", path: "/responseParameters/method.response.header.x-updated", value: "true" }] }));
    const methodResponse = await apig.send(new GetMethodResponseCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", statusCode: "200" })); assert.equal(methodResponse.responseParameters?.["method.response.header.x-updated"], true);

    await apig.send(new PutIntegrationResponseCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", statusCode: "200", responseTemplates: { "application/json": "{\"ok\":true}" } }));
    await apig.send(new UpdateIntegrationResponseCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", statusCode: "200", patchOperations: [{ op: "replace", path: "/selectionPattern", value: "2\\d\\d" }, { op: "replace", path: "/contentHandling", value: "CONVERT_TO_TEXT" }] }));
    const integrationResponse = await apig.send(new GetIntegrationResponseCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", statusCode: "200" })); assert.equal(integrationResponse.selectionPattern, "2\\d\\d"); assert.equal(integrationResponse.contentHandling, "CONVERT_TO_TEXT");

    await apig.send(new DeleteIntegrationResponseCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", statusCode: "200" })); await assert.rejects(apig.send(new GetIntegrationResponseCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", statusCode: "200" })), (error: any) => error.name === "NotFoundException");
    await apig.send(new DeleteMethodResponseCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", statusCode: "200" })); await assert.rejects(apig.send(new GetMethodResponseCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET", statusCode: "200" })), (error: any) => error.name === "NotFoundException");
    await apig.send(new DeleteIntegrationCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET" })); await assert.rejects(apig.send(new GetIntegrationCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET" })), (error: any) => error.name === "NotFoundException");
    await apig.send(new DeleteMethodCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET" })); await assert.rejects(apig.send(new GetMethodCommand({ restApiId: api.id!, resourceId: item, httpMethod: "GET" })), (error: any) => error.name === "NotFoundException");
  } finally { apig?.destroy(); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("API Gateway DeleteResource removes child resources and rejects deleting the root", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-apig-delete-resource-")); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, authMode: "off"}); let apig: APIGatewayClient | undefined;
  try {
    await simulator.start(); apig = new APIGatewayClient({ endpoint: `http://127.0.0.1:${simulator.port}`, region: "eu-west-1", credentials });
    const api = await apig.send(new CreateRestApiCommand({ name: "delete-resource" }));
    const rootResource = (await apig.send(new GetResourcesCommand({ restApiId: api.id! }))).items!.find(item => item.path === "/")!;
    const parent = await resource(apig, api.id!, rootResource.id!, "orders");
    const child = await resource(apig, api.id!, parent, "{id}");
    await apig.send(new PutMethodCommand({ restApiId: api.id!, resourceId: child, httpMethod: "GET", authorizationType: "NONE" }));
    await assert.rejects(apig.send(new DeleteResourceCommand({ restApiId: api.id!, resourceId: rootResource.id! })), (error: any) => error.name === "BadRequestException");
    await apig.send(new DeleteResourceCommand({ restApiId: api.id!, resourceId: parent }));
    const paths = ((await apig.send(new GetResourcesCommand({ restApiId: api.id! }))).items ?? []).map(item => item.path).sort();
    assert.deepEqual(paths, ["/"]);
  } finally { apig?.destroy(); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("API Gateway runs request/response mappings, MOCK, Lambda non-proxy, DynamoDB AWS, HTTP proxy, test invocation, and network safety", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-apig-pipeline-")); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, authMode: "off"}); const clients: Array<{ destroy(): void }> = []; const previousOutbound = process.env.STACKSIM_ALLOW_OUTBOUND_HTTP; const previousPrivate = process.env.STACKSIM_ALLOW_PRIVATE_HTTP;
  const backend = createServer((req, res) => { const send = () => { res.statusCode = req.url?.startsWith("/fail") ? 418 : 202; res.setHeader("x-backend", "yes"); res.end(JSON.stringify({ path: req.url })); }; if (req.url?.startsWith("/slow")) setTimeout(send, 120); else send(); }); await new Promise<void>(resolve => backend.listen(0, "127.0.0.1", resolve));
  try {
    await simulator.start(); const endpoint = `http://127.0.0.1:${simulator.port}`; const apig = new APIGatewayClient({ endpoint, region: "eu-west-1", credentials }); const lambda = new LambdaClient({ endpoint, region: "eu-west-1", credentials }); const ddb = new DynamoDBClient({ endpoint, region: "eu-west-1", credentials }); const iam = new IAMClient({ endpoint, region: "eu-west-1", credentials }); clients.push(apig, lambda, ddb, iam); const zip = await readFile(join(process.cwd(), "examples/lambda/function.zip")); await lambda.send(new CreateFunctionCommand({ FunctionName: "mapping", Runtime: "nodejs22.x", Role: "arn:aws:iam::000000000000:role/test", Handler: "handler.echoHandler", Code: { ZipFile: zip } })); await ddb.send(new CreateTableCommand({ TableName: "MappedItems", BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "id", AttributeType: "S" }], KeySchema: [{ AttributeName: "id", KeyType: "HASH" }] })); const gatewayTrust = JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "apigateway.amazonaws.com" }, Action: "sts:AssumeRole" }] }); const gatewayRole = await iam.send(new CreateRoleCommand({ RoleName: "api-integration", AssumeRolePolicyDocument: gatewayTrust })); const wrongGatewayRole = await iam.send(new CreateRoleCommand({ RoleName: "api-wrong-trust", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "lambda.amazonaws.com" }, Action: "sts:AssumeRole" }] }) }));
    const api = await apig.send(new CreateRestApiCommand({ name: "pipeline" })); const rootResource = (await apig.send(new GetResourcesCommand({ restApiId: api.id! }))).items!.find(item => item.path === "/")!;
    const parameterValidator = await apig.send(new CreateRequestValidatorCommand({ restApiId: api.id!, name: "parameters", validateRequestParameters: true })); const mock = await resource(apig, api.id!, rootResource.id!, "mock"); await apig.send(new PutMethodCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", authorizationType: "NONE", requestParameters: { "method.request.querystring.name": true }, requestValidatorId: parameterValidator.id })); await apig.send(new PutMethodResponseCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", statusCode: "201", responseParameters: { "method.response.header.x-result": true } })); await apig.send(new PutIntegrationCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", type: "MOCK", requestTemplates: { "application/json": "{\"statusCode\":201,\"name\":\"$util.escapeJavaScript($input.params('name'))\"}" } })); await apig.send(new PutIntegrationResponseCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", statusCode: "201", selectionPattern: "201", responseParameters: { "method.response.header.x-result": "'mapped'" }, responseTemplates: { "application/json": "{\"seen\":\"$input.path('$.name')\"}" } }));
    await assert.rejects(apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET" })), (error: any) => error.name === "BadRequestException"); const tested = await apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", pathWithQueryString: "/mock?name=Ada", headers: {} })); assert.equal(tested.status, 201); assert.deepEqual(JSON.parse(tested.body!), { seen: "Ada" }); assert.equal(tested.headers?.["x-result"], "mapped"); assert.match(tested.log ?? "", /Endpoint request body after transformations/); await apig.send(new UpdateIntegrationCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", patchOperations: [{ op: "replace", path: "/passthroughBehavior", value: "NEVER" }] })); await assert.rejects(apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", pathWithQueryString: "/mock?name=Ada", headers: { "content-type": "text/plain" } })), (error: any) => error.name === "UnsupportedMediaTypeException"); await apig.send(new UpdateIntegrationCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", patchOperations: [{ op: "remove", path: "/requestTemplates/application~1json" }] })); await assert.rejects(apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", pathWithQueryString: "/mock?name=Ada" })), (error: any) => error.name === "UnsupportedMediaTypeException"); await apig.send(new UpdateIntegrationCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", patchOperations: [{ op: "add", path: "/requestTemplates/application~1json", value: "{\"statusCode\":201,\"name\":\"$util.escapeJavaScript($input.params('name'))\"}" }, { op: "replace", path: "/passthroughBehavior", value: "WHEN_NO_MATCH" }] })); await apig.send(new UpdateIntegrationResponseCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", statusCode: "201", patchOperations: [{ op: "replace", path: "/contentHandling", value: "CONVERT_TO_TEXT" }] })); const converted = await apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", pathWithQueryString: "/mock?name=Ada" })); assert.deepEqual(JSON.parse(Buffer.from(converted.body!, "base64").toString("utf8")), { seen: "Ada" }); await apig.send(new UpdateIntegrationResponseCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", statusCode: "201", patchOperations: [{ op: "remove", path: "/contentHandling" }] }));
    const lambdaResource = await resource(apig, api.id!, rootResource.id!, "lambda"); await apig.send(new PutMethodCommand({ restApiId: api.id!, resourceId: lambdaResource, httpMethod: "POST", authorizationType: "NONE" })); await apig.send(new PutMethodResponseCommand({ restApiId: api.id!, resourceId: lambdaResource, httpMethod: "POST", statusCode: "200" })); await apig.send(new PutIntegrationCommand({ restApiId: api.id!, resourceId: lambdaResource, httpMethod: "POST", type: "AWS", integrationHttpMethod: "POST", uri: `arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:000000000000:function:mapping/invocations`, requestTemplates: { "application/json": "{\"message\":\"$input.path('$.message')\"}" } })); await apig.send(new PutIntegrationResponseCommand({ restApiId: api.id!, resourceId: lambdaResource, httpMethod: "POST", statusCode: "200", responseTemplates: { "application/json": "{\"echo\":\"$input.path('$.message')\"}" } })); const lambdaTest = await apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: lambdaResource, httpMethod: "POST", body: "{\"message\":\"hello\"}", headers: { "content-type": "application/json" } })); assert.deepEqual(JSON.parse(lambdaTest.body!), { echo: "hello" });
    const dynamo = await resource(apig, api.id!, rootResource.id!, "dynamo"); await apig.send(new PutMethodCommand({ restApiId: api.id!, resourceId: dynamo, httpMethod: "POST", authorizationType: "NONE" })); await apig.send(new PutMethodResponseCommand({ restApiId: api.id!, resourceId: dynamo, httpMethod: "POST", statusCode: "200" })); const dynamoIntegration = { restApiId: api.id!, resourceId: dynamo, httpMethod: "POST", type: "AWS" as const, integrationHttpMethod: "POST", uri: "arn:aws:apigateway:eu-west-1:dynamodb:action/PutItem", requestTemplates: { "application/json": "{\"TableName\":\"MappedItems\",\"Item\":{\"id\":{\"S\":\"$input.path('$.id')\"}}}" } }; await assert.rejects(apig.send(new PutIntegrationCommand({ ...dynamoIntegration, credentials: wrongGatewayRole.Role!.Arn! })), (error: any) => error.name === "BadRequestException"); await apig.send(new PutIntegrationCommand({ ...dynamoIntegration, credentials: gatewayRole.Role!.Arn! })); await apig.send(new PutIntegrationResponseCommand({ restApiId: api.id!, resourceId: dynamo, httpMethod: "POST", statusCode: "200", responseTemplates: { "application/json": "{\"stored\":true}" } })); await assert.rejects(apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: dynamo, httpMethod: "POST", body: "{\"id\":\"denied-by-role\"}" })), (error: any) => error.name === "AccessDeniedException"); await iam.send(new PutRolePolicyCommand({ RoleName: "api-integration", PolicyName: "dynamodb", PolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Action: "dynamodb:PutItem", Resource: "arn:aws:dynamodb:eu-west-1:000000000000:table/MappedItems" }] }) })); assert.equal((await apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: dynamo, httpMethod: "POST", body: "{\"id\":\"mapped\"}" }))).status, 200); assert.equal((await ddb.send(new GetItemCommand({ TableName: "MappedItems", Key: { id: { S: "mapped" } } }))).Item?.id?.S, "mapped");
    const http = await resource(apig, api.id!, rootResource.id!, "http"); await apig.send(new PutMethodCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET", authorizationType: "NONE" })); process.env.STACKSIM_ALLOW_OUTBOUND_HTTP = "true"; delete process.env.STACKSIM_ALLOW_PRIVATE_HTTP; const backendBase = `http://127.0.0.1:${(backend.address() as any).port}`; await apig.send(new PutIntegrationCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET", type: "HTTP_PROXY", integrationHttpMethod: "GET", uri: `${backendBase}/echo`, requestParameters: { "integration.request.querystring.forwarded": "method.request.querystring.q", "integration.request.header.x-static": "'mapped'" } })); await assert.rejects(apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET" })), (error: any) => error.name === "BadGatewayException"); process.env.STACKSIM_ALLOW_PRIVATE_HTTP = "true"; const httpResult = await apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET", pathWithQueryString: "/http?q=one" })); assert.equal(httpResult.status, 202); assert.equal(httpResult.headers?.["x-backend"], "yes"); assert.equal(JSON.parse(httpResult.body!).path, "/echo?q=one&forwarded=one");
    await apig.send(new PutMethodResponseCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET", statusCode: "202", responseParameters: { "method.response.header.x-mapped-backend": true } })); await apig.send(new PutMethodResponseCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET", statusCode: "400" })); await apig.send(new PutIntegrationCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET", type: "HTTP", integrationHttpMethod: "GET", uri: `${backendBase}/echo`, requestTemplates: { "application/json": "{\"mapped\":true}" } })); await apig.send(new PutIntegrationResponseCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET", statusCode: "202", responseParameters: { "method.response.header.x-mapped-backend": "integration.response.header.x-backend" }, responseTemplates: { "application/json": "{\"path\":\"$input.path('$.path')\"}" } })); await apig.send(new PutIntegrationResponseCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET", statusCode: "400", selectionPattern: "418", responseTemplates: { "application/json": "{\"backendError\":418}" } })); const nonProxy = await apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET" })); assert.equal(nonProxy.status, 202); assert.equal(nonProxy.headers?.["x-mapped-backend"], "yes"); assert.deepEqual(JSON.parse(nonProxy.body!), { path: "/echo" }); await apig.send(new UpdateIntegrationCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET", patchOperations: [{ op: "replace", path: "/uri", value: `${backendBase}/fail` }] })); const selectedError = await apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET" })); assert.equal(selectedError.status, 400); assert.deepEqual(JSON.parse(selectedError.body!), { backendError: 418 }); await apig.send(new UpdateIntegrationCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET", patchOperations: [{ op: "replace", path: "/uri", value: `${backendBase}/slow` }, { op: "replace", path: "/timeoutInMillis", value: "50" }] })); await assert.rejects(apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: http, httpMethod: "GET" })), (error: any) => error.name === "IntegrationFailureException");
    await apig.send(new CreateDeploymentCommand({ restApiId: api.id!, stageName: "dev" })); const deployedUrl = `http://127.0.0.1:${simulator.invokePort}/${api.id}/dev/mock?name=Grace`; const deployed = await fetch(deployedUrl); assert.equal(deployed.status, 201); assert.deepEqual(await deployed.json(), { seen: "Grace" }); await apig.send(new UpdateIntegrationCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", patchOperations: [{ op: "replace", path: "/requestTemplates/application~1json", value: "{\"statusCode\":201,\"name\":\"mutable\"}" }] })); const mutable = await apig.send(new TestInvokeMethodCommand({ restApiId: api.id!, resourceId: mock, httpMethod: "GET", pathWithQueryString: "/mock?name=ignored" })); assert.deepEqual(JSON.parse(mutable.body!), { seen: "mutable" }); const stillDeployed = await fetch(deployedUrl); assert.deepEqual(await stillDeployed.json(), { seen: "Grace" });
  } finally { if (previousOutbound === undefined) delete process.env.STACKSIM_ALLOW_OUTBOUND_HTTP; else process.env.STACKSIM_ALLOW_OUTBOUND_HTTP = previousOutbound; if (previousPrivate === undefined) delete process.env.STACKSIM_ALLOW_PRIVATE_HTTP; else process.env.STACKSIM_ALLOW_PRIVATE_HTTP = previousPrivate; clients.forEach(client => client.destroy()); await simulator.stop().catch(() => undefined); await new Promise<void>(resolve => backend.close(() => resolve())); await rm(root, { recursive: true, force: true }); }
});

test("API Gateway TOKEN authorizers enforce policies, validate output, cache by identity, expire, flush, and inject context", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-apig-authorizer-")); const clock = new TestClock(Date.now()); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, clock, authMode: "off"}); const clients: Array<{ destroy(): void }> = [];
  try {
    await simulator.start(); const endpoint = `http://127.0.0.1:${simulator.port}`; const apig = new APIGatewayClient({ endpoint, region: "eu-west-1", credentials }); const lambda = new LambdaClient({ endpoint, region: "eu-west-1", credentials }); const logs = new CloudWatchLogsClient({ endpoint, region: "eu-west-1", credentials }); clients.push(apig, lambda, logs); const zip = await readFile(join(process.cwd(), "examples/lambda/function.zip"));
    await lambda.send(new CreateFunctionCommand({ FunctionName: "auth", Runtime: "nodejs22.x", Role: "arn:aws:iam::000000000000:role/test", Handler: "handler.authorizerHandler", Code: { ZipFile: zip } })); await lambda.send(new CreateFunctionCommand({ FunctionName: "authorized-proxy", Runtime: "nodejs22.x", Role: "arn:aws:iam::000000000000:role/test", Handler: "handler.proxyEchoHandler", Code: { ZipFile: zip } }));
    const api = await apig.send(new CreateRestApiCommand({ name: "authorized" })); const rootResource = (await apig.send(new GetResourcesCommand({ restApiId: api.id! }))).items!.find(item => item.path === "/")!; await assert.rejects(apig.send(new CreateAuthorizerCommand({ restApiId: api.id!, name: "missing-identity", type: "TOKEN", authorizerUri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:000000000000:function:auth/invocations" })), (error: any) => error.name === "BadRequestException"); const authorizer = await apig.send(new CreateAuthorizerCommand({ restApiId: api.id!, name: "token", type: "TOKEN", authorizerUri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:000000000000:function:auth/invocations", identitySource: "method.request.header.Authorization", authorizerResultTtlInSeconds: 60 })); const secured = await resource(apig, api.id!, rootResource.id!, "secured"); await apig.send(new PutMethodCommand({ restApiId: api.id!, resourceId: secured, httpMethod: "GET", authorizationType: "CUSTOM", authorizerId: authorizer.id })); await apig.send(new PutIntegrationCommand({ restApiId: api.id!, resourceId: secured, httpMethod: "GET", type: "AWS_PROXY", integrationHttpMethod: "POST", uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:000000000000:function:authorized-proxy/invocations" })); await apig.send(new CreateDeploymentCommand({ restApiId: api.id!, stageName: "dev" })); const url = `http://127.0.0.1:${simulator.invokePort}/${api.id}/dev/secured`;
    const authorizerInvocations = async () => (await logs.send(new FilterLogEventsCommand({ logGroupName: "/aws/lambda/auth" }))).events?.filter(event => event.message?.startsWith("START RequestId:")).length ?? 0;
    assert.equal((await fetch(url)).status, 401); assert.equal((await fetch(url, { headers: { authorization: "deny" } })).status, 403); const deniedCount = await authorizerInvocations(); assert.equal((await fetch(url, { headers: { authorization: "deny" } })).status, 403); assert.equal(await authorizerInvocations(), deniedCount, "deny decisions must also be cached"); const allowed = await fetch(url, { headers: { authorization: "allow" } }); assert.equal(allowed.status, 200); assert.equal((await allowed.json()).principalId, "allowed-user");
    const firstCount = await authorizerInvocations(); assert.equal((await fetch(url, { headers: { authorization: "allow" } })).status, 200); const cachedCount = await authorizerInvocations(); assert.equal(cachedCount, firstCount, "cache hit must avoid invoking the authorizer"); clock.advance(61_000); assert.equal((await fetch(url, { headers: { authorization: "allow" } })).status, 200); assert.equal(await authorizerInvocations(), firstCount + 1);
    await apig.send(new FlushStageAuthorizersCacheCommand({ restApiId: api.id!, stageName: "dev" })); assert.equal((await fetch(url, { headers: { authorization: "allow" } })).status, 200); assert.equal(await authorizerInvocations(), firstCount + 2);
    await assert.rejects(apig.send(new TestInvokeAuthorizerCommand({ restApiId: api.id!, authorizerId: authorizer.id!, headers: { Authorization: "malformed" } })), (error: any) => error.name === "AuthorizerConfigurationException"); await assert.rejects(apig.send(new DeleteAuthorizerCommand({ restApiId: api.id!, authorizerId: authorizer.id! })), (error: any) => error.name === "ConflictException");
    const requestAuthorizer = await apig.send(new CreateAuthorizerCommand({ restApiId: api.id!, name: "request", type: "REQUEST", authorizerUri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:000000000000:function:auth/invocations", identitySource: "method.request.header.Authorization, method.request.querystring.tenant", authorizerResultTtlInSeconds: 0 })); const authorizerPage1 = await apig.send(new GetAuthorizersCommand({ restApiId: api.id!, limit: 1 })); assert.equal(authorizerPage1.items?.length, 1); assert.ok(authorizerPage1.position); const authorizerPage2 = await apig.send(new GetAuthorizersCommand({ restApiId: api.id!, limit: 1, position: authorizerPage1.position })); assert.equal(authorizerPage2.items?.length, 1); assert.notEqual(authorizerPage2.items?.[0].id, authorizerPage1.items?.[0].id); const requestTest = await apig.send(new TestInvokeAuthorizerCommand({ restApiId: api.id!, authorizerId: requestAuthorizer.id!, headers: { Authorization: "allow" }, pathWithQueryString: "/?tenant=acme" })); assert.equal(requestTest.principalId, "allowed-user"); await assert.rejects(apig.send(new UpdateAuthorizerCommand({ restApiId: api.id!, authorizerId: requestAuthorizer.id!, patchOperations: [{ op: "replace", path: "/authorizerResultTtlInSeconds", value: "3601" }] })), (error: any) => error.name === "BadRequestException"); assert.equal((await apig.send(new GetAuthorizerCommand({ restApiId: api.id!, authorizerId: requestAuthorizer.id! }))).authorizerResultTtlInSeconds, 0, "failed patches must not mutate the authorizer"); await apig.send(new UpdateAuthorizerCommand({ restApiId: api.id!, authorizerId: requestAuthorizer.id!, patchOperations: [{ op: "replace", path: "/name", value: "request-updated" }] })); assert.equal((await apig.send(new GetAuthorizerCommand({ restApiId: api.id!, authorizerId: requestAuthorizer.id! }))).name, "request-updated"); await apig.send(new DeleteAuthorizerCommand({ restApiId: api.id!, authorizerId: requestAuthorizer.id! }));
  } finally { clients.forEach(client => client.destroy()); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});
