import assert from "node:assert/strict";
import { createHash, createHmac, generateKeyPairSync, sign as signValue } from "node:crypto";
import { createServer, request as httpRequest, type Server } from "node:http";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import {
  ApiGatewayV2Client,
  CreateApiCommand,
  CreateApiMappingCommand,
  CreateAuthorizerCommand,
  CreateDeploymentCommand,
  CreateDomainNameCommand,
  CreateIntegrationCommand,
  CreateModelCommand,
  CreateRouteCommand,
  CreateStageCommand,
  DeleteApiMappingCommand,
  DeleteAuthorizerCommand,
  DeleteDeploymentCommand,
  DeleteDomainNameCommand,
  DeleteIntegrationCommand,
  DeleteRouteCommand,
  DeleteStageCommand,
  GetApiCommand,
  GetApiMappingCommand,
  GetApiMappingsCommand,
  GetApisCommand,
  GetAuthorizerCommand,
  GetAuthorizersCommand,
  GetDeploymentCommand,
  GetDeploymentsCommand,
  GetDomainNameCommand,
  GetDomainNamesCommand,
  GetIntegrationCommand,
  GetIntegrationsCommand,
  GetRouteCommand,
  GetRoutesCommand,
  GetStageCommand,
  GetStagesCommand,
  GetTagsCommand,
  ResetAuthorizersCacheCommand,
  TagResourceCommand,
  UntagResourceCommand,
  UpdateApiCommand,
  UpdateApiMappingCommand,
  UpdateAuthorizerCommand,
  UpdateDeploymentCommand,
  UpdateIntegrationCommand,
  UpdateRouteCommand,
  UpdateStageCommand,
} from "@aws-sdk/client-apigatewayv2";
import { AddPermissionCommand, CreateFunctionCommand, LambdaClient } from "@aws-sdk/client-lambda";
import { CloudWatchClient, ListMetricsCommand } from "@aws-sdk/client-cloudwatch";
import { CloudWatchLogsClient, CreateLogGroupCommand, FilterLogEventsCommand } from "@aws-sdk/client-cloudwatch-logs";
import { TestClock } from "../src/core/clock.js";
import { CURRENT_SCHEMA_VERSION } from "../src/migrations/v1-to-v2.js";
import { StackSim } from "../src/server.js";

const region = "eu-west-1";
const account = "000000000000";
const credentials = { accessKeyId: "admin", secretAccessKey: "password" };
const role = `arn:aws:iam::${account}:role/test`;

function crc32(data: Buffer): number { let crc = 0xffffffff; for (const byte of data) { crc ^= byte; for (let bit = 0; bit < 8; bit++) crc = crc >>> 1 ^ (crc & 1 ? 0xedb88320 : 0); } return (crc ^ 0xffffffff) >>> 0; }
function zip(name: string, content: string): Buffer {
  const fileName = Buffer.from(name); const body = Buffer.from(content); const checksum = crc32(body); const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50, 0); local.writeUInt16LE(20, 4); local.writeUInt32LE(checksum, 14); local.writeUInt32LE(body.length, 18); local.writeUInt32LE(body.length, 22); local.writeUInt16LE(fileName.length, 26); const centralOffset = local.length + fileName.length + body.length; const central = Buffer.alloc(46); central.writeUInt32LE(0x02014b50, 0); central.writeUInt16LE(0x031e, 4); central.writeUInt16LE(20, 6); central.writeUInt32LE(checksum, 16); central.writeUInt32LE(body.length, 20); central.writeUInt32LE(body.length, 24); central.writeUInt16LE(fileName.length, 28); central.writeUInt32LE((0o100644 << 16) >>> 0, 38); const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(1, 8); end.writeUInt16LE(1, 10); end.writeUInt32LE(central.length + fileName.length, 12); end.writeUInt32LE(centralOffset, 16); return Buffer.concat([local, fileName, body, central, fileName, end]);
}

function options(simulator: StackSim) { return { endpoint: `http://127.0.0.1:${simulator.port}`, region, credentials }; }
function clients(simulator: StackSim) { const value = options(simulator); return { apig: new ApiGatewayV2Client(value), lambda: new LambdaClient(value), metrics: new CloudWatchClient(value), logs: new CloudWatchLogsClient(value) }; }
function destroy(values: Array<{ destroy(): void }>): void { for (const value of values) value.destroy(); }
async function invokeHost(simulator: StackSim, host: string, path: string): Promise<{ status: number; body: string }> { return new Promise((resolve, reject) => { const request = httpRequest({ hostname: "127.0.0.1", port: simulator.invokePort, path, headers: { host } }, response => { const chunks: Buffer[] = []; response.on("data", chunk => chunks.push(Buffer.from(chunk))); response.on("end", () => resolve({ status: response.statusCode ?? 0, body: Buffer.concat(chunks).toString("utf8") })); }); request.on("error", reject); request.end(); }); }

const lambdaSource = `
exports.proxy = async event => ({ statusCode: 201, headers: { "content-type": "application/json", "access-control-allow-origin": "https://backend.invalid" }, cookies: ["session=v2; Path=/"], body: JSON.stringify(event) });
exports.infer = async event => event;
exports.authorizer = async event => ({ isAuthorized: event.headers?.authorization === "allow", context: { source: "lambda", token: event.headers?.authorization } });
`;

async function functionWithPermission(simulator: StackSim, lambda: LambdaClient, name: string, handler = "index.proxy"): Promise<string> {
  const created = await lambda.send(new CreateFunctionCommand({ FunctionName: name, Runtime: "nodejs22.x", Role: role, Handler: handler, Code: { ZipFile: zip("index.js", lambdaSource) } }));
  return created.FunctionArn!;
}

async function permit(lambda: LambdaClient, functionName: string, apiId: string, suffix = "*/*/*", statement = "gateway"): Promise<void> {
  await lambda.send(new AddPermissionCommand({ FunctionName: functionName, StatementId: statement, Action: "lambda:InvokeFunction", Principal: "apigateway.amazonaws.com", SourceArn: `arn:aws:execute-api:${region}:${account}:${apiId}/${suffix}` }));
}

test("API Gateway v2 HTTP control plane uses SDK shapes, signed pagination, snapshots, tags, domains, and current-schema persistence", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-apig-v2-control-")); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, authMode: "off"}); let active: ReturnType<typeof clients> | undefined;
  try {
    await simulator.start(); active = clients(simulator); const api = await active.apig.send(new CreateApiCommand({ Name: "orders", ProtocolType: "HTTP", Description: "first", Version: "1", RouteSelectionExpression: "$request.method $request.path", Tags: { owner: "platform" }, CorsConfiguration: { AllowOrigins: ["https://app.test"], AllowMethods: ["GET"], MaxAge: 60 } })); assert.equal(api.ProtocolType, "HTTP"); assert.equal(api.RouteSelectionExpression, "$request.method $request.path"); assert.ok(api.CreatedDate instanceof Date); assert.match(api.ApiEndpoint!, new RegExp(`/${api.ApiId}$`));
    const updatedApi = await active.apig.send(new UpdateApiCommand({ ApiId: api.ApiId, Name: "orders-http", Description: "updated", DisableExecuteApiEndpoint: true, IpAddressType: "dualstack" })); assert.equal(updatedApi.Name, "orders-http"); assert.equal(updatedApi.DisableExecuteApiEndpoint, true);
    const integration = await active.apig.send(new CreateIntegrationCommand({ ApiId: api.ApiId, IntegrationType: "HTTP_PROXY", IntegrationUri: "https://example.com/orders", IntegrationMethod: "ANY", PayloadFormatVersion: "1.0", Description: "origin" })); assert.equal((await active.apig.send(new GetIntegrationCommand({ ApiId: api.ApiId, IntegrationId: integration.IntegrationId }))).Description, "origin"); await active.apig.send(new UpdateIntegrationCommand({ ApiId: api.ApiId, IntegrationId: integration.IntegrationId, Description: "origin-updated", RequestParameters: { "overwrite:header.x-source": "'simulator'" } })); assert.equal((await active.apig.send(new GetIntegrationsCommand({ ApiId: api.ApiId }))).Items?.length, 1);
    const authorizer = await active.apig.send(new CreateAuthorizerCommand({ ApiId: api.ApiId, Name: "jwt", AuthorizerType: "JWT", IdentitySource: ["$request.header.Authorization"], JwtConfiguration: { Issuer: "https://issuer.test/", Audience: ["orders"] } })); assert.equal((await active.apig.send(new GetAuthorizerCommand({ ApiId: api.ApiId, AuthorizerId: authorizer.AuthorizerId }))).AuthorizerType, "JWT"); await active.apig.send(new UpdateAuthorizerCommand({ ApiId: api.ApiId, AuthorizerId: authorizer.AuthorizerId, Name: "jwt-updated", AuthorizerResultTtlInSeconds: 120 })); assert.equal((await active.apig.send(new GetAuthorizersCommand({ ApiId: api.ApiId }))).Items?.[0].Name, "jwt-updated");
    const route = await active.apig.send(new CreateRouteCommand({ ApiId: api.ApiId, RouteKey: "GET /orders/{id}", Target: `integrations/${integration.IntegrationId}`, AuthorizationType: "JWT", AuthorizerId: authorizer.AuthorizerId, AuthorizationScopes: ["orders:read"] })); const readRoute = await active.apig.send(new GetRouteCommand({ ApiId: api.ApiId, RouteId: route.RouteId })); assert.equal(readRoute.RouteKey, "GET /orders/{id}"); assert.equal(readRoute.RouteResponseSelectionExpression, undefined); await active.apig.send(new UpdateRouteCommand({ ApiId: api.ApiId, RouteId: route.RouteId, OperationName: "GetOrder" })); assert.equal((await active.apig.send(new GetRoutesCommand({ ApiId: api.ApiId }))).Items?.[0].OperationName, "GetOrder");
    const deployment = await active.apig.send(new CreateDeploymentCommand({ ApiId: api.ApiId, Description: "release one" })); assert.equal(deployment.DeploymentStatus, "SUCCEEDED"); await active.apig.send(new UpdateDeploymentCommand({ ApiId: api.ApiId, DeploymentId: deployment.DeploymentId, Description: "release one updated" })); assert.equal((await active.apig.send(new GetDeploymentCommand({ ApiId: api.ApiId, DeploymentId: deployment.DeploymentId }))).Description, "release one updated"); assert.equal((await active.apig.send(new GetDeploymentsCommand({ ApiId: api.ApiId }))).Items?.length, 1);
    const stage = await active.apig.send(new CreateStageCommand({ ApiId: api.ApiId, StageName: "dev", DeploymentId: deployment.DeploymentId, Description: "development", StageVariables: { environment: "test" }, DefaultRouteSettings: { DetailedMetricsEnabled: true }, Tags: { stage: "dev" } })); assert.equal(stage.StageVariables?.environment, "test"); await active.apig.send(new UpdateStageCommand({ ApiId: api.ApiId, StageName: "dev", Description: "development updated", RouteSettings: { "GET /orders/{id}": { ThrottlingBurstLimit: 2, ThrottlingRateLimit: 1 } } })); assert.equal((await active.apig.send(new GetStageCommand({ ApiId: api.ApiId, StageName: "dev" }))).Description, "development updated"); assert.equal((await active.apig.send(new GetStagesCommand({ ApiId: api.ApiId }))).Items?.length, 1);
    const apiArn = `arn:aws:apigateway:${region}::/apis/${api.ApiId}`; await active.apig.send(new TagResourceCommand({ ResourceArn: apiArn, Tags: { environment: "test" } })); await active.apig.send(new UntagResourceCommand({ ResourceArn: apiArn, TagKeys: ["owner"] })); assert.deepEqual((await active.apig.send(new GetTagsCommand({ ResourceArn: apiArn }))).Tags, { environment: "test" });
    const domain = await active.apig.send(new CreateDomainNameCommand({ DomainName: "http.example.test", DomainNameConfigurations: [{ EndpointType: "REGIONAL", CertificateArn: `arn:aws:acm:${region}:${account}:certificate/local`, SecurityPolicy: "TLS_1_2" }], Tags: { owner: "platform" } })); assert.equal((await active.apig.send(new GetDomainNameCommand({ DomainName: domain.DomainName }))).DomainNameConfigurations?.[0].DomainNameStatus, "AVAILABLE"); const mapping = await active.apig.send(new CreateApiMappingCommand({ DomainName: domain.DomainName, ApiId: api.ApiId, Stage: "dev", ApiMappingKey: "team/orders" })); assert.equal((await active.apig.send(new GetApiMappingCommand({ DomainName: domain.DomainName, ApiMappingId: mapping.ApiMappingId }))).ApiMappingKey, "team/orders"); await active.apig.send(new UpdateApiMappingCommand({ DomainName: domain.DomainName, ApiMappingId: mapping.ApiMappingId, ApiId: api.ApiId!, ApiMappingKey: "v1/orders" })); assert.equal((await active.apig.send(new GetApiMappingsCommand({ DomainName: domain.DomainName }))).Items?.[0].ApiMappingKey, "v1/orders"); assert.equal((await active.apig.send(new GetDomainNamesCommand({}))).Items?.length, 1);
    await assert.rejects(active.apig.send(new CreateModelCommand({ ApiId: api.ApiId, Name: "Order", Schema: "{}", ContentType: "application/json" })), (error: any) => error.name === "BadRequestException" && /WebSocket/.test(error.message));
    await active.apig.send(new CreateApiCommand({ Name: "second", ProtocolType: "HTTP" })); const firstPage = await active.apig.send(new GetApisCommand({ MaxResults: "1" })); assert.equal(firstPage.Items?.length, 1); assert.ok(firstPage.NextToken); await assert.rejects(active.apig.send(new GetRoutesCommand({ ApiId: api.ApiId, NextToken: firstPage.NextToken })), (error: any) => error.name === "BadRequestException"); assert.equal((await active.apig.send(new GetApisCommand({ MaxResults: "1", NextToken: firstPage.NextToken }))).Items?.length, 1);
    destroy(Object.values(active)); active = undefined; await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, authMode: "off"}); await simulator.start(); active = clients(simulator); assert.equal(simulator.store.state.schemaVersion, CURRENT_SCHEMA_VERSION); assert.equal((await active.apig.send(new GetApiCommand({ ApiId: api.ApiId }))).Name, "orders-http"); assert.equal((await active.apig.send(new GetApiMappingsCommand({ DomainName: domain.DomainName }))).Items?.[0].ApiMappingKey, "v1/orders");
    await active.apig.send(new DeleteApiMappingCommand({ DomainName: domain.DomainName, ApiMappingId: mapping.ApiMappingId })); await active.apig.send(new DeleteDomainNameCommand({ DomainName: domain.DomainName })); await active.apig.send(new DeleteRouteCommand({ ApiId: api.ApiId, RouteId: route.RouteId })); await active.apig.send(new DeleteAuthorizerCommand({ ApiId: api.ApiId, AuthorizerId: authorizer.AuthorizerId })); await active.apig.send(new DeleteIntegrationCommand({ ApiId: api.ApiId, IntegrationId: integration.IntegrationId })); await active.apig.send(new DeleteStageCommand({ ApiId: api.ApiId, StageName: "dev" })); await active.apig.send(new DeleteDeploymentCommand({ ApiId: api.ApiId, DeploymentId: deployment.DeploymentId }));
  } finally { if (active) destroy(Object.values(active)); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("HTTP API Lambda payloads, route priority, immutable deployments, CORS, quick-create, and custom mappings invoke correctly", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-apig-v2-lambda-")); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, authMode: "off"}); let active: ReturnType<typeof clients> | undefined;
  try {
    await simulator.start(); active = clients(simulator); const functionArn = await functionWithPermission(simulator, active.lambda, "http-v2-proxy"); const api = await active.apig.send(new CreateApiCommand({ Name: "runtime", ProtocolType: "HTTP", CorsConfiguration: { AllowOrigins: ["https://app.test"], AllowMethods: ["GET", "POST"], AllowHeaders: ["authorization", "content-type"], ExposeHeaders: ["x-route"], AllowCredentials: true, MaxAge: 600 } }));
    const integration = await active.apig.send(new CreateIntegrationCommand({ ApiId: api.ApiId, IntegrationType: "AWS_PROXY", IntegrationUri: functionArn, PayloadFormatVersion: "2.0" })); await active.apig.send(new CreateRouteCommand({ ApiId: api.ApiId, RouteKey: "ANY /things/{proxy+}", Target: `integrations/${integration.IntegrationId}` })); await active.apig.send(new CreateRouteCommand({ ApiId: api.ApiId, RouteKey: "GET /things/special", Target: `integrations/${integration.IntegrationId}` })); const firstDeployment = await active.apig.send(new CreateDeploymentCommand({ ApiId: api.ApiId, Description: "one" })); await active.apig.send(new CreateStageCommand({ ApiId: api.ApiId, StageName: "dev", DeploymentId: firstDeployment.DeploymentId, StageVariables: { release: "one" } })); await permit(active.lambda, "http-v2-proxy", api.ApiId!);
    const invoke = `http://127.0.0.1:${simulator.invokePort}/${api.ApiId}/dev`; let response = await fetch(`${invoke}/things/special?q=one&q=two`, { headers: { origin: "https://app.test", cookie: "one=1; two=2" } }); assert.equal(response.status, 201); assert.equal(response.headers.get("access-control-allow-origin"), "https://app.test"); assert.notEqual(response.headers.get("access-control-allow-origin"), "https://backend.invalid"); assert.equal(response.headers.getSetCookie()[0], "session=v2; Path=/"); const exact = await response.json() as any; assert.equal(exact.version, "2.0"); assert.equal(exact.routeKey, "GET /things/special"); assert.equal(exact.rawPath, "/things/special"); assert.equal(exact.queryStringParameters.q, "one,two"); assert.deepEqual(exact.cookies, ["one=1", "two=2"]); assert.equal(exact.requestContext.stage, "dev");
    const greedy = await (await fetch(`${invoke}/things/a/b`)).json() as any; assert.equal(greedy.routeKey, "ANY /things/{proxy+}"); assert.equal(greedy.pathParameters.proxy, "a/b");
    await active.apig.send(new CreateRouteCommand({ ApiId: api.ApiId, RouteKey: "POST /new", Target: `integrations/${integration.IntegrationId}` })); assert.equal((await fetch(`${invoke}/new`, { method: "POST" })).status, 404, "manual stage keeps the previous deployment snapshot"); const secondDeployment = await active.apig.send(new CreateDeploymentCommand({ ApiId: api.ApiId, Description: "two" })); await active.apig.send(new UpdateStageCommand({ ApiId: api.ApiId, StageName: "dev", DeploymentId: secondDeployment.DeploymentId })); assert.equal((await fetch(`${invoke}/new`, { method: "POST" })).status, 201);
    const preflight = await fetch(`${invoke}/anything`, { method: "OPTIONS", headers: { origin: "https://app.test", "access-control-request-method": "POST", "access-control-request-headers": "content-type" } }); assert.equal(preflight.status, 204); assert.match(preflight.headers.get("access-control-allow-methods") ?? "", /POST/); assert.equal(preflight.headers.get("access-control-max-age"), "600");
    const v1 = await active.apig.send(new CreateIntegrationCommand({ ApiId: api.ApiId, IntegrationType: "AWS_PROXY", IntegrationUri: functionArn, PayloadFormatVersion: "1.0" })); await active.apig.send(new CreateRouteCommand({ ApiId: api.ApiId, RouteKey: "POST /legacy/{id}", Target: `integrations/${v1.IntegrationId}` })); const third = await active.apig.send(new CreateDeploymentCommand({ ApiId: api.ApiId })); await active.apig.send(new UpdateStageCommand({ ApiId: api.ApiId, StageName: "dev", DeploymentId: third.DeploymentId })); const legacy = await (await fetch(`${invoke}/legacy/42`, { method: "POST", body: "hello", headers: { "content-type": "text/plain" } })).json() as any; assert.equal(legacy.httpMethod, "POST"); assert.equal(legacy.path, "/legacy/42"); assert.equal(legacy.pathParameters.id, "42"); assert.equal(legacy.body, "hello");
    const domain = await active.apig.send(new CreateDomainNameCommand({ DomainName: "runtime.example.test", DomainNameConfigurations: [{ CertificateArn: `arn:aws:acm:${region}:${account}:certificate/runtime`, EndpointType: "REGIONAL" }] })); await active.apig.send(new CreateApiMappingCommand({ DomainName: domain.DomainName, ApiId: api.ApiId, Stage: "dev", ApiMappingKey: "team/api" })); const mapped = await invokeHost(simulator, "runtime.example.test", "/team/api/things/custom"); assert.equal(mapped.status, 201, mapped.body); assert.equal((JSON.parse(mapped.body) as any).rawPath, "/things/custom", "mapping key is excluded from payload 2.0 rawPath");
    await active.apig.send(new UpdateApiCommand({ ApiId: api.ApiId, DisableExecuteApiEndpoint: true })); assert.equal((await fetch(`${invoke}/things/direct`)).status, 403); assert.equal((await invokeHost(simulator, "runtime.example.test", "/team/api/things/mapped")).status, 201);
    const quickFunction = await functionWithPermission(simulator, active.lambda, "http-v2-quick", "index.infer"); const quick = await active.apig.send(new CreateApiCommand({ Name: "quick", ProtocolType: "HTTP", Target: quickFunction, RouteKey: "ANY /{proxy+}" })); await permit(active.lambda, "http-v2-quick", quick.ApiId!); const quickEvent = await (await fetch(`http://127.0.0.1:${simulator.invokePort}/${quick.ApiId}/ready`)).json() as any; assert.equal(quickEvent.version, "2.0"); assert.equal(quickEvent.requestContext.stage, "$default"); assert.equal((await active.apig.send(new GetStagesCommand({ ApiId: quick.ApiId }))).Items?.[0].AutoDeploy, true);
  } finally { if (active) destroy(Object.values(active)); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("HTTP proxy mapping, access logs, detailed metrics, and route throttling remain opt-in and observable", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-apig-v2-http-proxy-")); const clock = new TestClock(Date.now()); let backend: Server | undefined; const previousOutbound = process.env.STACKSIM_ALLOW_OUTBOUND_HTTP; const previousPrivate = process.env.STACKSIM_ALLOW_PRIVATE_HTTP; process.env.STACKSIM_ALLOW_OUTBOUND_HTTP = "true"; process.env.STACKSIM_ALLOW_PRIVATE_HTTP = "true"; const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, clock, authMode: "off"}); let active: ReturnType<typeof clients> | undefined;
  try {
    backend = createServer((req, res) => { const target = new URL(req.url ?? "/", "http://backend"); res.statusCode = 202; res.setHeader("content-type", "application/json"); res.setHeader("x-backend", "origin"); res.end(JSON.stringify({ path: target.pathname, query: Object.fromEntries(target.searchParams), source: req.headers["x-source"] })); }); await new Promise<void>(resolve => backend!.listen(0, "127.0.0.1", resolve)); const backendPort = (backend.address() as any).port;
    await simulator.start(); active = clients(simulator); await active.logs.send(new CreateLogGroupCommand({ logGroupName: "/aws/apigateway/http-v2" })); const api = await active.apig.send(new CreateApiCommand({ Name: "proxy", ProtocolType: "HTTP" })); const integration = await active.apig.send(new CreateIntegrationCommand({ ApiId: api.ApiId, IntegrationType: "HTTP_PROXY", IntegrationUri: `http://127.0.0.1:${backendPort}/base`, IntegrationMethod: "ANY", PayloadFormatVersion: "1.0", RequestParameters: { "overwrite:path": "'/mapped'", "overwrite:querystring.source": "'simulator'", "overwrite:header.x-source": "'$request.header.x-client'" }, ResponseParameters: { "202": { "overwrite:statuscode": "201", "append:header.x-mapped": "'yes'", "overwrite:header.x-copy": "$response.header.x-backend" } } })); const route = await active.apig.send(new CreateRouteCommand({ ApiId: api.ApiId, RouteKey: "GET /proxy", Target: `integrations/${integration.IntegrationId}` })); const deployment = await active.apig.send(new CreateDeploymentCommand({ ApiId: api.ApiId })); await active.apig.send(new CreateStageCommand({ ApiId: api.ApiId, StageName: "dev", DeploymentId: deployment.DeploymentId, AccessLogSettings: { DestinationArn: `arn:aws:logs:${region}:${account}:log-group:/aws/apigateway/http-v2`, Format: "$context.requestId $context.routeKey $context.status $context.responseLength" }, RouteSettings: { "GET /proxy": { DetailedMetricsEnabled: true, ThrottlingBurstLimit: 1, ThrottlingRateLimit: 1 } } }));
    const invoke = `http://127.0.0.1:${simulator.invokePort}/${api.ApiId}/dev/proxy?discard=one`; let response = await fetch(invoke, { headers: { "x-client": "browser" } }); assert.equal(response.status, 201); assert.equal(response.headers.get("x-mapped"), "yes"); assert.equal(response.headers.get("x-copy"), "origin"); assert.deepEqual(await response.json(), { path: "/mapped", query: { discard: "one", source: "simulator" }, source: "$request.header.x-client" }); assert.equal((await fetch(invoke)).status, 429); clock.advance(1000); assert.equal((await fetch(invoke)).status, 201);
    const logs = await active.logs.send(new FilterLogEventsCommand({ logGroupName: "/aws/apigateway/http-v2" })); assert.ok(logs.events?.some(event => event.message?.includes("GET /proxy 201"))); const metrics = await active.metrics.send(new ListMetricsCommand({ Namespace: "AWS/ApiGateway" })); assert.ok(metrics.Metrics?.some(metric => metric.MetricName === "Count" && metric.Dimensions?.some(value => value.Name === "Route" && value.Value === route.RouteKey))); assert.ok(metrics.Metrics?.some(metric => metric.MetricName === "DataProcessed"));
  } finally { if (active) destroy(Object.values(active)); await simulator.stop().catch(() => undefined); if (backend) await new Promise<void>(resolve => backend!.close(() => resolve())); if (previousOutbound === undefined) delete process.env.STACKSIM_ALLOW_OUTBOUND_HTTP; else process.env.STACKSIM_ALLOW_OUTBOUND_HTTP = previousOutbound; if (previousPrivate === undefined) delete process.env.STACKSIM_ALLOW_PRIVATE_HTTP; else process.env.STACKSIM_ALLOW_PRIVATE_HTTP = previousPrivate; await rm(root, { recursive: true, force: true }); }
});

function signedHeaders(urlValue: string, date: Date): Record<string, string> {
  const url = new URL(urlValue); const amzDate = date.toISOString().replace(/[:-]|\.\d{3}/g, ""); const shortDate = amzDate.slice(0, 8); const payloadHash = createHash("sha256").update("").digest("hex"); const values: Record<string, string> = { host: url.host, "x-amz-content-sha256": payloadHash, "x-amz-date": amzDate }; const names = Object.keys(values).sort(); const canonicalHeaders = names.map(name => `${name}:${values[name]}\n`).join(""); const canonicalRequest = `GET\n${url.pathname}\n\n${canonicalHeaders}\n${names.join(";")}\n${payloadHash}`; const scope = `${shortDate}/${region}/execute-api/aws4_request`; const stringToSign = `AWS4-HMAC-SHA256\n${amzDate}\n${scope}\n${createHash("sha256").update(canonicalRequest).digest("hex")}`; const hmac = (key: string | Buffer, value: string) => createHmac("sha256", key).update(value).digest(); const signingKey = hmac(hmac(hmac(hmac(`AWS4${credentials.secretAccessKey}`, shortDate), region), "execute-api"), "aws4_request"); const signature = createHmac("sha256", signingKey).update(stringToSign).digest("hex"); return { "x-amz-content-sha256": payloadHash, "x-amz-date": amzDate, authorization: `AWS4-HMAC-SHA256 Credential=${credentials.accessKeyId}/${scope}, SignedHeaders=${names.join(";")}, Signature=${signature}` };
}

function jwt(privateKey: ReturnType<typeof generateKeyPairSync>["privateKey"], kid: string, claims: Record<string, unknown>): string {
  const header = Buffer.from(JSON.stringify({ alg: "RS256", kid, typ: "JWT" })).toString("base64url"); const payload = Buffer.from(JSON.stringify(claims)).toString("base64url"); const signature = signValue("RSA-SHA256", Buffer.from(`${header}.${payload}`), privateKey).toString("base64url"); return `${header}.${payload}.${signature}`;
}

test("HTTP API IAM, Lambda REQUEST, and local-JWKS JWT authorizers enforce dependencies, scopes, cache reset, and default-stage canonical targets", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-apig-v2-auth-")); const clock = new TestClock(Date.now()); const keys = generateKeyPairSync("rsa", { modulusLength: 2048 }); const kid = "local-key"; const publicJwk = keys.publicKey.export({ format: "jwk" }); publicJwk.kid = kid; const issuer = "https://issuer.local"; const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, clock, authMode: "enforce", cdkBootstrap: true, apiGatewayJwtJwks: { [issuer]: { keys: [publicJwk] } } }); let active: ReturnType<typeof clients> | undefined;
  try {
    await simulator.start(); active = clients(simulator); const targetArn = await functionWithPermission(simulator, active.lambda, "http-v2-auth-target"); const authorizerArn = await functionWithPermission(simulator, active.lambda, "http-v2-authorizer", "index.authorizer"); const api = await active.apig.send(new CreateApiCommand({ Name: "auth", ProtocolType: "HTTP" })); const integration = await active.apig.send(new CreateIntegrationCommand({ ApiId: api.ApiId, IntegrationType: "AWS_PROXY", IntegrationUri: targetArn, PayloadFormatVersion: "2.0" })); const requestAuthorizer = await active.apig.send(new CreateAuthorizerCommand({ ApiId: api.ApiId, Name: "lambda", AuthorizerType: "REQUEST", AuthorizerUri: `arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${authorizerArn}/invocations`, AuthorizerPayloadFormatVersion: "2.0", EnableSimpleResponses: true, IdentitySource: ["$request.header.Authorization"], AuthorizerResultTtlInSeconds: 60 })); const jwtAuthorizer = await active.apig.send(new CreateAuthorizerCommand({ ApiId: api.ApiId, Name: "jwt", AuthorizerType: "JWT", IdentitySource: ["$request.header.Authorization"], JwtConfiguration: { Issuer: issuer, Audience: ["local-client"] } })); await active.apig.send(new CreateRouteCommand({ ApiId: api.ApiId, RouteKey: "GET /lambda", Target: `integrations/${integration.IntegrationId}`, AuthorizationType: "CUSTOM", AuthorizerId: requestAuthorizer.AuthorizerId })); await active.apig.send(new CreateRouteCommand({ ApiId: api.ApiId, RouteKey: "GET /jwt", Target: `integrations/${integration.IntegrationId}`, AuthorizationType: "JWT", AuthorizerId: jwtAuthorizer.AuthorizerId, AuthorizationScopes: ["orders:read"] })); await active.apig.send(new CreateRouteCommand({ ApiId: api.ApiId, RouteKey: "GET /iam", Target: `integrations/${integration.IntegrationId}`, AuthorizationType: "AWS_IAM" })); await active.apig.send(new CreateStageCommand({ ApiId: api.ApiId, StageName: "$default", AutoDeploy: true })); await permit(active.lambda, "http-v2-auth-target", api.ApiId!); await permit(active.lambda, "http-v2-authorizer", api.ApiId!, `authorizers/${requestAuthorizer.AuthorizerId}`, "authorizer");
    const base = `http://127.0.0.1:${simulator.invokePort}/${api.ApiId}`; assert.equal((await fetch(`${base}/lambda`)).status, 401); assert.equal((await fetch(`${base}/lambda`, { headers: { authorization: "deny" } })).status, 403); let response = await fetch(`${base}/lambda`, { headers: { authorization: "allow" } }); assert.equal(response.status, 201); assert.equal((await response.json() as any).requestContext.authorizer.lambda.source, "lambda"); await active.apig.send(new ResetAuthorizersCacheCommand({ ApiId: api.ApiId, StageName: "$default" }));
    const now = Math.floor(clock.now() / 1000); const valid = jwt(keys.privateKey, kid, { iss: issuer, aud: "local-client", exp: now + 300, iat: now, scope: "orders:read profile", sub: "user-1" }); response = await fetch(`${base}/jwt`, { headers: { authorization: `Bearer ${valid}` } }); assert.equal(response.status, 201); assert.equal((await response.json() as any).requestContext.authorizer.jwt.claims.sub, "user-1"); const wrongScope = jwt(keys.privateKey, kid, { iss: issuer, aud: "local-client", exp: now + 300, scope: "other" }); assert.equal((await fetch(`${base}/jwt`, { headers: { authorization: `Bearer ${wrongScope}` } })).status, 403); const expired = jwt(keys.privateKey, kid, { iss: issuer, aud: "local-client", exp: now - 1, scope: "orders:read" }); assert.equal((await fetch(`${base}/jwt`, { headers: { authorization: `Bearer ${expired}` } })).status, 401);
    const futureIat = jwt(keys.privateKey, kid, { iss: issuer, aud: "local-client", exp: now + 300, iat: now + 1, scope: "orders:read" }); assert.equal((await fetch(`${base}/jwt`, { headers: { authorization: `Bearer ${futureIat}` } })).status, 401);
    const malformedIat = jwt(keys.privateKey, kid, { iss: issuer, aud: "local-client", exp: now + 300, iat: "now", scope: "orders:read" }); assert.equal((await fetch(`${base}/jwt`, { headers: { authorization: `Bearer ${malformedIat}` } })).status, 401);
    const absentIat = jwt(keys.privateKey, kid, { iss: issuer, aud: "local-client", exp: now + 300, scope: "orders:read" }); assert.equal((await fetch(`${base}/jwt`, { headers: { authorization: `Bearer ${absentIat}` } })).status, 201);
    const iamUrl = `${base}/iam`; assert.equal((await fetch(iamUrl)).status, 403); assert.equal((await fetch(iamUrl, { headers: signedHeaders(iamUrl, new Date(clock.now())) })).status, 201, "default-stage IAM authorization inserts $default into the policy target while preserving the signed URL");
  } finally { if (active) destroy(Object.values(active)); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("HTTP API remote JWT discovery is explicit, private-target guarded, bounded, and cached", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-apig-v2-remote-jwt-")); const clock = new TestClock(Date.now()); const keys = generateKeyPairSync("rsa", { modulusLength: 2048 }); const kid = "remote-key"; const publicJwk = keys.publicKey.export({ format: "jwk" }); publicJwk.kid = kid; let provider: Server | undefined; let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, clock, apiGatewayAllowRemoteJwtJwks: true, authMode: "off"}); let active: ReturnType<typeof clients> | undefined;
  try {
    provider = createServer((req, res) => { res.setHeader("content-type", "application/json"); if (req.url === "/.well-known/openid-configuration") return res.end(JSON.stringify({ issuer, jwks_uri: `${issuer}/jwks` })); if (req.url === "/jwks") return res.end(JSON.stringify({ keys: [publicJwk] })); res.statusCode = 404; res.end("{}"); }); await new Promise<void>(resolve => provider!.listen(0, "127.0.0.1", resolve)); const issuer = `http://127.0.0.1:${(provider.address() as any).port}`;
    await simulator.start(); active = clients(simulator); const targetArn = await functionWithPermission(simulator, active.lambda, "http-v2-remote-jwt-target"); const api = await active.apig.send(new CreateApiCommand({ Name: "remote-jwt", ProtocolType: "HTTP" })); const integration = await active.apig.send(new CreateIntegrationCommand({ ApiId: api.ApiId, IntegrationType: "AWS_PROXY", IntegrationUri: targetArn, PayloadFormatVersion: "2.0" })); const authorizer = await active.apig.send(new CreateAuthorizerCommand({ ApiId: api.ApiId, Name: "remote", AuthorizerType: "JWT", IdentitySource: ["$request.header.Authorization"], JwtConfiguration: { Issuer: issuer, Audience: ["remote-client"] } })); await active.apig.send(new CreateRouteCommand({ ApiId: api.ApiId, RouteKey: "GET /remote", Target: `integrations/${integration.IntegrationId}`, AuthorizationType: "JWT", AuthorizerId: authorizer.AuthorizerId })); await active.apig.send(new CreateStageCommand({ ApiId: api.ApiId, StageName: "$default", AutoDeploy: true })); await permit(active.lambda, "http-v2-remote-jwt-target", api.ApiId!);
    const now = Math.floor(clock.now() / 1000); const token = jwt(keys.privateKey, kid, { iss: issuer, aud: "remote-client", exp: now + 300, scope: "openid" }); const invoke = `http://127.0.0.1:${simulator.invokePort}/${api.ApiId}/remote`; assert.equal((await fetch(invoke, { headers: { authorization: `Bearer ${token}` } })).status, 401, "remote discovery cannot reach a private target without the second explicit opt-in");
    destroy(Object.values(active)); active = undefined; await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, clock, apiGatewayAllowRemoteJwtJwks: true, apiGatewayAllowPrivateJwtJwks: true, authMode: "off"}); await simulator.start(); active = clients(simulator); const restartedInvoke = `http://127.0.0.1:${simulator.invokePort}/${api.ApiId}/remote`; assert.equal((await fetch(restartedInvoke, { headers: { authorization: `Bearer ${token}` } })).status, 201);
    await new Promise<void>(resolve => provider!.close(() => resolve())); provider = undefined; assert.equal((await fetch(restartedInvoke, { headers: { authorization: `Bearer ${token}` } })).status, 201, "remote JWKS remains available from the bounded in-memory cache");
  } finally { if (active) destroy(Object.values(active)); await simulator.stop().catch(() => undefined); if (provider) await new Promise<void>(resolve => provider!.close(() => resolve())); await rm(root, { recursive: true, force: true }); }
});
