import assert from "node:assert/strict";
import { createHash, createHmac } from "node:crypto";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { AttachRolePolicyCommand, CreatePolicyCommand, CreateRoleCommand, IAMClient } from "@aws-sdk/client-iam";
import { APIGatewayClient, CreateAuthorizerCommand, CreateDeploymentCommand, CreateResourceCommand, CreateRestApiCommand, GetResourcesCommand, PutIntegrationCommand, PutMethodCommand, UpdateRestApiCommand } from "@aws-sdk/client-api-gateway";
import { CreateTableCommand, DeleteItemCommand, DynamoDBClient, GetItemCommand, ListTablesCommand, PutItemCommand } from "@aws-sdk/client-dynamodb";
import { AddPermissionCommand, CreateFunctionCommand, LambdaClient } from "@aws-sdk/client-lambda";
import { AssumeRoleCommand, GetAccessKeyInfoCommand, GetCallerIdentityCommand, STSClient } from "@aws-sdk/client-sts";
import { TestClock } from "../src/core/clock.js";
import { StackSim } from "../src/server.js";
import { waitForTableActive } from "./support/dynamodb.js";

const adminCredentials = { accessKeyId: "admin", secretAccessKey: "password" };

function signedHeaders(urlValue: string, credentials: { accessKeyId: string; secretAccessKey: string; sessionToken?: string }, date: Date): Record<string, string> {
  const url = new URL(urlValue); const amzDate = date.toISOString().replace(/[:-]|\.\d{3}/g, ""); const shortDate = amzDate.slice(0, 8); const payloadHash = createHash("sha256").update("").digest("hex");
  const values: Record<string, string> = { host: url.host, "x-amz-content-sha256": payloadHash, "x-amz-date": amzDate }; if (credentials.sessionToken) values["x-amz-security-token"] = credentials.sessionToken;
  const names = Object.keys(values).sort(); const canonicalHeaders = names.map(name => `${name}:${values[name]}\n`).join(""); const canonicalQuery = [...url.searchParams.entries()].map(([key, value]) => [encodeURIComponent(key), encodeURIComponent(value)] as const).sort((a, b) => a[0].localeCompare(b[0]) || a[1].localeCompare(b[1])).map(([key, value]) => `${key}=${value}`).join("&");
  const canonicalRequest = `GET\n${url.pathname}\n${canonicalQuery}\n${canonicalHeaders}\n${names.join(";")}\n${payloadHash}`; const scope = `${shortDate}/eu-west-1/execute-api/aws4_request`; const stringToSign = `AWS4-HMAC-SHA256\n${amzDate}\n${scope}\n${createHash("sha256").update(canonicalRequest).digest("hex")}`;
  const hmac = (key: string | Buffer, value: string) => createHmac("sha256", key).update(value).digest(); const signingKey = hmac(hmac(hmac(hmac(`AWS4${credentials.secretAccessKey}`, shortDate), "eu-west-1"), "execute-api"), "aws4_request"); const signature = createHmac("sha256", signingKey).update(stringToSign).digest("hex");
  const headers = Object.fromEntries(Object.entries(values).filter(([name]) => name !== "host")); headers.authorization = `AWS4-HMAC-SHA256 Credential=${credentials.accessKeyId}/${scope}, SignedHeaders=${names.join(";")}, Signature=${signature}`; return headers;
}

test("SigV4 validation, IAM policy enforcement, STS sessions, trust, session intersection, chaining, expiration, and restart", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-auth-sts-")); const clock = new TestClock(Date.now()); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1", clock, authMode: "enforce", cdkBootstrap: true }); let clients: Array<{ destroy(): void }> = [];
  try {
    await simulator.start(); let endpoint = `http://127.0.0.1:${simulator.port}`;
    const iam = new IAMClient({ endpoint, region: "eu-west-1", credentials: adminCredentials }); const dynamoRoot = new DynamoDBClient({ endpoint, region: "eu-west-1", credentials: adminCredentials }); const stsRoot = new STSClient({ endpoint, region: "eu-west-1", credentials: adminCredentials }); const lambda = new LambdaClient({ endpoint, region: "eu-west-1", credentials: adminCredentials }); const apigateway = new APIGatewayClient({ endpoint, region: "eu-west-1", credentials: adminCredentials }); clients.push(iam, dynamoRoot, stsRoot, lambda, apigateway);
    await dynamoRoot.send(new CreateTableCommand({ TableName: "Protected", BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "id", AttributeType: "S" }], KeySchema: [{ AttributeName: "id", KeyType: "HASH" }] })); await waitForTableActive(dynamoRoot, "Protected", clock); await dynamoRoot.send(new PutItemCommand({ TableName: "Protected", Item: { id: { S: "one" }, value: { S: "secret" } } }));
    const roleArn = "arn:aws:iam::000000000000:role/reader"; const trust = JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { AWS: "arn:aws:iam::000000000000:root" }, Action: ["sts:AssumeRole", "sts:TagSession"], Condition: { StringEquals: { "sts:ExternalId": "course-42" } } }, { Effect: "Allow", Principal: { Service: "lambda.amazonaws.com" }, Action: "sts:AssumeRole" }] }); await iam.send(new CreateRoleCommand({ RoleName: "reader", AssumeRolePolicyDocument: trust, MaxSessionDuration: 7200 }));
    const policy = JSON.stringify({ Version: "2012-10-17", Statement: [
      { Sid: "ReadInRegion", Effect: "Allow", Action: "dynamodb:Get*", Resource: "arn:aws:dynamodb:eu-west-1:000000000000:table/Protected", Condition: { StringEquals: { "aws:RequestedRegion": "eu-west-1" }, IpAddress: { "aws:SourceIp": "127.0.0.1/32" } } },
      { Sid: "NoDelete", Effect: "Deny", Action: "dynamodb:DeleteItem", Resource: "*" },
      { Sid: "Chain", Effect: "Allow", Action: "sts:AssumeRole", Resource: roleArn },
    ] }); const createdPolicy = await iam.send(new CreatePolicyCommand({ PolicyName: "ReaderPolicy", PolicyDocument: policy })); await iam.send(new AttachRolePolicyCommand({ RoleName: "reader", PolicyArn: createdPolicy.Policy!.Arn! }));
    await assert.rejects(stsRoot.send(new AssumeRoleCommand({ RoleArn: roleArn, RoleSessionName: "missing-external" })), (error: any) => error.name.startsWith("AccessDenied"));
    const assumed = await stsRoot.send(new AssumeRoleCommand({ RoleArn: roleArn, RoleSessionName: "student", ExternalId: "course-42", SourceIdentity: "lesson", Tags: [{ Key: "course", Value: "aws" }], DurationSeconds: 3600 })); assert.match(assumed.Credentials?.AccessKeyId ?? "", /^ASIA/); assert.equal(assumed.SourceIdentity, "lesson");
    const sessionCredentials = { accessKeyId: assumed.Credentials!.AccessKeyId!, secretAccessKey: assumed.Credentials!.SecretAccessKey!, sessionToken: assumed.Credentials!.SessionToken! }; const stsSession = new STSClient({ endpoint, region: "eu-west-1", credentials: sessionCredentials }); const dynamoSession = new DynamoDBClient({ endpoint, region: "eu-west-1", credentials: sessionCredentials }); clients.push(stsSession, dynamoSession);
    const identity = await stsSession.send(new GetCallerIdentityCommand({})); assert.equal(identity.Account, "000000000000"); assert.match(identity.Arn ?? "", /assumed-role\/reader\/student$/); assert.equal((await stsRoot.send(new GetAccessKeyInfoCommand({ AccessKeyId: sessionCredentials.accessKeyId }))).Account, "000000000000");
    assert.equal((await dynamoSession.send(new GetItemCommand({ TableName: "Protected", Key: { id: { S: "one" } } }))).Item?.value?.S, "secret"); await assert.rejects(dynamoSession.send(new PutItemCommand({ TableName: "Protected", Item: { id: { S: "two" } } })), (error: any) => error.name === "AccessDeniedException"); await assert.rejects(dynamoSession.send(new DeleteItemCommand({ TableName: "Protected", Key: { id: { S: "one" } } })), (error: any) => error.name === "AccessDeniedException");
    await assert.rejects(stsSession.send(new AssumeRoleCommand({ RoleArn: roleArn, RoleSessionName: "too-long", ExternalId: "course-42", DurationSeconds: 7200 })), (error: any) => error.name.startsWith("Validation"));
    const limited = await stsRoot.send(new AssumeRoleCommand({ RoleArn: roleArn, RoleSessionName: "limited", ExternalId: "course-42", Policy: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Action: "dynamodb:GetItem", Resource: "*" }] }) })); const limitedClient = new DynamoDBClient({ endpoint, region: "eu-west-1", credentials: { accessKeyId: limited.Credentials!.AccessKeyId!, secretAccessKey: limited.Credentials!.SecretAccessKey!, sessionToken: limited.Credentials!.SessionToken! } }); clients.push(limitedClient); assert.equal((await limitedClient.send(new GetItemCommand({ TableName: "Protected", Key: { id: { S: "one" } } }))).Item?.id?.S, "one"); await assert.rejects(limitedClient.send(new ListTablesCommand({})), (error: any) => error.name === "AccessDeniedException");
    const wrong = new DynamoDBClient({ endpoint, region: "eu-west-1", credentials: { accessKeyId: "admin", secretAccessKey: "wrong" } }); clients.push(wrong); await assert.rejects(wrong.send(new ListTablesCommand({})), (error: any) => error.name === "SignatureDoesNotMatch");
    const zip = await readFile(join(process.cwd(), "examples/lambda/function.zip")); const secureFunction = await lambda.send(new CreateFunctionCommand({ FunctionName: "secure-api-handler", Runtime: "nodejs22.x", Role: roleArn, Handler: "handler.loggingHandler", Code: { ZipFile: zip } })); const api = await apigateway.send(new CreateRestApiCommand({ name: "secure-api" })); const rootResource = (await apigateway.send(new GetResourcesCommand({ restApiId: api.id! }))).items!.find(resource => resource.path === "/")!; const secure = await apigateway.send(new CreateResourceCommand({ restApiId: api.id!, parentId: rootResource.id!, pathPart: "secure" })); await apigateway.send(new PutMethodCommand({ restApiId: api.id!, resourceId: secure.id!, httpMethod: "GET", authorizationType: "AWS_IAM" })); await apigateway.send(new PutIntegrationCommand({ restApiId: api.id!, resourceId: secure.id!, httpMethod: "GET", type: "AWS_PROXY", integrationHttpMethod: "POST", uri: `arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/${secureFunction.FunctionArn}/invocations` })); await apigateway.send(new CreateDeploymentCommand({ restApiId: api.id!, stageName: "dev" })); const invokeUrl = `http://127.0.0.1:${simulator.invokePort}/${api.id}/dev/secure`;
    assert.equal((await fetch(invokeUrl)).status, 403, "AWS_IAM methods must reject unsigned requests"); assert.equal((await fetch(invokeUrl, { headers: signedHeaders(invokeUrl, sessionCredentials, new Date(clock.now())) })).status, 403, "a valid signature without an identity or resource allow must be denied");
    await apigateway.send(new UpdateRestApiCommand({ restApiId: api.id!, patchOperations: [{ op: "replace", path: "/policy", value: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { AWS: roleArn }, Action: "execute-api:Invoke", Resource: "execute-api:/dev/GET/secure" }] }) }] })); await apigateway.send(new CreateDeploymentCommand({ restApiId: api.id!, stageName: "dev" })); assert.equal((await fetch(invokeUrl, { headers: signedHeaders(invokeUrl, sessionCredentials, new Date(clock.now())) })).status, 403, "a resource-policy allow must still require Lambda integration permission"); await lambda.send(new AddPermissionCommand({ FunctionName: "secure-api-handler", StatementId: "api", Action: "lambda:InvokeFunction", Principal: "apigateway.amazonaws.com", SourceArn: `arn:aws:execute-api:eu-west-1:000000000000:${api.id}/*/*/*` })); assert.equal((await fetch(invokeUrl, { headers: signedHeaders(invokeUrl, sessionCredentials, new Date(clock.now())) })).status, 200, "a same-account resource-policy role allow must authorize its assumed-role session");
    await apigateway.send(new UpdateRestApiCommand({ restApiId: api.id!, patchOperations: [{ op: "remove", path: "/policy" }] })); await apigateway.send(new CreateDeploymentCommand({ restApiId: api.id!, stageName: "dev" })); assert.equal((await fetch(invokeUrl, { headers: signedHeaders(invokeUrl, sessionCredentials, new Date(clock.now())) })).status, 403, "removing the resource allow must restore the implicit deny"); const invokePolicy = await iam.send(new CreatePolicyCommand({ PolicyName: "InvokeSecureApi", PolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Action: "execute-api:Invoke", Resource: `arn:aws:execute-api:eu-west-1:000000000000:${api.id}/dev/GET/secure` }] }) })); await iam.send(new AttachRolePolicyCommand({ RoleName: "reader", PolicyArn: invokePolicy.Policy!.Arn! })); assert.equal((await fetch(invokeUrl, { headers: signedHeaders(invokeUrl, sessionCredentials, new Date(clock.now())) })).status, 200, "an identity allow must authorize a same-account request without a resource policy");
    await apigateway.send(new UpdateRestApiCommand({ restApiId: api.id!, patchOperations: [{ op: "replace", path: "/policy", value: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Deny", Principal: "*", Action: "execute-api:Invoke", Resource: `arn:aws:execute-api:eu-west-1:000000000000:${api.id}/dev/GET/secure` }] }) }] })); await apigateway.send(new CreateDeploymentCommand({ restApiId: api.id!, stageName: "dev" })); assert.equal((await fetch(invokeUrl, { headers: signedHeaders(invokeUrl, sessionCredentials, new Date(clock.now())) })).status, 403, "an API resource-policy explicit deny must override the identity allow");
    const strictAuthorizerFunction = await lambda.send(new CreateFunctionCommand({ FunctionName: "strict-authorizer", Runtime: "nodejs22.x", Role: roleArn, Handler: "handler.authorizerHandler", Code: { ZipFile: zip } })); const strictTargetFunction = await lambda.send(new CreateFunctionCommand({ FunctionName: "strict-authorizer-target", Runtime: "nodejs22.x", Role: roleArn, Handler: "handler.proxyEchoHandler", Code: { ZipFile: zip } })); const strictApi = await apigateway.send(new CreateRestApiCommand({ name: "strict-authorizer-api" })); const strictRoot = (await apigateway.send(new GetResourcesCommand({ restApiId: strictApi.id! }))).items!.find(resource => resource.path === "/")!; const strictAuthorizer = await apigateway.send(new CreateAuthorizerCommand({ restApiId: strictApi.id!, name: "strict", type: "TOKEN", authorizerUri: `arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/${strictAuthorizerFunction.FunctionArn}/invocations`, identitySource: "method.request.header.Authorization", authorizerResultTtlInSeconds: 0 })); const strictResource = await apigateway.send(new CreateResourceCommand({ restApiId: strictApi.id!, parentId: strictRoot.id!, pathPart: "strict" })); await apigateway.send(new PutMethodCommand({ restApiId: strictApi.id!, resourceId: strictResource.id!, httpMethod: "GET", authorizationType: "CUSTOM", authorizerId: strictAuthorizer.id })); await apigateway.send(new PutIntegrationCommand({ restApiId: strictApi.id!, resourceId: strictResource.id!, httpMethod: "GET", type: "AWS_PROXY", integrationHttpMethod: "POST", uri: `arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/${strictTargetFunction.FunctionArn}/invocations` })); await lambda.send(new AddPermissionCommand({ FunctionName: "strict-authorizer-target", StatementId: "gateway-target", Action: "lambda:InvokeFunction", Principal: "apigateway.amazonaws.com", SourceArn: `arn:aws:execute-api:eu-west-1:000000000000:${strictApi.id}/*/*/*` })); await apigateway.send(new CreateDeploymentCommand({ restApiId: strictApi.id!, stageName: "dev" })); await new Promise(resolve => setTimeout(resolve, 0)); const strictUrl = `http://127.0.0.1:${simulator.invokePort}/${strictApi.id}/dev/strict`; assert.equal((await fetch(strictUrl, { headers: { authorization: "allow" } })).status, 500, "authorizer Lambda invocation must require a matching resource policy"); await lambda.send(new AddPermissionCommand({ FunctionName: "strict-authorizer", StatementId: "gateway-authorizer", Action: "lambda:InvokeFunction", Principal: "apigateway.amazonaws.com", SourceArn: `arn:aws:execute-api:eu-west-1:000000000000:${strictApi.id}/authorizers/${strictAuthorizer.id}` })); assert.equal((await fetch(strictUrl, { headers: { authorization: "allow" } })).status, 200);
    assert.ok(simulator.store.ensureAccount().iam.authorizationDecisions.some(decision => decision.decision === "explicitDeny" && decision.action === "dynamodb:DeleteItem"));

    clients.forEach(client => client.destroy()); clients = []; await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1", clock, authMode: "enforce", cdkBootstrap: true }); await simulator.start(); endpoint = `http://127.0.0.1:${simulator.port}`; const restartedSts = new STSClient({ endpoint, region: "eu-west-1", credentials: sessionCredentials }); clients.push(restartedSts); assert.match((await restartedSts.send(new GetCallerIdentityCommand({}))).Arn ?? "", /student$/);
    clock.advance(3_601_000); await assert.rejects(restartedSts.send(new GetCallerIdentityCommand({})), (error: any) => error.name === "InvalidClientTokenId");
  } finally { clients.forEach(client => client.destroy()); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});
