import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import {
  CloudWatchClient,
  DeleteInsightRulesCommand,
  DescribeInsightRulesCommand,
  DisableInsightRulesCommand,
  EnableInsightRulesCommand,
  GetInsightRuleReportCommand,
  ListManagedInsightRulesCommand,
  ListTagsForResourceCommand,
  PutInsightRuleCommand,
  PutManagedInsightRulesCommand,
  TagResourceCommand,
  UntagResourceCommand,
} from "@aws-sdk/client-cloudwatch";
import { CloudWatchLogsClient, CreateLogGroupCommand, CreateLogStreamCommand, PutLogEventsCommand } from "@aws-sdk/client-cloudwatch-logs";
import { CreateTableCommand, DynamoDBClient, GetItemCommand, PutItemCommand } from "@aws-sdk/client-dynamodb";
import { TestClock } from "../src/core/clock.js";
import { CURRENT_SCHEMA_VERSION } from "../src/migrations/v1-to-v2.js";
import { StackSim } from "../src/server.js";

const region = "eu-west-1";
const credentials = { accessKeyId: "admin", secretAccessKey: "password" };
function clients(simulator: StackSim) { const options = { endpoint: `http://127.0.0.1:${simulator.port}`, region, credentials, maxAttempts: 1 }; return { cloudwatch: new CloudWatchClient(options), logs: new CloudWatchLogsClient(options), dynamodb: new DynamoDBClient(options) }; }
const customDefinition = JSON.stringify({ Schema: { Name: "CloudWatchLogRule", Version: 1 }, LogGroupNames: ["/learning/orders*"], LogFormat: "JSON", Contribution: { Keys: ["$.service"], ValueOf: "$.bytes", Filters: [{ Match: "$.status", GreaterThan: 399 }] }, AggregateOn: "Sum" });

test("CW-08F contributor and DynamoDB managed insight rules implement lifecycle, reports, tags, pagination, Query XML, windows, and restart", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-cw08f-")); const clock = new TestClock(Date.parse("2026-07-17T14:00:00Z")); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, clock, authMode: "off"}); let active: ReturnType<typeof clients> | undefined;
  try {
    await simulator.start(); active = clients(simulator); const { cloudwatch, logs, dynamodb } = active; await logs.send(new CreateLogGroupCommand({ logGroupName: "/learning/orders" })); await logs.send(new CreateLogStreamCommand({ logGroupName: "/learning/orders", logStreamName: "application" })); await logs.send(new PutLogEventsCommand({ logGroupName: "/learning/orders", logStreamName: "application", logEvents: [{ timestamp: clock.now(), message: JSON.stringify({ service: "before", status: 500, bytes: 100 }) }] })); clock.advance(1_000);

    await cloudwatch.send(new PutInsightRuleCommand({ RuleName: "order_errors", RuleDefinition: customDefinition, RuleState: "ENABLED", ApplyOnTransformedLogs: true, Tags: [{ Key: "team", Value: "platform" }] })); const arn = `arn:aws:cloudwatch:${region}:000000000000:insight-rule/order_errors`; await logs.send(new PutLogEventsCommand({ logGroupName: "/learning/orders", logStreamName: "application", logEvents: [{ timestamp: clock.now(), message: JSON.stringify({ service: "api", status: 500, bytes: 5 }) }, { timestamp: clock.now() + 1, message: JSON.stringify({ service: "worker", status: 503, bytes: 2 }) }, { timestamp: clock.now() + 2, message: JSON.stringify({ service: "api", status: 502, bytes: 7 }) }, { timestamp: clock.now() + 3, message: JSON.stringify({ service: "ignored", status: 200, bytes: 100 }) }] }));
    let described = await cloudwatch.send(new DescribeInsightRulesCommand({ MaxResults: 1 })); assert.equal(described.InsightRules?.[0].Name, "order_errors"); assert.equal(described.InsightRules?.[0].State, "ENABLED"); assert.equal(described.InsightRules?.[0].ApplyOnTransformedLogs, true); assert.equal(described.InsightRules?.[0].Schema, JSON.stringify({ Name: "CloudWatchLogRule", Version: 1 }));
    let report = await cloudwatch.send(new GetInsightRuleReportCommand({ RuleName: "order_errors", StartTime: new Date(clock.now() - 60_000), EndTime: new Date(clock.now() + 60_000), Period: 60, MaxContributorCount: 1, Metrics: ["UniqueContributors", "MaxContributorValue", "SampleCount", "Sum", "Average"], OrderBy: "Sum" })); assert.deepEqual(report.KeyLabels, ["$.service"]); assert.equal(report.AggregationStatistic, "SUM"); assert.equal(report.AggregateValue, 14); assert.equal(report.ApproximateUniqueCount, 2); assert.deepEqual(report.Contributors?.map(item => [item.Keys?.[0], item.ApproximateAggregateValue]), [["api", 12]]); assert.equal(report.MetricDatapoints?.[0].UniqueContributors, 2); assert.equal(report.MetricDatapoints?.[0].SampleCount, 3); assert.equal(report.MetricDatapoints?.[0].Sum, 14);

    await cloudwatch.send(new DisableInsightRulesCommand({ RuleNames: ["order_errors"] })); clock.advance(1_000); await logs.send(new PutLogEventsCommand({ logGroupName: "/learning/orders", logStreamName: "application", logEvents: [{ timestamp: clock.now(), message: JSON.stringify({ service: "disabled", status: 500, bytes: 50 }) }] })); clock.advance(1_000); await cloudwatch.send(new EnableInsightRulesCommand({ RuleNames: ["order_errors"] })); await logs.send(new PutLogEventsCommand({ logGroupName: "/learning/orders", logStreamName: "application", logEvents: [{ timestamp: clock.now(), message: JSON.stringify({ service: "api", status: 500, bytes: 3 }) }] })); report = await cloudwatch.send(new GetInsightRuleReportCommand({ RuleName: "order_errors", StartTime: new Date(clock.now() - 60_000), EndTime: new Date(clock.now() + 60_000), Period: 60 })); assert.equal(report.AggregateValue, 17); assert.equal(report.ApproximateUniqueCount, 2, "events ingested before creation or while disabled are not backfilled");

    await cloudwatch.send(new TagResourceCommand({ ResourceARN: arn, Tags: [{ Key: "environment", Value: "local" }] })); await cloudwatch.send(new UntagResourceCommand({ ResourceARN: arn, TagKeys: ["team"] })); assert.deepEqual((await cloudwatch.send(new ListTagsForResourceCommand({ ResourceARN: arn }))).Tags, [{ Key: "environment", Value: "local" }]); await assert.rejects(cloudwatch.send(new PutInsightRuleCommand({ RuleName: "invalid", RuleDefinition: JSON.stringify({ Schema: { Name: "CloudWatchLogRule", Version: 1 }, LogGroupARNs: ["arn:aws:logs:us-east-1:111111111111:log-group:x"], LogFormat: "JSON", Contribution: { Keys: ["$.x"] }, AggregateOn: "Count" }) })), (error: any) => /^InvalidParameterValue/.test(error.name));

    await cloudwatch.send(new PutInsightRuleCommand({ RuleName: "second_rule", RuleDefinition: JSON.stringify({ Schema: { Name: "CloudWatchLogRule", Version: 1 }, LogGroupNames: ["/learning/orders"], LogFormat: "JSON", Contribution: { Keys: ["$.service"] }, AggregateOn: "Count" }), RuleState: "DISABLED" })); const first = await cloudwatch.send(new DescribeInsightRulesCommand({ MaxResults: 1 })); assert.ok(first.NextToken); const second = await cloudwatch.send(new DescribeInsightRulesCommand({ MaxResults: 1, NextToken: first.NextToken })); assert.equal(second.InsightRules?.length, 1);
    const query = await fetch(`http://127.0.0.1:${simulator.port}`, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ Action: "DescribeInsightRules", Version: "2010-08-01", MaxResults: "10" }) }); const xml = await query.text(); assert.equal(query.status, 200); assert.match(xml, /<Name>order_errors<\/Name>/); assert.match(xml, /<ApplyOnTransformedLogs>true<\/ApplyOnTransformedLogs>/);

    await dynamodb.send(new CreateTableCommand({ TableName: "ManagedOrders", BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "pk", AttributeType: "S" }, { AttributeName: "sk", AttributeType: "N" }], KeySchema: [{ AttributeName: "pk", KeyType: "HASH" }, { AttributeName: "sk", KeyType: "RANGE" }] })); const resourceArn = `arn:aws:dynamodb:${region}:000000000000:table/ManagedOrders`; const managedPage = await cloudwatch.send(new ListManagedInsightRulesCommand({ ResourceARN: resourceArn, MaxResults: 2 })); assert.deepEqual(managedPage.ManagedRules?.map(item => item.TemplateName), ["DynamoDBContributorInsights-PKC", "DynamoDBContributorInsights-SKC"]); assert.ok(managedPage.NextToken); const managedNext = await cloudwatch.send(new ListManagedInsightRulesCommand({ ResourceARN: resourceArn, MaxResults: 2, NextToken: managedPage.NextToken })); assert.deepEqual(managedNext.ManagedRules?.map(item => item.TemplateName), ["DynamoDBContributorInsights-PKT", "DynamoDBContributorInsights-SKT"]);
    const enabled = await cloudwatch.send(new PutManagedInsightRulesCommand({ ManagedRules: [{ TemplateName: "DynamoDBContributorInsights-PKC", ResourceARN: resourceArn, Tags: [{ Key: "source", Value: "managed" }] }, { TemplateName: "PrivateLinkInvalid", ResourceARN: resourceArn }] })); assert.equal(enabled.Failures?.length, 1); const managed = (await cloudwatch.send(new ListManagedInsightRulesCommand({ ResourceARN: resourceArn }))).ManagedRules?.find(item => item.TemplateName === "DynamoDBContributorInsights-PKC"); assert.equal(managed?.RuleState?.State, "ENABLED"); const managedName = managed?.RuleState?.RuleName!; clock.advance(1_000); const item = { pk: { S: "hot" }, sk: { N: "1" } }; await dynamodb.send(new PutItemCommand({ TableName: "ManagedOrders", Item: item })); await dynamodb.send(new GetItemCommand({ TableName: "ManagedOrders", Key: item })); const managedReport = await cloudwatch.send(new GetInsightRuleReportCommand({ RuleName: managedName, StartTime: new Date(clock.now() - 60_000), EndTime: new Date(clock.now() + 60_000), Period: 60 })); assert.deepEqual(managedReport.KeyLabels, ["pk"]); assert.equal(managedReport.AggregateValue, 2); assert.deepEqual(managedReport.Contributors?.[0].Keys, ["hot"]); await cloudwatch.send(new DisableInsightRulesCommand({ RuleNames: [managedName] })); assert.equal((await cloudwatch.send(new ListManagedInsightRulesCommand({ ResourceARN: resourceArn }))).ManagedRules?.find(item => item.TemplateName === "DynamoDBContributorInsights-PKC")?.RuleState?.State, "DISABLED");

    const partial = await cloudwatch.send(new DeleteInsightRulesCommand({ RuleNames: ["second_rule", "missing_rule"] })); assert.equal(partial.Failures?.length, 1); active.cloudwatch.destroy(); active.logs.destroy(); active.dynamodb.destroy(); active = undefined; await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, clock, authMode: "off"}); await simulator.start(); active = clients(simulator); assert.equal(simulator.store.state.schemaVersion, CURRENT_SCHEMA_VERSION); described = await active.cloudwatch.send(new DescribeInsightRulesCommand({ MaxResults: 10 })); assert.deepEqual(described.InsightRules?.map(rule => rule.Name).sort(), [managedName, "order_errors"].sort()); assert.equal(described.InsightRules?.find(rule => rule.Name === managedName)?.State, "DISABLED");
  } finally { if (active) Object.values(active).forEach(client => client.destroy()); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});
