import assert from "node:assert/strict";
import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import {
  BatchWriteItemCommand,
  CreateTableCommand,
  DeleteItemCommand,
  DescribeTableCommand,
  DynamoDBClient,
  PutItemCommand,
  TransactWriteItemsCommand,
  UpdateTableCommand,
} from "@aws-sdk/client-dynamodb";
import {
  DescribeStreamCommand,
  DynamoDBStreamsClient,
  GetRecordsCommand,
  GetShardIteratorCommand,
  ListStreamsCommand,
} from "@aws-sdk/client-dynamodb-streams";
import { TestClock } from "../src/core/clock.js";
import { CURRENT_SCHEMA_VERSION } from "../src/migrations/v1-to-v2.js";
import { StackSim } from "../src/server.js";
import { waitForTableActive } from "./support/dynamodb.js";
import { assertPrivateFile } from "./support/platform.js";

const credentials = { accessKeyId: "admin", secretAccessKey: "password" };
function clients(simulator: StackSim): { dynamodb: DynamoDBClient; streams: DynamoDBStreamsClient } { const options = { endpoint: `http://127.0.0.1:${simulator.port}`, region: "eu-west-1", credentials }; return { dynamodb: new DynamoDBClient(options), streams: new DynamoDBStreamsClient(options) }; }
async function tick(clock: TestClock, milliseconds = 50): Promise<void> { clock.advance(milliseconds); await new Promise<void>(resolve => setImmediate(resolve)); }
async function rejects(promise: Promise<unknown>, name: string): Promise<void> { await assert.rejects(promise, (error: any) => error.name === name); }

test("DynamoDB Streams returns ordered image-selected records for single, batch, transaction, and failed writes", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-ddb-streams-")); const clock = new TestClock(Date.parse("2026-07-15T16:00:00Z")); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1", clock, dynamoStreamRetentionMs: 2_000, authMode: "off"}); let dynamodb: DynamoDBClient | undefined; let streams: DynamoDBStreamsClient | undefined;
  try {
    await simulator.start(); ({ dynamodb, streams } = clients(simulator));
    const created = await dynamodb.send(new CreateTableCommand({ TableName: "StreamRecords", BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "id", AttributeType: "S" }], KeySchema: [{ AttributeName: "id", KeyType: "HASH" }], StreamSpecification: { StreamEnabled: true, StreamViewType: "NEW_AND_OLD_IMAGES" } }));
    await waitForTableActive(dynamodb, "StreamRecords", clock);
    const firstArn = created.TableDescription!.LatestStreamArn!; assert.equal(created.TableDescription?.StreamSpecification?.StreamViewType, "NEW_AND_OLD_IMAGES"); assert.equal(created.TableDescription?.LatestStreamLabel, firstArn.split("/stream/")[1]);
    const listed = await streams.send(new ListStreamsCommand({ TableName: "StreamRecords" })); assert.deepEqual(listed.Streams?.map(stream => stream.StreamArn), [firstArn]); await rejects(streams.send(new ListStreamsCommand({ TableName: "MissingTable" })), "ResourceNotFoundException"); const raw = await fetch(`http://127.0.0.1:${simulator.port}`, { method: "POST", headers: { "content-type": "application/x-amz-json-1.0", "x-amz-target": "DynamoDBStreams_20120810.ListStreams" }, body: JSON.stringify({ TableName: "StreamRecords" }) }); assert.equal(raw.status, 200); assert.match(raw.headers.get("content-type") ?? "", /application\/x-amz-json-1\.0/); assert.ok(raw.headers.get("x-amzn-requestid")); assert.deepEqual((await raw.json() as any).Streams.map((stream: any) => stream.StreamArn), [firstArn]); await rejects(streams.send(new GetRecordsCommand({ ShardIterator: "not-a-signed-iterator" })), "ValidationException"); const described = await streams.send(new DescribeStreamCommand({ StreamArn: firstArn })); const shardId = described.StreamDescription!.Shards![0].ShardId!; assert.equal(described.StreamDescription?.StreamStatus, "ENABLED"); assert.deepEqual(described.StreamDescription?.KeySchema, [{ AttributeName: "id", KeyType: "HASH" }]);

    await dynamodb.send(new PutItemCommand({ TableName: "StreamRecords", Item: { id: { S: "alpha" }, version: { N: "1" } } }));
    await dynamodb.send(new PutItemCommand({ TableName: "StreamRecords", Item: { id: { S: "alpha" }, version: { N: "2" } } }));
    await dynamodb.send(new DeleteItemCommand({ TableName: "StreamRecords", Key: { id: { S: "alpha" } } }));
    await dynamodb.send(new BatchWriteItemCommand({ RequestItems: { StreamRecords: [{ PutRequest: { Item: { id: { S: "beta" }, version: { N: "1" } } } }, { PutRequest: { Item: { id: { S: "gamma" }, version: { N: "1" } } } }] } }));
    await dynamodb.send(new TransactWriteItemsCommand({ TransactItems: [{ Put: { TableName: "StreamRecords", Item: { id: { S: "beta" }, version: { N: "2" } } } }, { Delete: { TableName: "StreamRecords", Key: { id: { S: "gamma" } } } }] }));
    await rejects(dynamodb.send(new TransactWriteItemsCommand({ TransactItems: [{ Put: { TableName: "StreamRecords", Item: { id: { S: "never" } } } }, { ConditionCheck: { TableName: "StreamRecords", Key: { id: { S: "missing" } }, ConditionExpression: "attribute_exists(id)" } }] })), "TransactionCanceledException");

    let iterator = (await streams.send(new GetShardIteratorCommand({ StreamArn: firstArn, ShardId: shardId, ShardIteratorType: "TRIM_HORIZON" }))).ShardIterator!; const records: any[] = [];
    do { const page = await streams.send(new GetRecordsCommand({ ShardIterator: iterator, Limit: 2 })); records.push(...(page.Records ?? [])); iterator = page.NextShardIterator ?? ""; } while (iterator && records.length < 7);
    assert.deepEqual(records.map(record => record.eventName), ["INSERT", "MODIFY", "REMOVE", "INSERT", "INSERT", "MODIFY", "REMOVE"]); assert.deepEqual(records.map(record => record.dynamodb?.Keys?.id?.S), ["alpha", "alpha", "alpha", "beta", "gamma", "beta", "gamma"]); assert.deepEqual(records.map(record => record.dynamodb?.SequenceNumber), [...records.map(record => record.dynamodb!.SequenceNumber!)].sort());
    assert.equal(records[0].dynamodb?.OldImage, undefined); assert.equal(records[0].dynamodb?.NewImage?.version?.N, "1"); assert.equal(records[1].dynamodb?.OldImage?.version?.N, "1"); assert.equal(records[1].dynamodb?.NewImage?.version?.N, "2"); assert.equal(records[2].dynamodb?.OldImage?.version?.N, "2"); assert.equal(records[2].dynamodb?.NewImage, undefined); assert.equal(records.some(record => record.dynamodb?.Keys?.id?.S === "never"), false);

    const secondSequence = records[1].dynamodb!.SequenceNumber!; const at = (await streams.send(new GetShardIteratorCommand({ StreamArn: firstArn, ShardId: shardId, ShardIteratorType: "AT_SEQUENCE_NUMBER", SequenceNumber: secondSequence }))).ShardIterator!; assert.equal((await streams.send(new GetRecordsCommand({ ShardIterator: at, Limit: 1 }))).Records?.[0].eventName, "MODIFY"); const after = (await streams.send(new GetShardIteratorCommand({ StreamArn: firstArn, ShardId: shardId, ShardIteratorType: "AFTER_SEQUENCE_NUMBER", SequenceNumber: secondSequence }))).ShardIterator!; assert.equal((await streams.send(new GetRecordsCommand({ ShardIterator: after, Limit: 1 }))).Records?.[0].eventName, "REMOVE");

    await dynamodb.send(new UpdateTableCommand({ TableName: "StreamRecords", StreamSpecification: { StreamEnabled: true, StreamViewType: "NEW_IMAGE" } })); await tick(clock); const current = (await dynamodb.send(new DescribeTableCommand({ TableName: "StreamRecords" }))).Table!; const secondArn = current.LatestStreamArn!; assert.notEqual(secondArn, firstArn); assert.equal(current.StreamSpecification?.StreamViewType, "NEW_IMAGE"); assert.equal((await streams.send(new DescribeStreamCommand({ StreamArn: firstArn }))).StreamDescription?.StreamStatus, "DISABLED");
    const firstPage = await streams.send(new ListStreamsCommand({ TableName: "StreamRecords", Limit: 1 })); assert.equal(firstPage.Streams?.length, 1); assert.ok(firstPage.LastEvaluatedStreamArn); const secondPage = await streams.send(new ListStreamsCommand({ TableName: "StreamRecords", Limit: 1, ExclusiveStartStreamArn: firstPage.LastEvaluatedStreamArn })); assert.equal(secondPage.Streams?.length, 1); assert.notEqual(secondPage.Streams?.[0].StreamArn, firstPage.Streams?.[0].StreamArn);
    await dynamodb.send(new PutItemCommand({ TableName: "StreamRecords", Item: { id: { S: "new-view" }, version: { N: "3" } } })); const secondDescription = await streams.send(new DescribeStreamCommand({ StreamArn: secondArn })); const secondShard = secondDescription.StreamDescription!.Shards![0].ShardId!; const secondIterator = (await streams.send(new GetShardIteratorCommand({ StreamArn: secondArn, ShardId: secondShard, ShardIteratorType: "TRIM_HORIZON" }))).ShardIterator!; const newView = (await streams.send(new GetRecordsCommand({ ShardIterator: secondIterator }))).Records![0]; assert.equal(newView.dynamodb?.NewImage?.version?.N, "3"); assert.equal(newView.dynamodb?.OldImage, undefined);
    await dynamodb.send(new UpdateTableCommand({ TableName: "StreamRecords", StreamSpecification: { StreamEnabled: true, StreamViewType: "OLD_IMAGE" } })); await tick(clock); const oldArn = (await dynamodb.send(new DescribeTableCommand({ TableName: "StreamRecords" }))).Table!.LatestStreamArn!; await dynamodb.send(new PutItemCommand({ TableName: "StreamRecords", Item: { id: { S: "new-view" }, version: { N: "4" } } })); const oldDescription = await streams.send(new DescribeStreamCommand({ StreamArn: oldArn })); const oldIterator = (await streams.send(new GetShardIteratorCommand({ StreamArn: oldArn, ShardId: oldDescription.StreamDescription!.Shards![0].ShardId!, ShardIteratorType: "TRIM_HORIZON" }))).ShardIterator!; const oldView = (await streams.send(new GetRecordsCommand({ ShardIterator: oldIterator }))).Records![0]; assert.equal(oldView.dynamodb?.OldImage?.version?.N, "3"); assert.equal(oldView.dynamodb?.NewImage, undefined);
  } finally { dynamodb?.destroy(); streams?.destroy(); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("DynamoDB stream descriptors, records, iterator expiry, and configured retention survive restart", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-ddb-stream-restart-")); const clock = new TestClock(Date.parse("2026-07-15T18:00:00Z")); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1", clock, dynamoStreamRetentionMs: 2_000, authMode: "off"}); let dynamodb: DynamoDBClient | undefined; let streams: DynamoDBStreamsClient | undefined;
  try {
    await simulator.start(); ({ dynamodb, streams } = clients(simulator)); await dynamodb.send(new CreateTableCommand({ TableName: "RestartStream", BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "id", AttributeType: "S" }], KeySchema: [{ AttributeName: "id", KeyType: "HASH" }], StreamSpecification: { StreamEnabled: true, StreamViewType: "KEYS_ONLY" } })); await waitForTableActive(dynamodb, "RestartStream", clock); const table = (await dynamodb.send(new DescribeTableCommand({ TableName: "RestartStream" }))).Table!; const arn = table.LatestStreamArn!; await dynamodb.send(new PutItemCommand({ TableName: "RestartStream", Item: { id: { S: "durable" }, hidden: { S: "value" } } })); const description = await streams.send(new DescribeStreamCommand({ StreamArn: arn })); const shard = description.StreamDescription!.Shards![0].ShardId!; const streamRoot = join(root, "data", "dynamodb", "streams", "000000000000", "eu-west-1"); const streamDirectories = await readdir(streamRoot); const segment = join(streamRoot, streamDirectories[0], "segment-000001.jsonl"); await assertPrivateFile(segment); assert.doesNotMatch(await readFile(join(root, "state.json"), "utf8"), /"eventName"\s*:/);
    const durableIterator = (await streams.send(new GetShardIteratorCommand({ StreamArn: arn, ShardId: shard, ShardIteratorType: "TRIM_HORIZON" }))).ShardIterator!; dynamodb.destroy(); streams.destroy(); await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1", clock, dynamoStreamRetentionMs: 2_000, authMode: "off"}); await simulator.start(); ({ dynamodb, streams } = clients(simulator)); const durable = (await streams.send(new GetRecordsCommand({ ShardIterator: durableIterator }))).Records![0]; assert.deepEqual(durable.dynamodb?.Keys, { id: { S: "durable" } }); assert.equal(durable.dynamodb?.NewImage, undefined); assert.equal(simulator.store.state.schemaVersion, CURRENT_SCHEMA_VERSION);

    const expiring = (await streams.send(new GetShardIteratorCommand({ StreamArn: arn, ShardId: shard, ShardIteratorType: "LATEST" }))).ShardIterator!; await tick(clock, 15 * 60_000 + 1); await rejects(streams.send(new GetRecordsCommand({ ShardIterator: expiring })), "ExpiredIteratorException"); await rejects(streams.send(new GetShardIteratorCommand({ StreamArn: arn, ShardId: shard, ShardIteratorType: "AT_SEQUENCE_NUMBER", SequenceNumber: durable.dynamodb!.SequenceNumber! })), "TrimmedDataAccessException"); assert.equal((await streams.send(new ListStreamsCommand({ TableName: "RestartStream" }))).Streams?.length, 1);

    await dynamodb.send(new UpdateTableCommand({ TableName: "RestartStream", StreamSpecification: { StreamEnabled: false } })); await tick(clock); assert.equal((await dynamodb.send(new DescribeTableCommand({ TableName: "RestartStream" }))).Table?.LatestStreamArn, undefined); assert.equal((await streams.send(new DescribeStreamCommand({ StreamArn: arn }))).StreamDescription?.StreamStatus, "DISABLED"); await tick(clock, 2_001); assert.equal((await streams.send(new ListStreamsCommand({ TableName: "RestartStream" }))).Streams?.length, 0); await rejects(streams.send(new DescribeStreamCommand({ StreamArn: arn })), "ResourceNotFoundException");
  } finally { dynamodb?.destroy(); streams?.destroy(); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("schema v8 legacy stream hooks migrate without putting records in control-plane state", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-ddb-stream-migration-")); const clock = new TestClock(Date.parse("2026-07-15T20:00:00Z")); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1", clock, authMode: "off"}); let dynamodb: DynamoDBClient | undefined; let streams: DynamoDBStreamsClient | undefined;
  try {
    await simulator.start(); ({ dynamodb, streams } = clients(simulator)); await dynamodb.send(new CreateTableCommand({ TableName: "LegacyStream", BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "id", AttributeType: "S" }], KeySchema: [{ AttributeName: "id", KeyType: "HASH" }], StreamSpecification: { StreamEnabled: true, StreamViewType: "NEW_IMAGE" } })); await waitForTableActive(dynamodb, "LegacyStream", clock); const arn = (await dynamodb.send(new DescribeTableCommand({ TableName: "LegacyStream" }))).Table!.LatestStreamArn!; await dynamodb.send(new PutItemCommand({ TableName: "LegacyStream", Item: { id: { S: "legacy" }, value: { N: "8" } } })); const description = await streams.send(new DescribeStreamCommand({ StreamArn: arn })); const shard = description.StreamDescription!.Shards![0].ShardId!; const iterator = (await streams.send(new GetShardIteratorCommand({ StreamArn: arn, ShardId: shard, ShardIteratorType: "TRIM_HORIZON" }))).ShardIterator!; const record = (await streams.send(new GetRecordsCommand({ ShardIterator: iterator }))).Records![0]; dynamodb.destroy(); streams.destroy(); await simulator.stop();
    const statePath = join(root, "state.json"); const state = JSON.parse(await readFile(statePath, "utf8")); const region = state.accounts["000000000000"].regions["eu-west-1"]; state.schemaVersion = 8; region.tables.LegacyStream.streamRecords = [{ ...record, dynamodb: { ...record.dynamodb, ApproximateCreationDateTime: record.dynamodb!.ApproximateCreationDateTime!.getTime() / 1000 } }]; delete region.dynamodbStreams; await writeFile(statePath, JSON.stringify(state, null, 2), { mode: 0o600 }); await rm(join(root, "data", "dynamodb", "streams"), { recursive: true, force: true });
    simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1", clock, authMode: "off"}); await simulator.start(); ({ dynamodb, streams } = clients(simulator)); const migrated = await streams.send(new ListStreamsCommand({ TableName: "LegacyStream" })); assert.equal(migrated.Streams?.length, 1); const migratedDescription = await streams.send(new DescribeStreamCommand({ StreamArn: migrated.Streams![0].StreamArn! })); const migratedIterator = (await streams.send(new GetShardIteratorCommand({ StreamArn: migrated.Streams![0].StreamArn!, ShardId: migratedDescription.StreamDescription!.Shards![0].ShardId!, ShardIteratorType: "TRIM_HORIZON" }))).ShardIterator!; assert.equal((await streams.send(new GetRecordsCommand({ ShardIterator: migratedIterator }))).Records?.[0].dynamodb?.NewImage?.value?.N, "8"); assert.equal(simulator.store.state.schemaVersion, CURRENT_SCHEMA_VERSION); assert.doesNotMatch(await readFile(statePath, "utf8"), /"eventName"\s*:/);
  } finally { dynamodb?.destroy(); streams?.destroy(); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});
