import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { AttachRolePolicyCommand, CreatePolicyCommand, CreateRoleCommand, IAMClient } from "@aws-sdk/client-iam";
import { AssumeRoleCommand, STSClient } from "@aws-sdk/client-sts";
import { CreateTableCommand, DeleteResourcePolicyCommand, DeleteTableCommand, DescribeTableCommand, DynamoDBClient, GetItemCommand, GetResourcePolicyCommand, PutItemCommand, PutResourcePolicyCommand, QueryCommand } from "@aws-sdk/client-dynamodb";
import { TestClock } from "../src/core/clock.js";
import { CURRENT_SCHEMA_VERSION } from "../src/migrations/v1-to-v2.js";
import { StackSim } from "../src/server.js";
import { waitForTableActive } from "./support/dynamodb.js";

const adminCredentials = { accessKeyId: "admin", secretAccessKey: "password" };
const region = "eu-west-1";

function dynamo(simulator: StackSim, credentials: any = adminCredentials): DynamoDBClient { return new DynamoDBClient({ endpoint: `http://127.0.0.1:${simulator.port}`, region, credentials }); }
function tableInput(name: string, ResourcePolicy?: string): any { return { TableName: name, BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "id", AttributeType: "S" }], KeySchema: [{ AttributeName: "id", KeyType: "HASH" }], ...(ResourcePolicy ? { ResourcePolicy } : {}) }; }
function policy(statements: any[]): string { return JSON.stringify({ Version: "2012-10-17", Statement: statements }); }

test("DynamoDB resource-policy APIs persist normalized documents, revisions, guards, and table/stream attachments", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-ddb-policies-")); const clock = new TestClock(Date.parse("2026-07-15T20:00:00Z")); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, clock, authMode: "off"}); let client: DynamoDBClient | undefined;
  try {
    await simulator.start(); client = dynamo(simulator); const tableArn = `arn:aws:dynamodb:${region}:000000000000:table/PolicyRecords`;
    await client.send(new CreateTableCommand(tableInput("PolicyRecords")));
    await assert.rejects(client.send(new GetResourcePolicyCommand({ ResourceArn: tableArn })), (error: any) => error.name === "PolicyNotFoundException");
    await assert.rejects(client.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: "{" })), (error: any) => error.name === "ValidationException"); await assert.rejects(client.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: policy([{ Effect: "Allow", Principal: "*", Action: "s3:GetObject", Resource: "*" }]) })), (error: any) => error.name === "ValidationException"); await assert.rejects(client.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: `${policy([{ Effect: "Allow", Principal: "*", Action: "dynamodb:GetItem", Resource: tableArn }])}${" ".repeat(20 * 1024)}` })), (error: any) => error.name === "LimitExceededException");
    const firstDocument = policy([{ Sid: "Read", Effect: "Allow", Principal: { AWS: "arn:aws:iam::000000000000:role/reader" }, Action: "dynamodb:GetItem", Resource: tableArn }]);
    const first = await client.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: firstDocument, ExpectedRevisionId: "NO_POLICY" })); assert.match(first.RevisionId ?? "", /^[0-9a-f]{32}$/);
    const loaded = await client.send(new GetResourcePolicyCommand({ ResourceArn: tableArn })); assert.equal(loaded.RevisionId, first.RevisionId); assert.equal(JSON.stringify(JSON.parse(loaded.Policy!)), loaded.Policy, "stored policy JSON should be normalized and compact");
    const repeated = await client.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: ` { "Statement": ${JSON.stringify(JSON.parse(firstDocument).Statement)}, "Version": "2012-10-17" } `, ExpectedRevisionId: first.RevisionId })); assert.equal(repeated.RevisionId, first.RevisionId, "equivalent normalized policy should be idempotent");
    const changedDocument = policy([{ Effect: "Allow", Principal: "*", Action: "dynamodb:GetItem", Resource: tableArn }]);
    await assert.rejects(client.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: changedDocument, ExpectedRevisionId: first.RevisionId })), (error: any) => error.name === "ResourceInUseException");
    clock.advance(15_000); await assert.rejects(client.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: changedDocument, ExpectedRevisionId: "wrong" })), (error: any) => error.name === "PolicyNotFoundException");
    const second = await client.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: changedDocument, ExpectedRevisionId: first.RevisionId })); assert.notEqual(second.RevisionId, first.RevisionId);
    clock.advance(15_000); const lockout = policy([{ Effect: "Deny", Principal: "*", Action: "dynamodb:PutResourcePolicy", Resource: tableArn }]);
    await assert.rejects(client.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: lockout, ExpectedRevisionId: second.RevisionId })), (error: any) => error.name === "ValidationException" && /ConfirmRemoveSelfResourceAccess/.test(error.message));
    const locked = await client.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: lockout, ExpectedRevisionId: second.RevisionId, ConfirmRemoveSelfResourceAccess: true }));
    clock.advance(15_000); await assert.rejects(client.send(new DeleteResourcePolicyCommand({ ResourceArn: tableArn, ExpectedRevisionId: "wrong" })), (error: any) => error.name === "PolicyNotFoundException");
    const deleted = await client.send(new DeleteResourcePolicyCommand({ ResourceArn: tableArn, ExpectedRevisionId: locked.RevisionId })); assert.equal(deleted.RevisionId, locked.RevisionId); await assert.rejects(client.send(new DeleteResourcePolicyCommand({ ResourceArn: tableArn, ExpectedRevisionId: "NO_POLICY" })), (error: any) => error.name === "PolicyNotFoundException"); assert.equal((await client.send(new DeleteResourcePolicyCommand({ ResourceArn: tableArn }))).RevisionId, "");

    const createArn = `arn:aws:dynamodb:${region}:000000000000:table/CreatePolicy`; const createDocument = policy([{ Effect: "Allow", Principal: "*", Action: "dynamodb:GetItem", Resource: createArn }]); await client.send(new CreateTableCommand(tableInput("CreatePolicy", createDocument))); assert.equal(JSON.parse((await client.send(new GetResourcePolicyCommand({ ResourceArn: createArn }))).Policy!).Statement[0].Resource, createArn, "CreateTable ResourcePolicy should be strongly visible");
    const streamTable = await client.send(new CreateTableCommand({ ...tableInput("StreamPolicy"), StreamSpecification: { StreamEnabled: true, StreamViewType: "KEYS_ONLY" } })); const streamArn = streamTable.TableDescription?.LatestStreamArn!; const streamDocument = policy([{ Effect: "Allow", Principal: "*", Action: "dynamodb:GetRecords", Resource: streamArn }]); clock.advance(15_000); const streamRevision = await client.send(new PutResourcePolicyCommand({ ResourceArn: streamArn, Policy: streamDocument, ExpectedRevisionId: "NO_POLICY" })); assert.equal((await client.send(new GetResourcePolicyCommand({ ResourceArn: streamArn }))).RevisionId, streamRevision.RevisionId);
    await client.send(new DeleteTableCommand({ TableName: "StreamPolicy" })); assert.equal((await client.send(new GetResourcePolicyCommand({ ResourceArn: streamArn }))).RevisionId, streamRevision.RevisionId, "a retained stream keeps its own policy after table deletion");

    client.destroy(); client = undefined; await simulator.stop(); const persisted = JSON.parse(await readFile(join(root, "state.json"), "utf8")); assert.equal(persisted.schemaVersion, CURRENT_SCHEMA_VERSION); assert.equal(persisted.accounts["000000000000"].regions[region].dynamodbResourcePolicies[streamArn].revisionId, streamRevision.RevisionId);
    persisted.schemaVersion = 9; delete persisted.accounts["000000000000"].regions[region].dynamodbResourcePolicies; delete persisted.accounts["000000000000"].regions[region].dynamodbResourcePolicyMutationTimes; await writeFile(join(root, "state.json"), JSON.stringify(persisted), { mode: 0o600 });
    simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, clock, authMode: "off"}); await simulator.start(); assert.equal(simulator.store.state.schemaVersion, CURRENT_SCHEMA_VERSION); assert.deepEqual(simulator.store.regionState(region).dynamodbResourcePolicies, {}); assert.deepEqual(simulator.store.regionState(region).dynamodbResourcePolicyMutationTimes, {});
  } finally { client?.destroy(); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("DynamoDB resource policies combine with identity policies for tables and indexes with explicit-deny precedence", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-ddb-policy-auth-")); const clock = new TestClock(Date.now()); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, clock, authMode: "enforce", cdkBootstrap: true, rootRecovery: true }); const clients: Array<{ destroy(): void }> = [];
  try {
    await simulator.start(); const endpoint = `http://127.0.0.1:${simulator.port}`; const rootDynamo = new DynamoDBClient({ endpoint, region, credentials: adminCredentials }); const iam = new IAMClient({ endpoint, region, credentials: adminCredentials }); const sts = new STSClient({ endpoint, region, credentials: adminCredentials }); clients.push(rootDynamo, iam, sts);
    const tableArn = `arn:aws:dynamodb:${region}:000000000000:table/SharedRecords`; const indexArn = `${tableArn}/index/ByCategory`; await rootDynamo.send(new CreateTableCommand({ TableName: "SharedRecords", BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "id", AttributeType: "S" }, { AttributeName: "category", AttributeType: "S" }], KeySchema: [{ AttributeName: "id", KeyType: "HASH" }], GlobalSecondaryIndexes: [{ IndexName: "ByCategory", KeySchema: [{ AttributeName: "category", KeyType: "HASH" }], Projection: { ProjectionType: "ALL" } }] })); await waitForTableActive(rootDynamo, "SharedRecords", clock); await rootDynamo.send(new PutItemCommand({ TableName: "SharedRecords", Item: { id: { S: "one" }, category: { S: "news" }, value: { S: "shared" } } }));
    const roleArn = "arn:aws:iam::000000000000:role/resource-reader"; await iam.send(new CreateRoleCommand({ RoleName: "resource-reader", AssumeRolePolicyDocument: policy([{ Effect: "Allow", Principal: { AWS: "arn:aws:iam::000000000000:root" }, Action: "sts:AssumeRole", Resource: "*" }]) })); const assumed = await sts.send(new AssumeRoleCommand({ RoleArn: roleArn, RoleSessionName: "shared" })); const credentials = { accessKeyId: assumed.Credentials!.AccessKeyId!, secretAccessKey: assumed.Credentials!.SecretAccessKey!, sessionToken: assumed.Credentials!.SessionToken! }; const reader = new DynamoDBClient({ endpoint, region, credentials }); clients.push(reader);
    const delegatedArn = `arn:aws:dynamodb:${region}:000000000000:table/DelegatedPolicy`; const createOnly = await iam.send(new CreatePolicyCommand({ PolicyName: "CreateDelegatedTable", PolicyDocument: policy([{ Effect: "Allow", Action: "dynamodb:CreateTable", Resource: delegatedArn }]) })); await iam.send(new AttachRolePolicyCommand({ RoleName: "resource-reader", PolicyArn: createOnly.Policy!.Arn! })); const delegatedPolicy = policy([{ Effect: "Allow", Principal: { AWS: roleArn }, Action: "dynamodb:GetItem", Resource: delegatedArn }]); await assert.rejects(reader.send(new CreateTableCommand(tableInput("DelegatedPolicy", delegatedPolicy))), (error: any) => error.name === "AccessDeniedException", "CreateTable with ResourcePolicy must also require dynamodb:PutResourcePolicy"); const putPolicy = await iam.send(new CreatePolicyCommand({ PolicyName: "PutDelegatedPolicy", PolicyDocument: policy([{ Effect: "Allow", Action: "dynamodb:PutResourcePolicy", Resource: delegatedArn }]) })); await iam.send(new AttachRolePolicyCommand({ RoleName: "resource-reader", PolicyArn: putPolicy.Policy!.Arn! })); await reader.send(new CreateTableCommand(tableInput("DelegatedPolicy", delegatedPolicy))); assert.deepEqual(JSON.parse((await rootDynamo.send(new GetResourcePolicyCommand({ ResourceArn: delegatedArn }))).Policy!), JSON.parse(delegatedPolicy));
    const allow = policy([{ Sid: "TableRead", Effect: "Allow", Principal: { AWS: roleArn }, Action: "dynamodb:GetItem", Resource: tableArn }, { Sid: "IndexQuery", Effect: "Allow", Principal: { AWS: roleArn }, Action: "dynamodb:Query", Resource: indexArn }, { Sid: "ResourcePut", Effect: "Allow", Principal: { AWS: roleArn }, Action: "dynamodb:PutItem", Resource: tableArn }]); const allowed = await rootDynamo.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: allow, ExpectedRevisionId: "NO_POLICY" }));
    assert.equal((await reader.send(new GetItemCommand({ TableName: "SharedRecords", Key: { id: { S: "one" } } }))).Item?.value?.S, "shared", "same-account resource allow should authorize without an identity allow"); assert.equal((await reader.send(new QueryCommand({ TableName: "SharedRecords", IndexName: "ByCategory", KeyConditionExpression: "category = :category", ExpressionAttributeValues: { ":category": { S: "news" } } }))).Count, 1, "index ARN policy should authorize an index request");
    const identity = await iam.send(new CreatePolicyCommand({ PolicyName: "SharedIdentity", PolicyDocument: policy([{ Effect: "Allow", Action: ["dynamodb:GetItem", "dynamodb:Query", "dynamodb:PutItem"], Resource: [tableArn, indexArn] }, { Effect: "Deny", Action: "dynamodb:PutItem", Resource: tableArn }]) })); await iam.send(new AttachRolePolicyCommand({ RoleName: "resource-reader", PolicyArn: identity.Policy!.Arn! })); await assert.rejects(reader.send(new PutItemCommand({ TableName: "SharedRecords", Item: { id: { S: "two" }, category: { S: "news" } } })), (error: any) => error.name === "AccessDeniedException", "identity explicit deny must override a resource allow");
    clock.advance(15_000); const deny = policy([{ Effect: "Allow", Principal: { AWS: roleArn }, Action: ["dynamodb:GetItem", "dynamodb:Query"], Resource: [tableArn, indexArn] }, { Sid: "NoRead", Effect: "Deny", Principal: { AWS: roleArn }, Action: "dynamodb:GetItem", Resource: tableArn }]); const denied = await rootDynamo.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: deny, ExpectedRevisionId: allowed.RevisionId })); await assert.rejects(reader.send(new GetItemCommand({ TableName: "SharedRecords", Key: { id: { S: "one" } } })), (error: any) => error.name === "AccessDeniedException", "resource explicit deny must override an identity allow");
    clock.advance(15_000); const locked = policy([{ Effect: "Deny", Principal: "*", Action: "dynamodb:*", Resource: [tableArn, indexArn] }]); await rootDynamo.send(new PutResourcePolicyCommand({ ResourceArn: tableArn, Policy: locked, ExpectedRevisionId: denied.RevisionId, ConfirmRemoveSelfResourceAccess: true })); await assert.rejects(rootDynamo.send(new DescribeTableCommand({ TableName: "SharedRecords" })), (error: any) => error.name === "AccessDeniedException"); clock.advance(15_000); await rootDynamo.send(new DeleteResourcePolicyCommand({ ResourceArn: tableArn })); assert.equal((await rootDynamo.send(new DescribeTableCommand({ TableName: "SharedRecords" }))).Table?.TableName, "SharedRecords", "bootstrap root must be able to delete a locking policy");
    assert.ok(simulator.store.ensureAccount().iam.authorizationDecisions.some(decision => decision.action === "dynamodb:GetItem" && decision.decision === "explicitDeny"));
  } finally { for (const client of clients) client.destroy(); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});
