import { signedFetch } from "./helpers/signed-fetch.js";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { AddUserToGroupCommand, AttachGroupPolicyCommand, AttachUserPolicyCommand, CreateAccessKeyCommand, CreateGroupCommand, CreatePolicyCommand, CreatePolicyVersionCommand, CreateRoleCommand, CreateUserCommand, IAMClient, PutGroupPolicyCommand, PutRolePolicyCommand, PutUserPolicyCommand, UpdateAssumeRolePolicyCommand } from "@aws-sdk/client-iam";
import { DynamoDBClient, ListTablesCommand, CreateTableCommand, DescribeTableCommand, PutResourcePolicyCommand, GetItemCommand } from "@aws-sdk/client-dynamodb";
import { STSClient, AssumeRoleCommand } from "@aws-sdk/client-sts";
import { evaluateAuthorization, evaluateRoleAuthorization, evaluateResourcePolicy, evaluateTrust, combineIdentityAndResourceAuthorization } from "../src/iam/evaluator.js";
import { createIamState, normalizeIamState } from "../src/iam/model.js";
import { boundProvenance, decisionProvenance, authorizationDecision, policyRevision, resourcePolicySource, trustPolicySource } from "../src/iam/provenance.js";
import type { PolicyDocument } from "../src/types.js";
import { StackSim } from "../src/server.js";

const action = "dynamodb:ListTables";
const policy = (effect: "Allow" | "Deny" = "Allow", selected = action): PolicyDocument => ({ Version: "2012-10-17", Statement: [{ Sid: "DuplicateSid", Effect: effect, Action: selected, Resource: "*" }] });

test("policy provenance distinguishes role, boundary, session, resource and trust layers without altering their combination", () => {
  const iam = createIamState(); const role = iam.roles.test; role.attachedPolicyArns = []; role.inlinePolicies = { reader: policy() };
  const boundaryArn = "arn:aws:iam::000000000000:policy/learning/boundary";
  iam.policies[boundaryArn] = { ...iam.policies["arn:aws:iam::aws:policy/AdministratorAccess"], arn: boundaryArn, defaultVersionId: "v2", versions: { v2: { versionId: "v2", document: policy("Allow", "s3:GetObject"), isDefaultVersion: true, createDate: 0 } } };
  role.permissionsBoundaryArn = boundaryArn;
  const restricted = evaluateRoleAuthorization(iam, role.arn, action, "*");
  assert.equal(restricted.decision, "implicitDeny"); assert.match(restricted.reason, /Permissions boundary/);
  assert.deepEqual(restricted.provenance!.map(entry => [entry.layer, entry.matched, entry.source.versionId]), [["boundary", false, "v2"], ["identity", true, undefined]]);
  role.attachedPolicyArns = [boundaryArn];
  const managedRole = evaluateRoleAuthorization(iam, role.arn, "s3:GetObject", "*");
  assert.equal(managedRole.provenance!.find(entry => entry.layer === "identity" && entry.source.kind === "managed")!.source.versionId, "v2");
  role.attachedPolicyArns = [];
  iam.policies[boundaryArn].versions.v2.document = policy("Deny");
  assert.equal(evaluateRoleAuthorization(iam, role.arn, action, "*").decision, "explicitDeny");
  iam.policies[boundaryArn].versions.v2.document = policy("Allow", "s3:GetObject");
  const principalArn = "arn:aws:sts::000000000000:assumed-role/test/learner";
  iam.sessions.test = { accessKeyId: "test", principalArn, principalId: "id", roleArn: role.arn, roleName: "test", sessionName: "learner", expiration: Date.now() + 1000, sessionTags: {}, sessionPolicies: [policy(), policy("Allow", "s3:GetObject")] };
  const principal: any = { principalType: "assumedRole", principalArn, roleArn: role.arn, accessKeyId: "test", accountId: "000000000000" };
  const limited = evaluateAuthorization(iam, principal, action, "*", {});
  assert.equal(limited.decision, "implicitDeny"); assert.equal(limited.provenance!.filter(entry => entry.layer === "session").length, 2);
  const document: PolicyDocument = { Statement: [{ Effect: "Allow", Sid: "DuplicateSid", Principal: { AWS: principalArn }, Action: action, Resource: "*" }] };
  const resource = evaluateResourcePolicy(document, principal, action, "*", {}, resourcePolicySource("dynamodb", "arn:aws:dynamodb:eu-west-1:000000000000:table/example", document, "revision-17"));
  const combined = combineIdentityAndResourceAuthorization(limited, resource, "sameAccount");
  assert.equal(combined.decision, "allowed", "direct session grants retain existing bypass semantics for implicit restrictions");
  assert.equal(combined.provenance!.find(entry => entry.layer === "resource")!.source.revision, "revision-17");
  role.inlinePolicies.deny = policy("Deny");
  assert.equal(combineIdentityAndResourceAuthorization(evaluateAuthorization(iam, principal, action, "*", {}), resource, "sameAccount").decision, "explicitDeny");
  const trust = evaluateTrust(role.assumeRolePolicyDocument, "lambda.amazonaws.com", "sts:AssumeRole", {}, trustPolicySource(role));
  assert.equal(trust.decision, "allowed"); assert.equal(trust.provenance![0].layer, "trust"); assert.equal(trust.provenance![0].source.entityArn, role.arn);
  assert.equal(trust.provenance![0].source.revision, policyRevision(role.assumeRolePolicyDocument));
  const reversed: PolicyDocument = { Statement: [{ Effect: "Allow", Action: "s3:GetObject", Resource: "*" }, { Effect: "Deny", Action: "s3:PutObject", Resource: "*" }] };
  assert.notEqual(policyRevision(reversed), policyRevision({ Statement: [...reversed.Statement as any[]].reverse() }), "revision preserves statement indexes");
});

test("provenance bounds are deterministic, byte-aware, redacted and honest for historical history", () => {
  const iam = createIamState(); const role = iam.roles.test; role.attachedPolicyArns = [];
  role.inlinePolicies = Object.fromEntries(Array.from({ length: 45 }, (_, n) => [`policy-${String(n).padStart(2, "0")}`, { Statement: [{ Effect: "Allow", Action: action, Resource: "*", Condition: { StringEquals: { "aws:PrincipalTag/secret": "secret-context-value" } } }] }]));
  const result = evaluateRoleAuthorization(iam, role.arn, action, "*", { "aws:PrincipalTag/secret": "secret-context-value" });
  assert.equal(result.provenance!.length, 32); assert.equal(result.provenanceTotalCount, 45); assert.equal(result.provenanceMatchedCount, 45); assert.equal(result.provenanceTruncated, true);
  assert.doesNotMatch(JSON.stringify(decisionProvenance(result)), /secret-context-value|Condition|Statement/);
  role.inlinePolicies = Object.fromEntries(Object.entries(role.inlinePolicies).reverse());
  assert.deepEqual(evaluateRoleAuthorization(iam, role.arn, action, "*", { "aws:PrincipalTag/secret": "secret-context-value" }).provenance, result.provenance);
  const large = boundProvenance(Array.from({ length: 20 }, (_, n) => ({ ...result.provenance![0], source: { ...result.provenance![0].source, policyName: `${n}`.padStart(2, "0") + "x".repeat(2000) } })));
  assert.ok(large.provenance!.length < 20); assert.ok(Buffer.byteLength(JSON.stringify(large)) <= 16384); assert.equal(large.provenanceTruncated, true); assert.equal(large.provenanceTotalCount, 20);
  const old = { time: 1, requestId: "old", principalArn: role.arn, action, resource: "*", decision: "allowed", reason: "old generic reason" };
  const boundedDecision = authorizationDecision({ ...old, decision: "allowed", resource: "x".repeat(5000) }, large);
  assert.ok(Buffer.byteLength(JSON.stringify(boundedDecision)) <= 16384); assert.equal(boundedDecision.provenanceTruncated, true);
  const oversizedTarget = authorizationDecision({ ...old, decision: "allowed", resource: "🔒".repeat(10000) }, large);
  assert.ok(Buffer.byteLength(JSON.stringify(oversizedTarget)) <= 16384);
  assert.deepEqual(oversizedTarget.diagnosticFieldsTruncated, ["resource"]);
  const normalized = normalizeIamState({ ...iam, authorizationDecisions: Array.from({ length: 1002 }, () => old) });
  assert.equal(normalized.authorizationDecisions.length, 1000); assert.equal(normalized.authorizationDecisions[0].provenanceUnavailable, true); assert.equal(normalized.authorizationDecisions[0].provenance, undefined);
});

test("IAM SDK sources survive collection, session policy flattening, private diagnostics, retention and restart", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-iam-provenance-")); let sim = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1" });
  const clients: Array<{ destroy(): void }> = [];
  try {
    await sim.start(); const config = { endpoint: `http://127.0.0.1:${sim.port}`, region: "eu-west-1", credentials: { accessKeyId: "admin", secretAccessKey: "password" }, maxAttempts: 1 };
    const iam = new IAMClient(config); clients.push(iam);
    const user = await iam.send(new CreateUserCommand({ UserName: "learner", Path: "/training/" }));
    await iam.send(new CreateGroupCommand({ GroupName: "class", Path: "/training/" })); await iam.send(new AddUserToGroupCommand({ GroupName: "class", UserName: "learner" }));
    await iam.send(new PutUserPolicyCommand({ UserName: "learner", PolicyName: "user-inline", PolicyDocument: JSON.stringify(policy()) }));
    await iam.send(new PutGroupPolicyCommand({ GroupName: "class", PolicyName: "group-inline", PolicyDocument: JSON.stringify(policy()) }));
    const managed = (await iam.send(new CreatePolicyCommand({ PolicyName: "shared", Path: "/training/", PolicyDocument: JSON.stringify(policy()) }))).Policy!;
    await iam.send(new CreatePolicyVersionCommand({ PolicyArn: managed.Arn, PolicyDocument: JSON.stringify(policy()), SetAsDefault: true }));
    await iam.send(new AttachUserPolicyCommand({ UserName: "learner", PolicyArn: managed.Arn })); await iam.send(new AttachGroupPolicyCommand({ GroupName: "class", PolicyArn: managed.Arn }));
    const key = (await iam.send(new CreateAccessKeyCommand({ UserName: "learner" }))).AccessKey!;
    const db = new DynamoDBClient({ ...config, credentials: { accessKeyId: key.AccessKeyId!, secretAccessKey: key.SecretAccessKey! } }); clients.push(db);
    await db.send(new ListTablesCommand({}));
    let decision = sim.store.ensureAccount().iam.authorizationDecisions.at(-1)!;
    assert.equal(decision.principalArn, user.User!.Arn); assert.equal(decision.provenanceMatchedCount, 4);
    assert.deepEqual(decision.provenance!.filter(entry => entry.source.kind === "managed").map(entry => entry.source.versionId), ["v2", "v2"]);
    assert.deepEqual(new Set(decision.provenance!.map(entry => entry.source.entityType)), new Set(["user", "group"]));
    const firstRevision = decision.provenance!.find(entry => entry.source.policyName === "group-inline")!.source.revision;
    await iam.send(new PutGroupPolicyCommand({ GroupName: "class", PolicyName: "group-inline", PolicyDocument: JSON.stringify(policy("Deny")) }));
    await assert.rejects(db.send(new ListTablesCommand({})), /not authorized/);
    decision = sim.store.ensureAccount().iam.authorizationDecisions.at(-1)!; assert.equal(decision.decision, "explicitDeny"); assert.equal(decision.provenance!.filter(entry => entry.effect === "Deny")[0].source.policyName, "group-inline");
    assert.notEqual(decision.provenance!.find(entry => entry.source.policyName === "group-inline")!.source.revision, firstRevision);
    const adminDb = new DynamoDBClient(config); clients.push(adminDb);
    const table = (await adminDb.send(new CreateTableCommand({ TableName: "policy-observation", BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "pk", AttributeType: "S" }], KeySchema: [{ AttributeName: "pk", KeyType: "HASH" }] }))).TableDescription!;
    for (let i = 0; i < 100; i++) { if ((await adminDb.send(new DescribeTableCommand({ TableName: "policy-observation" }))).Table?.TableStatus === "ACTIVE") break; await new Promise(resolve => setTimeout(resolve, 10)); }
    const attached = await adminDb.send(new PutResourcePolicyCommand({ ResourceArn: table.TableArn, Policy: JSON.stringify({ Statement: [{ Effect: "Allow", Sid: "DuplicateSid", Action: "dynamodb:GetItem", Resource: table.TableArn, Principal: { AWS: user.User!.Arn } }] }) }));
    await db.send(new GetItemCommand({ TableName: "policy-observation", Key: { pk: { S: "missing" } } }));
    const resourceDecision = sim.store.ensureAccount().iam.authorizationDecisions.at(-1)!;
    assert.equal(resourceDecision.decision, "allowed");
    const resourceSource = resourceDecision.provenance!.find(entry => entry.layer === "resource")!;
    assert.equal(resourceSource.source.revision, attached.RevisionId); assert.equal(resourceSource.source.resourceArn, table.TableArn); assert.equal(resourceSource.statementIndex, 0); assert.equal(resourceSource.source.service, "dynamodb");
    const role = (await iam.send(new CreateRoleCommand({ RoleName: "session-learner", Path: "/training/", AssumeRolePolicyDocument: JSON.stringify({ Statement: [{ Effect: "Allow", Principal: { AWS: "arn:aws:iam::000000000000:root" }, Action: "sts:AssumeRole" }] }) }))).Role!;
    await iam.send(new PutRolePolicyCommand({ RoleName: "session-learner", PolicyName: "role-inline", PolicyDocument: JSON.stringify(policy()) }));
    const sts = new STSClient(config); clients.push(sts);
    const session = (await sts.send(new AssumeRoleCommand({ RoleArn: role.Arn, RoleSessionName: "class-session", Policy: JSON.stringify(policy("Allow", "s3:GetObject")), PolicyArns: [{ arn: managed.Arn }] }))).Credentials!;
    const trustDecision = sim.store.ensureAccount().iam.authorizationDecisions.at(-1)!;
    assert.equal(trustDecision.action, "sts:AssumeRole"); assert.equal(trustDecision.provenance!.find(entry => entry.layer === "trust")!.source.entityArn, role.Arn);
    await iam.send(new UpdateAssumeRolePolicyCommand({ RoleName: "session-learner", PolicyDocument: JSON.stringify({ Statement: [{ Effect: "Deny", Principal: { AWS: "arn:aws:iam::000000000000:root" }, Action: "sts:AssumeRole" }] }) }));
    await assert.rejects(sts.send(new AssumeRoleCommand({ RoleArn: role.Arn, RoleSessionName: "denied-session" })), /Trust policy explicitly denies/);
    const trustDeny = sim.store.ensureAccount().iam.authorizationDecisions.at(-1)!; assert.equal(trustDeny.decision, "explicitDeny"); assert.equal(trustDeny.provenance!.find(entry => entry.layer === "trust")!.effect, "Deny");
    const sessionDb = new DynamoDBClient({ ...config, credentials: { accessKeyId: session.AccessKeyId!, secretAccessKey: session.SecretAccessKey!, sessionToken: session.SessionToken! } }); clients.push(sessionDb);
    await sessionDb.send(new ListTablesCommand({})); decision = sim.store.ensureAccount().iam.authorizationDecisions.at(-1)!;
    assert.equal(decision.decision, "allowed", "merged STS policies remain a union within the session restriction");
    const sources = decision.provenance!.filter(entry => entry.layer === "session"); assert.equal(sources.length, 2); assert.equal(sources.find(entry => entry.matched)!.source.policyArn, managed.Arn); assert.equal(sources.find(entry => entry.matched)!.source.versionId, "v2");
    assert.equal(sources.find(entry => !entry.matched)!.statementIndex, 0);
    const route = await signedFetch(`${config.endpoint}/_stacksim/api/iam/decisions`, { service: "iam", region: config.region, credentials: config.credentials }); assert.equal(route.status, 200); const history: any = await route.json(); assert.deepEqual(history.decisions[0].provenance, decision.provenance);
    const saved = structuredClone(decision);
    sim.store.ensureAccount().iam.authorizationDecisions = [saved, ...Array.from({ length: 1000 }, (_, i) => ({ time: i, requestId: `old-${i}`, principalArn: "old", action, resource: "*", decision: "allowed" as const, reason: "historical" }))];
    await sessionDb.send(new ListTablesCommand({})); assert.equal(sim.store.ensureAccount().iam.authorizationDecisions.length, 1000);
    for (const client of clients) client.destroy(); await sim.stop();
    sim = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1" }); await sim.start();
    const restored = sim.store.ensureAccount().iam.authorizationDecisions; assert.equal(restored[0].provenanceUnavailable, true); assert.deepEqual(restored.at(-1)!.provenance, saved.provenance);
    const serialized = JSON.stringify(restored); for (const secret of [key.AccessKeyId!, key.SecretAccessKey!, session.AccessKeyId!, session.SecretAccessKey!, session.SessionToken!]) assert.equal(serialized.includes(secret), false);
  } finally { for (const client of clients) client.destroy(); await sim.stop(); await rm(root, { recursive: true, force: true }); }
});
