import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { CreateRoleCommand, IAMClient, PutRolePolicyCommand } from "@aws-sdk/client-iam";
import { CreateTableCommand, DynamoDBClient, PutItemCommand } from "@aws-sdk/client-dynamodb";
import { DescribeLogStreamsCommand, CloudWatchLogsClient } from "@aws-sdk/client-cloudwatch-logs";
import { AddPermissionCommand, CreateAliasCommand, CreateFunctionCommand, DeleteAliasCommand, DeleteFunctionCommand, GetAliasCommand, GetFunctionCommand, GetPolicyCommand, InvokeCommand, LambdaClient, ListAliasesCommand, ListTagsCommand, ListVersionsByFunctionCommand, PublishVersionCommand, RemovePermissionCommand, TagResourceCommand, UntagResourceCommand, UpdateAliasCommand, UpdateFunctionCodeCommand, UpdateFunctionConfigurationCommand } from "@aws-sdk/client-lambda";
import { AssumeRoleCommand, STSClient } from "@aws-sdk/client-sts";
import { StackSim } from "../src/server.js";
import { waitForTableActive } from "./support/dynamodb.js";

const credentials = { accessKeyId: "admin", secretAccessKey: "password" };
const payload = (result: any) => JSON.parse(Buffer.from(result.Payload ?? []).toString("utf8"));
function crc32(data: Buffer): number { let crc = 0xffffffff; for (const byte of data) { crc ^= byte; for (let bit = 0; bit < 8; bit++) crc = crc >>> 1 ^ (crc & 1 ? 0xedb88320 : 0); } return (crc ^ 0xffffffff) >>> 0; }
function zipSingle(name: string, source: string): Buffer {
  const filename = Buffer.from(name); const content = Buffer.from(source); const checksum = crc32(content); const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50, 0); local.writeUInt16LE(20, 4); local.writeUInt32LE(checksum, 14); local.writeUInt32LE(content.length, 18); local.writeUInt32LE(content.length, 22); local.writeUInt16LE(filename.length, 26);
  const central = Buffer.alloc(46); central.writeUInt32LE(0x02014b50, 0); central.writeUInt16LE(20, 4); central.writeUInt16LE(20, 6); central.writeUInt32LE(checksum, 16); central.writeUInt32LE(content.length, 20); central.writeUInt32LE(content.length, 24); central.writeUInt16LE(filename.length, 28);
  const directoryOffset = local.length + filename.length + content.length; const directorySize = central.length + filename.length; const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(1, 8); end.writeUInt16LE(1, 10); end.writeUInt32LE(directorySize, 12); end.writeUInt32LE(directoryOffset, 16); return Buffer.concat([local, filename, content, central, filename, end]);
}

test("Lambda versions, aliases, weighted routing, qualified policies, tags, deletion conflicts, and restart persistence", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-lambda-versions-")); const draws = [0.1, 0.9]; let draw = 0; let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, random: () => draws[draw++ % draws.length], authMode: "off"}); let lambda: LambdaClient | undefined;
  try {
    await simulator.start(); lambda = new LambdaClient({ endpoint: `http://127.0.0.1:${simulator.port}`, region: "eu-west-1", credentials }); const zip = await readFile(join(process.cwd(), "examples/lambda/function.zip"));
    const created = await lambda.send(new CreateFunctionCommand({ FunctionName: "versioned", Runtime: "nodejs22.x", Role: "arn:aws:iam::000000000000:role/test", Handler: "handler.versionHandler", Code: { ZipFile: zip }, Environment: { Variables: { VERSION_MARKER: "one" } }, Tags: { team: "platform" } }));
    await lambda.send(new TagResourceCommand({ Resource: created.FunctionArn!, Tags: { environment: "test" } })); await lambda.send(new UntagResourceCommand({ Resource: created.FunctionArn!, TagKeys: ["team"] })); assert.deepEqual((await lambda.send(new ListTagsCommand({ Resource: created.FunctionArn! }))).Tags, { environment: "test" }); assert.deepEqual((await lambda.send(new GetFunctionCommand({ FunctionName: "versioned" }))).Tags, { environment: "test" }); const bulkTags = Object.fromEntries(Array.from({ length: 49 }, (_, index) => [`key${index}`, String(index)])); await lambda.send(new TagResourceCommand({ Resource: created.FunctionArn!, Tags: bulkTags })); await assert.rejects(lambda.send(new TagResourceCommand({ Resource: created.FunctionArn!, Tags: { overflow: "no" } })), (error: any) => error.name === "InvalidParameterValueException");
    const v1 = await lambda.send(new PublishVersionCommand({ FunctionName: "versioned", CodeSha256: created.CodeSha256, RevisionId: created.RevisionId, Description: "first" })); assert.equal(v1.Version, "1"); await assert.rejects(lambda.send(new PublishVersionCommand({ FunctionName: "versioned:1" })), (error: any) => error.name === "InvalidParameterValueException"); await assert.rejects(lambda.send(new PublishVersionCommand({ FunctionName: "versioned", CodeSha256: "incorrect" })), (error: any) => error.name === "PreconditionFailedException"); await assert.rejects(lambda.send(new PublishVersionCommand({ FunctionName: "versioned", RevisionId: "incorrect" })), (error: any) => error.name === "PreconditionFailedException"); const replacementZip = zipSingle("index.mjs", 'export async function handler(_event, context) { return { marker: process.env.VERSION_MARKER, code: "replacement", version: context.functionVersion }; }'); const updatedCode = await lambda.send(new UpdateFunctionCodeCommand({ FunctionName: "versioned", ZipFile: replacementZip })); const updatedConfiguration = await lambda.send(new UpdateFunctionConfigurationCommand({ FunctionName: "versioned", Handler: "index.handler", Environment: { Variables: { VERSION_MARKER: "two" } } })); await assert.rejects(lambda.send(new UpdateFunctionConfigurationCommand({ FunctionName: "versioned:1", Description: "must-not-change" })), (error: any) => error.name === "InvalidParameterValueException"); const v2 = await lambda.send(new PublishVersionCommand({ FunctionName: "versioned", CodeSha256: updatedCode.CodeSha256, RevisionId: updatedConfiguration.RevisionId, Description: "second" })); assert.equal(v2.Version, "2");
    assert.equal((await lambda.send(new GetFunctionCommand({ FunctionName: "versioned", Qualifier: "1" }))).Configuration?.Environment?.Variables?.VERSION_MARKER, "one"); const immutableCode = await lambda.send(new InvokeCommand({ FunctionName: "versioned:1", Payload: Buffer.from("{}") })); assert.equal(payload(immutableCode).marker, "one"); assert.equal(payload(immutableCode).code, undefined); const replacementCode = await lambda.send(new InvokeCommand({ FunctionName: "versioned:2", Payload: Buffer.from("{}") })); assert.equal(payload(replacementCode).marker, "two"); assert.equal(payload(replacementCode).code, "replacement"); assert.equal((await lambda.send(new ListVersionsByFunctionCommand({ FunctionName: "versioned" }))).Versions?.length, 3); const versionPage1 = await lambda.send(new ListVersionsByFunctionCommand({ FunctionName: "versioned", MaxItems: 1 })); assert.deepEqual(versionPage1.Versions?.map(version => version.Version), ["$LATEST"]); const versionPage2 = await lambda.send(new ListVersionsByFunctionCommand({ FunctionName: "versioned", MaxItems: 1, Marker: versionPage1.NextMarker })); assert.deepEqual(versionPage2.Versions?.map(version => version.Version), ["1"]);
    await assert.rejects(lambda.send(new CreateAliasCommand({ FunctionName: "versioned", Name: "latest", FunctionVersion: "$LATEST" })), (error: any) => error.name === "InvalidParameterValueException"); await assert.rejects(lambda.send(new CreateAliasCommand({ FunctionName: "versioned", Name: "invalid-weights", FunctionVersion: "2", RoutingConfig: { AdditionalVersionWeights: { "1": 1.1 } } })), (error: any) => error.name === "InvalidParameterValueException"); await lambda.send(new CreateAliasCommand({ FunctionName: "versioned", Name: "live", FunctionVersion: "2", RoutingConfig: { AdditionalVersionWeights: { "1": 0.25 } } })); assert.equal((await lambda.send(new ListAliasesCommand({ FunctionName: "versioned" }))).Aliases?.[0].Name, "live"); await assert.rejects(lambda.send(new CreateAliasCommand({ FunctionName: "versioned", Name: "live", FunctionVersion: "2" })), (error: any) => error.name === "ResourceConflictException"); const liveAlias = await lambda.send(new GetAliasCommand({ FunctionName: "versioned", Name: "live" })); await assert.rejects(lambda.send(new UpdateAliasCommand({ FunctionName: "versioned", Name: "live", FunctionVersion: "2", RevisionId: "incorrect" })), (error: any) => error.name === "PreconditionFailedException"); assert.ok(liveAlias.RevisionId);
    await lambda.send(new CreateAliasCommand({ FunctionName: "versioned", Name: "temporary", FunctionVersion: "1" })); assert.equal((await lambda.send(new GetAliasCommand({ FunctionName: "versioned", Name: "temporary" }))).FunctionVersion, "1"); const aliasPage1 = await lambda.send(new ListAliasesCommand({ FunctionName: "versioned", MaxItems: 1 })); assert.equal(aliasPage1.Aliases?.length, 1); assert.ok(aliasPage1.NextMarker); const aliasPage2 = await lambda.send(new ListAliasesCommand({ FunctionName: "versioned", MaxItems: 1, Marker: aliasPage1.NextMarker })); assert.equal(aliasPage2.Aliases?.length, 1); assert.equal((await lambda.send(new ListAliasesCommand({ FunctionName: "versioned", FunctionVersion: "1" }))).Aliases?.length, 1); await lambda.send(new DeleteAliasCommand({ FunctionName: "versioned", Name: "temporary" })); await assert.rejects(lambda.send(new GetAliasCommand({ FunctionName: "versioned", Name: "temporary" })), (error: any) => error.name === "ResourceNotFoundException");
    const weighted = await lambda.send(new InvokeCommand({ FunctionName: "versioned", Qualifier: "live", Payload: Buffer.from("{}") })); assert.equal(weighted.ExecutedVersion, "1"); assert.equal(payload(weighted).marker, "one"); const primary = await lambda.send(new InvokeCommand({ FunctionName: "versioned:live", Payload: Buffer.from("{}") })); assert.equal(primary.ExecutedVersion, "2"); assert.equal(payload(primary).marker, "two"); assert.equal(payload(primary).code, "replacement");
    await lambda.send(new AddPermissionCommand({ FunctionName: "versioned", Qualifier: "live", StatementId: "gateway", Action: "lambda:InvokeFunction", Principal: "apigateway.amazonaws.com", SourceArn: "arn:aws:execute-api:eu-west-1:000000000000:api/*/*/*", SourceAccount: "000000000000", PrincipalOrgID: "o-example" })); const policyResult = await lambda.send(new GetPolicyCommand({ FunctionName: "versioned", Qualifier: "live" })); const policy = JSON.parse(policyResult.Policy!); assert.equal(policy.Statement[0].Resource, `${created.FunctionArn}:live`); assert.equal(policy.Statement[0].Condition.ArnLike["AWS:SourceArn"], "arn:aws:execute-api:eu-west-1:000000000000:api/*/*/*"); assert.equal(policy.Statement[0].Condition.StringEquals["AWS:SourceAccount"], "000000000000"); assert.equal(policy.Statement[0].Condition.StringEquals["aws:PrincipalOrgID"], "o-example"); await assert.rejects(lambda.send(new AddPermissionCommand({ FunctionName: "versioned", Qualifier: "live", StatementId: "wrong-revision", Action: "lambda:InvokeFunction", Principal: "apigateway.amazonaws.com", RevisionId: "incorrect" })), (error: any) => error.name === "PreconditionFailedException"); await assert.rejects(lambda.send(new AddPermissionCommand({ FunctionName: "versioned", Qualifier: "live", StatementId: "gateway", Action: "lambda:InvokeFunction", Principal: "apigateway.amazonaws.com" })), (error: any) => error.name === "ResourceConflictException"); await assert.rejects(lambda.send(new RemovePermissionCommand({ FunctionName: "versioned", Qualifier: "live", StatementId: "gateway", RevisionId: "incorrect" })), (error: any) => error.name === "PreconditionFailedException"); await lambda.send(new RemovePermissionCommand({ FunctionName: "versioned", Qualifier: "live", StatementId: "gateway", RevisionId: policyResult.RevisionId }));
    await assert.rejects(lambda.send(new DeleteFunctionCommand({ FunctionName: "versioned", Qualifier: "1" })), (error: any) => error.name === "ResourceConflictException"); await lambda.send(new UpdateAliasCommand({ FunctionName: "versioned", Name: "live", FunctionVersion: "2", RoutingConfig: { AdditionalVersionWeights: {} } }));
    lambda.destroy(); await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, random: () => 0.9, authMode: "off"}); await simulator.start(); lambda = new LambdaClient({ endpoint: `http://127.0.0.1:${simulator.port}`, region: "eu-west-1", credentials }); const restarted = await lambda.send(new InvokeCommand({ FunctionName: "versioned", Qualifier: "live", Payload: Buffer.from("{}") })); assert.equal(restarted.ExecutedVersion, "2"); assert.equal(payload(restarted).marker, "two"); assert.equal(payload(restarted).code, "replacement"); await lambda.send(new DeleteFunctionCommand({ FunctionName: "versioned" })); await assert.rejects(lambda.send(new ListVersionsByFunctionCommand({ FunctionName: "versioned" })), (error: any) => error.name === "ResourceNotFoundException"); await assert.rejects(lambda.send(new ListAliasesCommand({ FunctionName: "versioned" })), (error: any) => error.name === "ResourceNotFoundException");
  } finally { lambda?.destroy(); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("Lambda validates execution-role trust and gives runtime SDKs role credentials with explicit-deny enforcement", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-lambda-role-")); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, authMode: "enforce", cdkBootstrap: true }); const clients: Array<{ destroy(): void }> = [];
  try {
    await simulator.start(); const endpoint = `http://127.0.0.1:${simulator.port}`; const iam = new IAMClient({ endpoint, region: "eu-west-1", credentials }); const dynamodb = new DynamoDBClient({ endpoint, region: "eu-west-1", credentials }); const lambda = new LambdaClient({ endpoint, region: "eu-west-1", credentials }); const sts = new STSClient({ endpoint, region: "eu-west-1", credentials }); const logs = new CloudWatchLogsClient({ endpoint, region: "eu-west-1", credentials }); clients.push(iam, dynamodb, lambda, sts, logs); const zip = await readFile(join(process.cwd(), "examples/lambda/function.zip"));
    await dynamodb.send(new CreateTableCommand({ TableName: "RuntimeData", BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "id", AttributeType: "S" }], KeySchema: [{ AttributeName: "id", KeyType: "HASH" }] })); await waitForTableActive(dynamodb, "RuntimeData"); await dynamodb.send(new PutItemCommand({ TableName: "RuntimeData", Item: { id: { S: "allowed" } } }));
    const lambdaTrust = JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "lambda.amazonaws.com" }, Action: "sts:AssumeRole" }] }); const role = await iam.send(new CreateRoleCommand({ RoleName: "lambda-runtime", AssumeRolePolicyDocument: lambdaTrust })); const secondRole = await iam.send(new CreateRoleCommand({ RoleName: "lambda-runtime-two", AssumeRolePolicyDocument: lambdaTrust })); await iam.send(new PutRolePolicyCommand({ RoleName: "lambda-runtime", PolicyName: "runtime", PolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Action: "dynamodb:GetItem", Resource: "arn:aws:dynamodb:eu-west-1:000000000000:table/RuntimeData" }, { Effect: "Deny", Action: "dynamodb:PutItem", Resource: "*" }] }) }));
    await iam.send(new CreateRoleCommand({ RoleName: "wrong-trust", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { AWS: "arn:aws:iam::000000000000:root" }, Action: "sts:AssumeRole" }] }) })); await assert.rejects(lambda.send(new CreateFunctionCommand({ FunctionName: "wrong", Runtime: "nodejs22.x", Role: "arn:aws:iam::000000000000:role/wrong-trust", Handler: "handler.handler", Code: { ZipFile: zip } })), (error: any) => error.name === "InvalidParameterValueException");
    const caller = await iam.send(new CreateRoleCommand({ RoleName: "lambda-deployer", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { AWS: "arn:aws:iam::000000000000:root" }, Action: "sts:AssumeRole" }] }) })); const deployPolicy = (passRoleResources: string[]) => JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Action: ["lambda:CreateFunction", "lambda:UpdateFunctionConfiguration"], Resource: "*" }, ...(passRoleResources.length ? [{ Effect: "Allow", Action: "iam:PassRole", Resource: passRoleResources, Condition: { StringEquals: { "iam:PassedToService": "lambda.amazonaws.com" } } }] : [])] }); await iam.send(new PutRolePolicyCommand({ RoleName: "lambda-deployer", PolicyName: "deploy", PolicyDocument: deployPolicy([]) })); const assumed = await sts.send(new AssumeRoleCommand({ RoleArn: caller.Role!.Arn!, RoleSessionName: "deployer" })); const deployer = new LambdaClient({ endpoint, region: "eu-west-1", credentials: { accessKeyId: assumed.Credentials!.AccessKeyId!, secretAccessKey: assumed.Credentials!.SecretAccessKey!, sessionToken: assumed.Credentials!.SessionToken! } }); clients.push(deployer); const passRoleInput = { FunctionName: "passrole-allowed", Runtime: "nodejs22.x" as const, Role: role.Role!.Arn!, Handler: "handler.handler", Code: { ZipFile: zip } }; await assert.rejects(deployer.send(new CreateFunctionCommand(passRoleInput)), (error: any) => error.name === "AccessDeniedException" && /iam:PassRole/.test(error.message)); await iam.send(new PutRolePolicyCommand({ RoleName: "lambda-deployer", PolicyName: "deploy", PolicyDocument: deployPolicy([role.Role!.Arn!]) })); assert.equal((await deployer.send(new CreateFunctionCommand(passRoleInput))).FunctionName, "passrole-allowed"); await new Promise(resolve => setTimeout(resolve, 0)); await assert.rejects(deployer.send(new UpdateFunctionConfigurationCommand({ FunctionName: "passrole-allowed", Role: secondRole.Role!.Arn! })), (error: any) => error.name === "AccessDeniedException" && /iam:PassRole/.test(error.message)); await iam.send(new PutRolePolicyCommand({ RoleName: "lambda-deployer", PolicyName: "deploy", PolicyDocument: deployPolicy([role.Role!.Arn!, secondRole.Role!.Arn!]) })); assert.equal((await deployer.send(new UpdateFunctionConfigurationCommand({ FunctionName: "passrole-allowed", Role: secondRole.Role!.Arn! }))).Role, secondRole.Role!.Arn);
    await lambda.send(new CreateFunctionCommand({ FunctionName: "runtime", Runtime: "nodejs22.x", Role: role.Role!.Arn!, Handler: "handler.handler", Code: { ZipFile: zip }, Environment: { Variables: { TABLE_NAME: "RuntimeData", STACKSIM_ENDPOINT: endpoint } } })); await new Promise(resolve => setTimeout(resolve, 0));
    const allowed = await lambda.send(new InvokeCommand({ FunctionName: "runtime", Payload: Buffer.from(JSON.stringify({ httpMethod: "GET", pathParameters: { id: "allowed" } })) })); assert.equal(allowed.FunctionError, undefined); assert.equal(JSON.parse(payload(allowed).body).id.S, "allowed");
    await assert.rejects(logs.send(new DescribeLogStreamsCommand({ logGroupName: "/aws/lambda/runtime" })), (error: any) => error.name === "ResourceNotFoundException");
    const denied = await lambda.send(new InvokeCommand({ FunctionName: "runtime", Payload: Buffer.from(JSON.stringify({ httpMethod: "POST", body: JSON.stringify({ id: "denied" }) })) })); assert.equal(denied.FunctionError, "Unhandled"); assert.match(JSON.stringify(payload(denied)), /AccessDeniedException/);
  } finally { clients.forEach(client => client.destroy()); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});
