import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { request as httpRequest } from "node:http";
import { Readable } from "node:stream";
import {
  AbortMultipartUploadCommand,
  CompleteMultipartUploadCommand,
  CopyObjectCommand,
  CreateBucketCommand,
  CreateMultipartUploadCommand,
  DeleteBucketCommand,
  DeleteObjectCommand,
  DeleteObjectsCommand,
  GetBucketVersioningCommand,
  GetBucketLocationCommand,
  GetObjectAttributesCommand,
  GetObjectCommand,
  GetObjectTorrentCommand,
  HeadBucketCommand,
  HeadObjectCommand,
  ListBucketsCommand,
  ListMultipartUploadsCommand,
  ListObjectsCommand,
  ListObjectsV2Command,
  ListObjectVersionsCommand,
  ListPartsCommand,
  PutBucketVersioningCommand,
  PutObjectCommand,
  S3Client,
  UploadPartCommand,
  UploadPartCopyCommand,
  waitUntilBucketExists,
  waitUntilObjectExists,
} from "@aws-sdk/client-s3";
import { Upload } from "@aws-sdk/lib-storage";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { TestClock } from "../src/core/clock.js";
import { StackSim, type SimulatorOptions } from "../src/server.js";
import { S3Checksums, type S3ChecksumAlgorithm } from "../src/s3/checksums.js";

const credentials = { accessKeyId: "admin", secretAccessKey: "password" };

function client(simulator: StackSim, region = "eu-west-1"): S3Client {
  return new S3Client({ endpoint: `http://127.0.0.1:${simulator.port}`, region, forcePathStyle: true, credentials });
}

async function bytes(output: Awaited<ReturnType<S3Client["send"]>> | any): Promise<Buffer> {
  return Buffer.from(await output.Body.transformToByteArray());
}

async function fixture(options: SimulatorOptions = {}) {
  const dataDir = await mkdtemp(join(tmpdir(), "stacksim-s3-")); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir, region: "eu-west-1", authMode: "off", cdkBootstrap: false, ...options }); await simulator.start(); return { dataDir, simulator, s3: client(simulator), async close() { await simulator.stop(); await rm(dataDir, { recursive: true, force: true }); } };
}

async function rawHttp(url: string, options: { method?: string; headers?: Record<string, string>; body?: string | Buffer } = {}): Promise<{ status: number; headers: Record<string, string | string[] | undefined>; body: Buffer }> {
  return new Promise((resolve, reject) => { const req = httpRequest(url, { method: options.method, headers: options.headers }, res => { const chunks: Buffer[] = []; res.on("data", chunk => chunks.push(Buffer.from(chunk))); res.on("end", () => resolve({ status: res.statusCode ?? 0, headers: res.headers, body: Buffer.concat(chunks) })); }); req.on("error", reject); if (options.body !== undefined) req.write(options.body); req.end(); });
}

test("S3-01 supports general-purpose buckets, opaque object keys, listings, encrypted persistence, and restart", async () => {
  const active = await fixture(); let simulator = active.simulator; let s3 = active.s3;
  try {
    const bucket = "phase-one-general-bucket";
    const created = await s3.send(new CreateBucketCommand({ Bucket: bucket, CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })); assert.equal(created.Location, `/${bucket}`);
    assert.equal((await waitUntilBucketExists({ client: s3, maxWaitTime: 5, minDelay: 1, maxDelay: 1 }, { Bucket: bucket })).state, "SUCCESS");
    assert.equal((await s3.send(new HeadBucketCommand({ Bucket: bucket }))).BucketRegion, "eu-west-1");
    assert.equal((await s3.send(new GetBucketLocationCommand({ Bucket: bucket }))).LocationConstraint, "eu-west-1");
    assert.deepEqual((await s3.send(new ListBucketsCommand({ Prefix: "phase-one" }))).Buckets?.map(item => item.Name), [bucket]);
    await assert.rejects(s3.send(new CreateBucketCommand({ Bucket: bucket, CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })), (error: any) => error.name === "BucketAlreadyOwnedByYou");
    const foreignBucket = "phase-one-foreign-owner"; simulator.store.regionState("eu-west-1", "111111111111").s3Buckets[foreignBucket] = { name: foreignBucket, arn: `arn:aws:s3:::${foreignBucket}`, region: "eu-west-1", ownerAccountId: "111111111111", ownerId: "foreign", createdAt: Date.now(), versioning: "unversioned" }; simulator.store.state.installation.s3BucketNames[foreignBucket] = { accountId: "111111111111", region: "eu-west-1" }; await assert.rejects(s3.send(new CreateBucketCommand({ Bucket: foreignBucket, CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })), (error: any) => error.name === "BucketAlreadyExists"); await assert.rejects(s3.send(new HeadBucketCommand({ Bucket: foreignBucket })), (error: any) => error.$metadata?.httpStatusCode === 403); delete simulator.store.regionState("eu-west-1", "111111111111").s3Buckets[foreignBucket]; delete simulator.store.state.installation.s3BucketNames[foreignBucket];
    const raceBucket = "phase-one-global-race"; const eastRace = client(simulator, "us-east-1"); const race = await Promise.allSettled([s3.send(new CreateBucketCommand({ Bucket: raceBucket, CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })), eastRace.send(new CreateBucketCommand({ Bucket: raceBucket }))]); assert.equal(race.filter(result => result.status === "fulfilled").length, 1); assert.equal(race.filter(result => result.status === "rejected" && result.reason?.name === "BucketAlreadyOwnedByYou").length, 1); const raceRegion = simulator.store.state.installation.s3BucketNames[raceBucket].region; await (raceRegion === "us-east-1" ? eastRace : s3).send(new DeleteBucketCommand({ Bucket: raceBucket })); eastRace.destroy();

    const payload = Buffer.from([0, 1, 2, 3, 254, 255]); const key = "folders/../opaque + % ✓.bin";
    const put = await s3.send(new PutObjectCommand({ Bucket: bucket, Key: key, Body: payload, ContentType: "application/octet-stream", Metadata: { purpose: "binary" } })); assert.match(put.ETag!, /^"[a-f0-9]{32}"$/); assert.equal(put.ServerSideEncryption, "AES256");
    assert.equal((await waitUntilObjectExists({ client: s3, maxWaitTime: 5, minDelay: 1, maxDelay: 1 }, { Bucket: bucket, Key: key })).state, "SUCCESS");
    await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "folders/alpha.txt", Body: "alpha" })); await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "folders/nested/bravo.txt", Body: "bravo" })); await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "zero", Body: Buffer.alloc(0) }));
    const got = await s3.send(new GetObjectCommand({ Bucket: bucket, Key: key, ChecksumMode: "ENABLED" })); assert.deepEqual(await bytes(got), payload); assert.deepEqual(got.Metadata, { purpose: "binary" }); assert.equal(got.ServerSideEncryption, "AES256"); assert.ok(got.ChecksumCRC32); assert.equal(got.ChecksumType, "FULL_OBJECT");
    assert.equal((await s3.send(new HeadObjectCommand({ Bucket: bucket, Key: "zero" }))).ContentLength, 0);
    const grouped = await s3.send(new ListObjectsV2Command({ Bucket: bucket, Prefix: "folders/", Delimiter: "/", MaxKeys: 2 })); assert.equal(grouped.IsTruncated, true); assert.ok(grouped.NextContinuationToken); const next = await s3.send(new ListObjectsV2Command({ Bucket: bucket, Prefix: "folders/", Delimiter: "/", MaxKeys: 2, ContinuationToken: grouped.NextContinuationToken })); assert.equal((grouped.Contents?.length ?? 0) + (grouped.CommonPrefixes?.length ?? 0) + (next.Contents?.length ?? 0) + (next.CommonPrefixes?.length ?? 0), 3); await assert.rejects(s3.send(new ListObjectsV2Command({ Bucket: bucket, Prefix: "folders/", Delimiter: "/", MaxKeys: 2, ContinuationToken: `${grouped.NextContinuationToken}tampered` })), (error: any) => error.name === "InvalidArgument"); const legacy = await s3.send(new ListObjectsCommand({ Bucket: bucket, Prefix: "folders/", MaxKeys: 1, EncodingType: "url" })); assert.equal(legacy.IsTruncated, true); assert.equal(legacy.NextMarker, undefined); const legacyNext = await s3.send(new ListObjectsCommand({ Bucket: bucket, Prefix: "folders/", Marker: legacy.Contents?.[0].Key, MaxKeys: 1 })); assert.notEqual(legacyNext.Contents?.[0].Key, legacy.Contents?.[0].Key); const legacyDelimited = await s3.send(new ListObjectsCommand({ Bucket: bucket, Prefix: "folders/", Delimiter: "/", MaxKeys: 1 })); assert.equal(legacyDelimited.IsTruncated, true); assert.ok(legacyDelimited.NextMarker);

    const paginationBucket = "phase-one-pagination-bucket"; await s3.send(new CreateBucketCommand({ Bucket: paginationBucket, CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })); const bucketPage = await s3.send(new ListBucketsCommand({ Prefix: "phase-one", MaxBuckets: 1 })); assert.equal(bucketPage.Buckets?.length, 1); assert.ok(bucketPage.ContinuationToken); assert.equal((await s3.send(new ListBucketsCommand({ Prefix: "phase-one", MaxBuckets: 1, ContinuationToken: bucketPage.ContinuationToken }))).Buckets?.length, 1); const paginationObjects: Record<string, any[]> = {}; for (let index = 0; index < 1_001; index++) paginationObjects[`object-${String(index).padStart(4, "0")}`] = [{ versionId: "null", size: 0, etag: createHash("md5").update(String(index)).digest("hex"), lastModified: Date.now() + index, metadata: {}, tags: {}, checksums: { CRC32: "AAAAAA==" }, checksumAlgorithm: "CRC32", checksumType: "FULL_OBJECT", storageClass: "STANDARD", encryption: "AES256" }]; await simulator.s3.storage.saveBucket(simulator.store.accountId, "eu-west-1", paginationBucket, { schemaVersion: 1, objects: paginationObjects, multipartUploads: {} }); const firstThousand = await s3.send(new ListObjectsV2Command({ Bucket: paginationBucket })); assert.equal(firstThousand.KeyCount, 1_000); assert.equal(firstThousand.IsTruncated, true); const finalPage = await s3.send(new ListObjectsV2Command({ Bucket: paginationBucket, ContinuationToken: firstThousand.NextContinuationToken })); assert.equal(finalPage.KeyCount, 1); await assert.rejects(s3.send(new DeleteBucketCommand({ Bucket: paginationBucket })), (error: any) => error.name === "BucketNotEmpty"); const emptyBucket = "phase-one-empty-delete"; await s3.send(new CreateBucketCommand({ Bucket: emptyBucket, CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })); await s3.send(new DeleteBucketCommand({ Bucket: emptyBucket })); await assert.rejects(s3.send(new HeadBucketCommand({ Bucket: emptyBucket })), (error: any) => error.name === "NotFound" || error.name === "NoSuchBucket");

    const virtual = await rawHttp(`http://127.0.0.1:${simulator.port}/${encodeURIComponent("folders/alpha.txt").replace(/%2F/g, "/")}`, { headers: { host: `${bucket}.localhost`, "x-stacksim-service": "s3" } }); assert.equal(virtual.status, 200); assert.equal(virtual.body.toString(), "alpha");
    const bad = await fetch(`http://127.0.0.1:${simulator.port}/${bucket}/failed`, { method: "PUT", headers: { "x-stacksim-service": "s3", "x-amz-checksum-sha256": "not-a-checksum" }, body: "must-not-publish" }); assert.equal(bad.status, 400); assert.match(await bad.text(), /<Code>BadDigest<\/Code>/); await assert.rejects(s3.send(new HeadObjectCommand({ Bucket: bucket, Key: "failed" })), (error: any) => error.name === "NotFound" || error.name === "NoSuchKey");

    const state = await readFile(join(active.dataDir, "state.json"), "utf8"); assert.doesNotMatch(state, /must-not-publish|folders\/\.\.\/opaque/); const blobParents = await readdir(join(active.dataDir, "s3", "blobs")); assert.ok(blobParents.length > 0); await writeFile(join(active.dataDir, "s3", "staging", "interrupted-upload.plain"), "partial-object");
    s3.destroy(); await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: active.dataDir, region: "eu-west-1", authMode: "off"}); await simulator.start(); s3 = client(simulator); assert.deepEqual(await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: key }))), payload); assert.deepEqual(await readdir(join(active.dataDir, "s3", "staging")), []);
    const wrongRegion = client(simulator, "us-east-1"); await assert.rejects(wrongRegion.send(new HeadBucketCommand({ Bucket: bucket })), (error: any) => error.$metadata?.httpStatusCode === 301 || error.name === "PermanentRedirect"); wrongRegion.destroy();
  } finally { s3.destroy(); if (simulator !== active.simulator) await simulator.stop(); await rm(active.dataDir, { recursive: true, force: true }); }

  const countLimited = await fixture({ s3MaximumObjectBytes: 5, s3MaximumBucketObjects: 1, s3MaximumBuckets: 1, s3MaximumTotalBytes: 10 });
  try { await countLimited.s3.send(new CreateBucketCommand({ Bucket: "phase-one-limits", CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })); await assert.rejects(countLimited.s3.send(new CreateBucketCommand({ Bucket: "phase-one-too-many", CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })), (error: any) => error.name === "TooManyBuckets"); await countLimited.s3.send(new PutObjectCommand({ Bucket: "phase-one-limits", Key: "first", Body: "12345" })); await assert.rejects(countLimited.s3.send(new PutObjectCommand({ Bucket: "phase-one-limits", Key: "too-large", Body: "123456" })), (error: any) => error.name === "EntityTooLarge"); await assert.rejects(countLimited.s3.send(new PutObjectCommand({ Bucket: "phase-one-limits", Key: "second", Body: "1" })), (error: any) => error.name === "ServiceUnavailable"); } finally { countLimited.s3.destroy(); await countLimited.close(); }
  const storageLimited = await fixture({ s3MaximumObjectBytes: 10, s3MaximumBucketObjects: 2, s3MaximumBuckets: 2, s3MaximumTotalBytes: 5 });
  try { await storageLimited.s3.send(new CreateBucketCommand({ Bucket: "phase-one-total-limit", CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })); await storageLimited.s3.send(new PutObjectCommand({ Bucket: "phase-one-total-limit", Key: "first", Body: "12345" })); await storageLimited.s3.send(new PutObjectCommand({ Bucket: "phase-one-total-limit", Key: "first", Body: "abcde" })); await assert.rejects(storageLimited.s3.send(new PutObjectCommand({ Bucket: "phase-one-total-limit", Key: "second", Body: "1" })), (error: any) => error.name === "ServiceUnavailable"); } finally { storageLimited.s3.destroy(); await storageLimited.close(); }
});

test("S3-02 supports HTTP conditions, ranges, copy, object attributes, torrents, and presigned SigV4", async () => {
  const active = await fixture(); const { simulator, s3 } = active; const bucket = "phase-two-http-bucket";
  try {
    await s3.send(new CreateBucketCommand({ Bucket: bucket, CreateBucketConfiguration: { LocationConstraint: { } as any } })).catch(async () => s3.send(new CreateBucketCommand({ Bucket: bucket, CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })));
    const source = await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "source.txt", Body: "0123456789", ContentType: "text/plain", Metadata: { source: "yes" }, Tagging: "source=yes", ChecksumAlgorithm: "SHA256" }));
    const checksumBody = Buffer.from("all-current-checksums"); const checksumEngine = new S3Checksums(); await checksumEngine.update(checksumBody); const digest = await checksumEngine.digest(); const algorithms: S3ChecksumAlgorithm[] = ["CRC32", "CRC32C", "CRC64NVME", "MD5", "SHA1", "SHA256", "SHA512", "XXHASH64", "XXHASH3", "XXHASH128"];
    for (const algorithm of algorithms) { const header = `x-amz-checksum-${algorithm.toLowerCase()}`; const put = await rawHttp(`http://127.0.0.1:${simulator.port}/${bucket}/checksum-${algorithm.toLowerCase()}`, { method: "PUT", headers: { "x-stacksim-service": "s3", "content-length": String(checksumBody.length), [header]: digest.values[algorithm]! }, body: checksumBody }); assert.equal(put.status, 200); assert.equal(put.headers[header], digest.values[algorithm]); const head = await rawHttp(`http://127.0.0.1:${simulator.port}/${bucket}/checksum-${algorithm.toLowerCase()}`, { method: "HEAD", headers: { "x-stacksim-service": "s3", "x-amz-checksum-mode": "ENABLED" } }); assert.equal(head.status, 200); assert.equal(head.headers[header], digest.values[algorithm]); }
    assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "source.txt", Range: "bytes=2-5" })))).toString(), "2345"); assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "source.txt", Range: "bytes=-3" })))).toString(), "789"); const rawRange = await rawHttp(`http://127.0.0.1:${simulator.port}/${bucket}/source.txt?response-content-type=application%2Fjson`, { headers: { "x-stacksim-service": "s3", range: "bytes=1-3" } }); assert.equal(rawRange.status, 206); assert.equal(rawRange.headers["content-range"], "bytes 1-3/10"); assert.equal(rawRange.headers["content-type"], "application/json"); assert.equal(rawRange.body.toString(), "123"); const multipleRanges = await rawHttp(`http://127.0.0.1:${simulator.port}/${bucket}/source.txt`, { headers: { "x-stacksim-service": "s3", range: "bytes=0-1,4-5" } }); assert.equal(multipleRanges.status, 416); assert.match(multipleRanges.body.toString(), /<Code>InvalidRange<\/Code>/);
    await assert.rejects(s3.send(new GetObjectCommand({ Bucket: bucket, Key: "source.txt", IfMatch: '"incorrect"' })), (error: any) => error.$metadata?.httpStatusCode === 412); const notModified = await fetch(`http://127.0.0.1:${simulator.port}/${bucket}/source.txt`, { headers: { "x-stacksim-service": "s3", "if-none-match": source.ETag! } }); assert.equal(notModified.status, 304);
    const copied = await s3.send(new CopyObjectCommand({ Bucket: bucket, Key: "copy.txt", CopySource: `${bucket}/source.txt`, MetadataDirective: "REPLACE", Metadata: { copied: "yes" }, ContentType: "text/custom", TaggingDirective: "REPLACE", Tagging: "copied=yes", ChecksumAlgorithm: "CRC64NVME" })); assert.equal(copied.CopyObjectResult?.ETag, source.ETag); assert.ok(copied.CopyObjectResult?.ChecksumCRC64NVME); const copyHead = await s3.send(new HeadObjectCommand({ Bucket: bucket, Key: "copy.txt" })); assert.deepEqual(copyHead.Metadata, { copied: "yes" }); assert.equal(copyHead.ContentType, "text/custom"); assert.equal(copyHead.TagCount, 1);
    await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "atomic-copy", Body: "prior destination" })); await assert.rejects(s3.send(new CopyObjectCommand({ Bucket: bucket, Key: "atomic-copy", CopySource: `${bucket}/source.txt`, CopySourceIfMatch: '"incorrect"' })), (error: any) => error.name === "PreconditionFailed"); assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "atomic-copy" })))).toString(), "prior destination"); const storage = simulator.s3.storage as any; const stageCopy = storage.stageFromBlobs.bind(storage); storage.stageFromBlobs = async (...args: any[]) => { const staged = await stageCopy(...args); await storage.discardStaged(staged); throw new Error("simulated interrupted copy"); }; try { await assert.rejects(s3.send(new CopyObjectCommand({ Bucket: bucket, Key: "atomic-copy", CopySource: `${bucket}/source.txt` })), (error: any) => error.name === "InternalError"); } finally { storage.stageFromBlobs = stageCopy; } assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "atomic-copy" })))).toString(), "prior destination"); assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "source.txt" })))).toString(), "0123456789");
    const attributes = await s3.send(new GetObjectAttributesCommand({ Bucket: bucket, Key: "copy.txt", ObjectAttributes: ["ETag", "Checksum", "ObjectSize", "StorageClass"] })); assert.equal(attributes.ETag, source.ETag); assert.equal(attributes.ObjectSize, 10); assert.equal(attributes.StorageClass, "STANDARD"); assert.ok(attributes.Checksum?.ChecksumCRC64NVME);
    const torrent = await s3.send(new GetObjectTorrentCommand({ Bucket: bucket, Key: "source.txt" })); const torrentBytes = await bytes(torrent); assert.equal(torrentBytes[0], "d".charCodeAt(0));
    const deleteTarget = await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "conditional-delete", Body: "keep-until-match" })); const failedDelete = await rawHttp(`http://127.0.0.1:${simulator.port}/${bucket}/conditional-delete`, { method: "DELETE", headers: { "x-stacksim-service": "s3", "if-match": '"incorrect"' } }); assert.equal(failedDelete.status, 412); assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "conditional-delete" })))).toString(), "keep-until-match"); const matchedDelete = await rawHttp(`http://127.0.0.1:${simulator.port}/${bucket}/conditional-delete`, { method: "DELETE", headers: { "x-stacksim-service": "s3", "if-match": deleteTarget.ETag! } }); assert.equal(matchedDelete.status, 204);

    const east = client(simulator, "us-east-1"); try { const eastBucket = "phase-two-east-source"; await east.send(new CreateBucketCommand({ Bucket: eastBucket })); await east.send(new PutObjectCommand({ Bucket: eastBucket, Key: "cross region + source", Body: "cross-region", Metadata: { region: "east" } })); await s3.send(new CopyObjectCommand({ Bucket: bucket, Key: "cross-region-copy", CopySource: `${eastBucket}/cross%20region%20%2B%20source` })); const crossRegion = await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "cross-region-copy" })); assert.equal((await bytes(crossRegion)).toString(), "cross-region"); assert.deepEqual(crossRegion.Metadata, { region: "east" }); } finally { east.destroy(); }
  } finally { s3.destroy(); await active.close(); }

  const clock = new TestClock(Date.now()); const signed = await fixture({ authMode: "validate", clock }); const signedClient = signed.s3;
  try {
    const signedBucket = "phase-two-presigned-bucket"; await signedClient.send(new CreateBucketCommand({ Bucket: signedBucket, CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })); await signedClient.send(new PutObjectCommand({ Bucket: signedBucket, Key: "a b/✓", Body: "presigned" })); const streaming = Buffer.from("signed-streaming-body"); await signedClient.send(new PutObjectCommand({ Bucket: signedBucket, Key: "streaming", Body: Readable.from([streaming.subarray(0, 6), streaming.subarray(6)]), ContentLength: streaming.length, ChecksumAlgorithm: "CRC32" })); assert.deepEqual(await bytes(await signedClient.send(new GetObjectCommand({ Bucket: signedBucket, Key: "streaming" }))), streaming); const url = await getSignedUrl(signedClient, new GetObjectCommand({ Bucket: signedBucket, Key: "a b/✓" }), { expiresIn: 60 }); const valid = await fetch(url); assert.equal(valid.status, 200); assert.equal(await valid.text(), "presigned"); const modified = new URL(url); modified.pathname = modified.pathname.replace("a%20b", "changed"); const invalid = await fetch(modified); assert.equal(invalid.status, 403); assert.match(await invalid.text(), /<Code>SignatureDoesNotMatch<\/Code>/);
    const putBody = Buffer.from("presigned-put-body"); const putChecksum = createHash("sha256").update(putBody).digest("base64"); const putUrl = await getSignedUrl(signedClient, new PutObjectCommand({ Bucket: signedBucket, Key: "presigned-put", ChecksumSHA256: putChecksum }), { expiresIn: 60 }); const putValid = await fetch(putUrl, { method: "PUT", body: putBody }); assert.equal(putValid.status, 200); const putMutatedBody = await fetch(putUrl, { method: "PUT", body: "mutated-body" }); assert.equal(putMutatedBody.status, 400); assert.match(await putMutatedBody.text(), /<Code>BadDigest<\/Code>/); const putMutatedQuery = new URL(putUrl); putMutatedQuery.searchParams.set("x-id", "GetObject"); assert.equal((await fetch(putMutatedQuery, { method: "PUT", body: putBody })).status, 403); assert.equal((await fetch(putUrl)).status, 403); const wrongHost = await rawHttp(putUrl, { method: "PUT", headers: { host: "mutated.localhost" }, body: putBody }); assert.equal(wrongHost.status, 403);
    const md5Body = Buffer.from("signed-header"); const md5 = createHash("md5").update(md5Body).digest("base64"); const signedHeaderUrl = await getSignedUrl(signedClient, new PutObjectCommand({ Bucket: signedBucket, Key: "signed-header", Body: md5Body, ContentMD5: md5 }), { expiresIn: 60 }); assert.equal((await fetch(signedHeaderUrl, { method: "PUT", headers: { "content-md5": md5 }, body: md5Body })).status, 200); assert.equal((await fetch(signedHeaderUrl, { method: "PUT", headers: { "content-md5": "AAAAAAAAAAAAAAAAAAAAAA==" }, body: md5Body })).status, 403);
    clock.advance(61_000); const expired = await fetch(url); assert.equal(expired.status, 400); assert.match(await expired.text(), /<Code>RequestExpired<\/Code>/);
  } finally { signedClient.destroy(); await signed.close(); }

  const enforced = await fixture({ authMode: "enforce", cdkBootstrap: true });
  try {
    const enforcedBucket = "phase-two-authorization"; await enforced.s3.send(new CreateBucketCommand({ Bucket: enforcedBucket, CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })); await enforced.s3.send(new PutObjectCommand({ Bucket: enforcedBucket, Key: "source", Body: "authorized copy" })); await enforced.s3.send(new CopyObjectCommand({ Bucket: enforcedBucket, Key: "destination", CopySource: `${enforcedBucket}/source` })); const decisions = enforced.simulator.store.ensureAccount().iam.authorizationDecisions.slice(-2); assert.deepEqual(decisions.map(decision => [decision.action, decision.resource]), [["s3:PutObject", `arn:aws:s3:::${enforcedBucket}/destination`], ["s3:GetObject", `arn:aws:s3:::${enforcedBucket}/source`]]);
  } finally { enforced.s3.destroy(); await enforced.close(); }
});

test("S3-03 supports multipart upload, part copy, replacement, listing, completion, abort, and lib-storage", async () => {
  const active = await fixture(); let simulator = active.simulator; let s3 = active.s3; const bucket = "phase-three-multipart-bucket";
  try {
    await s3.send(new CreateBucketCommand({ Bucket: bucket, CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })); await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "copy-source", Body: "copy-part-source" })); await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "large.bin", Body: "prior object" })); const interrupted = Readable.from((async function* () { yield Buffer.from("partial"); throw new Error("simulated disconnect"); })()) as any; interrupted.headers = {}; await assert.rejects(simulator.s3.storage.stageRequest(interrupted, 1_024), /simulated disconnect/); assert.deepEqual(await readdir(join(active.dataDir, "s3", "staging")), []);
    const initiated = await s3.send(new CreateMultipartUploadCommand({ Bucket: bucket, Key: "large.bin", Metadata: { upload: "multipart" }, ChecksumAlgorithm: "CRC32" })); const uploadId = initiated.UploadId!; const paginationUpload = await s3.send(new CreateMultipartUploadCommand({ Bucket: bucket, Key: "pagination.bin" })); const firstBody = Buffer.alloc(5 * 1024 * 1024, 7); const first = await s3.send(new UploadPartCommand({ Bucket: bucket, Key: "large.bin", UploadId: uploadId, PartNumber: 1, Body: firstBody, ChecksumAlgorithm: "CRC32" })); let second = await s3.send(new UploadPartCommand({ Bucket: bucket, Key: "large.bin", UploadId: uploadId, PartNumber: 2, Body: "old", ChecksumAlgorithm: "CRC32" })); second = await s3.send(new UploadPartCommand({ Bucket: bucket, Key: "large.bin", UploadId: uploadId, PartNumber: 2, Body: "tail", ChecksumAlgorithm: "CRC32" })); s3.destroy(); await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: active.dataDir, region: "eu-west-1", authMode: "off"}); await simulator.start(); s3 = client(simulator);
    const listed = await s3.send(new ListPartsCommand({ Bucket: bucket, Key: "large.bin", UploadId: uploadId })); assert.deepEqual(listed.Parts?.map(part => [part.PartNumber, part.Size]), [[1, firstBody.length], [2, 4]]); const partPage = await s3.send(new ListPartsCommand({ Bucket: bucket, Key: "large.bin", UploadId: uploadId, MaxParts: 1 })); assert.equal(partPage.IsTruncated, true); assert.equal((await s3.send(new ListPartsCommand({ Bucket: bucket, Key: "large.bin", UploadId: uploadId, PartNumberMarker: partPage.NextPartNumberMarker }))).Parts?.[0].PartNumber, 2); const uploadPage = await s3.send(new ListMultipartUploadsCommand({ Bucket: bucket, MaxUploads: 1 })); assert.equal(uploadPage.IsTruncated, true); assert.equal((await s3.send(new ListMultipartUploadsCommand({ Bucket: bucket, KeyMarker: uploadPage.NextKeyMarker, UploadIdMarker: uploadPage.NextUploadIdMarker }))).Uploads?.length, 1); await s3.send(new AbortMultipartUploadCommand({ Bucket: bucket, Key: "pagination.bin", UploadId: paginationUpload.UploadId }));
    await assert.rejects(s3.send(new CompleteMultipartUploadCommand({ Bucket: bucket, Key: "large.bin", UploadId: uploadId, MultipartUpload: { Parts: [{ PartNumber: 1, ETag: '"incorrect"', ChecksumCRC32: first.ChecksumCRC32 }] } })), (error: any) => error.name === "InvalidPart"); assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "large.bin" })))).toString(), "prior object"); assert.equal((await s3.send(new ListPartsCommand({ Bucket: bucket, Key: "large.bin", UploadId: uploadId }))).Parts?.length, 2);
    const completed = await s3.send(new CompleteMultipartUploadCommand({ Bucket: bucket, Key: "large.bin", UploadId: uploadId, MultipartUpload: { Parts: [{ PartNumber: 1, ETag: first.ETag, ChecksumCRC32: first.ChecksumCRC32 }, { PartNumber: 2, ETag: second.ETag, ChecksumCRC32: second.ChecksumCRC32 }] } })); assert.match(completed.ETag!, /-2"$/); assert.match(completed.ChecksumCRC32!, /-2$/); const downloaded = await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "large.bin" }))); assert.equal(downloaded.length, firstBody.length + 4); assert.equal(downloaded.subarray(-4).toString(), "tail"); assert.deepEqual((await s3.send(new HeadObjectCommand({ Bucket: bucket, Key: "large.bin" }))).Metadata, { upload: "multipart" }); const multipartAttributes = await s3.send(new GetObjectAttributesCommand({ Bucket: bucket, Key: "large.bin", ObjectAttributes: ["Checksum", "ObjectParts"], MaxParts: 1 })); assert.equal(multipartAttributes.ObjectParts?.TotalPartsCount, 2); assert.equal(multipartAttributes.ObjectParts?.Parts?.length, 1); assert.equal(multipartAttributes.ObjectParts?.IsTruncated, true); assert.match(multipartAttributes.Checksum?.ChecksumCRC32 ?? "", /-2$/);

    await assert.rejects(s3.send(new CreateMultipartUploadCommand({ Bucket: bucket, Key: "invalid-full", ChecksumAlgorithm: "SHA256", ChecksumType: "FULL_OBJECT" })), (error: any) => error.name === "InvalidRequest"); const full = await s3.send(new CreateMultipartUploadCommand({ Bucket: bucket, Key: "full-crc64", ChecksumAlgorithm: "CRC64NVME", ChecksumType: "FULL_OBJECT" })); const fullPart = await s3.send(new UploadPartCommand({ Bucket: bucket, Key: "full-crc64", UploadId: full.UploadId, PartNumber: 1, Body: "full-object-checksum", ChecksumAlgorithm: "CRC64NVME" })); const fullComplete = await s3.send(new CompleteMultipartUploadCommand({ Bucket: bucket, Key: "full-crc64", UploadId: full.UploadId, ChecksumType: "FULL_OBJECT", ChecksumCRC64NVME: fullPart.ChecksumCRC64NVME, MpuObjectSize: 20, MultipartUpload: { Parts: [{ PartNumber: 1, ETag: fullPart.ETag }] } })); assert.equal(fullComplete.ChecksumCRC64NVME, fullPart.ChecksumCRC64NVME); assert.equal(fullComplete.ChecksumType, "FULL_OBJECT");

    const copiedUpload = await s3.send(new CreateMultipartUploadCommand({ Bucket: bucket, Key: "part-copy" })); const copiedPart = await s3.send(new UploadPartCopyCommand({ Bucket: bucket, Key: "part-copy", UploadId: copiedUpload.UploadId, PartNumber: 1, CopySource: `${bucket}/copy-source`, CopySourceRange: "bytes=0-3" })); await s3.send(new CompleteMultipartUploadCommand({ Bucket: bucket, Key: "part-copy", UploadId: copiedUpload.UploadId, MultipartUpload: { Parts: [{ PartNumber: 1, ETag: copiedPart.CopyPartResult?.ETag }] } })); assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "part-copy" })))).toString(), "copy"); const copyIndex = await simulator.s3.storage.loadBucket(simulator.store.accountId, "eu-west-1", bucket); assert.deepEqual(copyIndex.objects["part-copy"][0].parts?.[0].copySource, { bucket, key: "copy-source", versionId: "null", range: "bytes=0-3" });
    const aborted = await s3.send(new CreateMultipartUploadCommand({ Bucket: bucket, Key: "aborted" })); await s3.send(new UploadPartCommand({ Bucket: bucket, Key: "aborted", UploadId: aborted.UploadId, PartNumber: 1, Body: "unused" })); await s3.send(new AbortMultipartUploadCommand({ Bucket: bucket, Key: "aborted", UploadId: aborted.UploadId })); await assert.rejects(s3.send(new ListPartsCommand({ Bucket: bucket, Key: "aborted", UploadId: aborted.UploadId })), (error: any) => error.name === "NoSuchUpload");

    const managedBody = Buffer.alloc(6 * 1024 * 1024, 9); const managed = new Upload({ client: s3, params: { Bucket: bucket, Key: "managed.bin", Body: managedBody }, partSize: 5 * 1024 * 1024, queueSize: 2 }); await managed.done(); assert.deepEqual(await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "managed.bin" }))), managedBody);
  } finally { s3.destroy(); if (simulator !== active.simulator) await simulator.stop(); else await active.simulator.stop(); await rm(active.dataDir, { recursive: true, force: true }); }
});

test("S3-04 supports version history, delete markers, suspension, version reads, and bulk deletion", async () => {
  const active = await fixture(); let simulator = active.simulator; let s3 = active.s3; const bucket = "phase-four-version-bucket";
  try {
    await s3.send(new CreateBucketCommand({ Bucket: bucket, CreateBucketConfiguration: { LocationConstraint: "eu-west-1" } })); const unversioned = await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "record", Body: "unversioned" })); assert.equal(unversioned.VersionId, undefined); assert.equal((await s3.send(new GetBucketVersioningCommand({ Bucket: bucket }))).Status, undefined); await s3.send(new PutBucketVersioningCommand({ Bucket: bucket, VersioningConfiguration: { Status: "Enabled" } })); const one = await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "record", Body: "one" })); const two = await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "record", Body: "two" })); assert.ok(one.VersionId); assert.ok(two.VersionId); assert.notEqual(one.VersionId, two.VersionId); const concurrent = await Promise.all(Array.from({ length: 10 }, (_, index) => s3.send(new PutObjectCommand({ Bucket: bucket, Key: "concurrent", Body: `write-${index}` })))); assert.equal(new Set(concurrent.map(result => result.VersionId)).size, 10); assert.equal((await s3.send(new ListObjectVersionsCommand({ Bucket: bucket, Prefix: "concurrent" }))).Versions?.length, 10);
    let versions = await s3.send(new ListObjectVersionsCommand({ Bucket: bucket, Prefix: "record", MaxKeys: 2 })); assert.equal(versions.IsTruncated, true); assert.equal(versions.Versions?.[0].VersionId, two.VersionId); const next = await s3.send(new ListObjectVersionsCommand({ Bucket: bucket, Prefix: "record", KeyMarker: versions.NextKeyMarker, VersionIdMarker: versions.NextVersionIdMarker })); assert.ok((next.Versions?.length ?? 0) >= 1); await assert.rejects(s3.send(new ListObjectVersionsCommand({ Bucket: bucket, Prefix: "record", KeyMarker: versions.NextKeyMarker, VersionIdMarker: `${versions.NextVersionIdMarker}tampered` })), (error: any) => error.name === "InvalidArgument");
    const restored = await s3.send(new CopyObjectCommand({ Bucket: bucket, Key: "restored-from-version", CopySource: `${bucket}/record?versionId=${encodeURIComponent(one.VersionId!)}` })); assert.equal(restored.CopySourceVersionId, one.VersionId); assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "restored-from-version" })))).toString(), "one"); const deleted = await s3.send(new DeleteObjectCommand({ Bucket: bucket, Key: "record" })); assert.equal(deleted.DeleteMarker, true); assert.ok(deleted.VersionId); await assert.rejects(s3.send(new GetObjectCommand({ Bucket: bucket, Key: "record" })), (error: any) => error.name === "NoSuchKey" && error.$response?.headers?.["x-amz-delete-marker"] === "true"); assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "record", VersionId: one.VersionId })))).toString(), "one"); await s3.send(new DeleteObjectCommand({ Bucket: bucket, Key: "record", VersionId: deleted.VersionId })); assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "record" })))).toString(), "two");
    await s3.send(new PutBucketVersioningCommand({ Bucket: bucket, VersioningConfiguration: { Status: "Suspended" } })); const nullOne = await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "suspended", Body: "null-one" })); const nullTwo = await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "suspended", Body: "null-two" })); assert.equal(nullOne.VersionId, undefined); assert.equal(nullTwo.VersionId, undefined); const suspendedVersions = await s3.send(new ListObjectVersionsCommand({ Bucket: bucket, Prefix: "suspended" })); assert.equal(suspendedVersions.Versions?.length, 1); assert.equal(suspendedVersions.Versions?.[0].VersionId, "null");
    await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "bulk-a", Body: "a" })); await s3.send(new PutObjectCommand({ Bucket: bucket, Key: "bulk-b", Body: "b" })); const missingChecksum = await rawHttp(`http://127.0.0.1:${simulator.port}/${bucket}?delete`, { method: "POST", headers: { "x-stacksim-service": "s3", "content-type": "application/xml" }, body: "<Delete><Object><Key>bulk-a</Key></Object></Delete>" }); assert.equal(missingChecksum.status, 400); assert.match(missingChecksum.body.toString(), /<Code>InvalidRequest<\/Code>/); const bulk = await s3.send(new DeleteObjectsCommand({ Bucket: bucket, Delete: { Objects: [{ Key: "bulk-a" }, { Key: "bulk-b" }, { Key: "missing" }], Quiet: false } })); assert.equal(bulk.Deleted?.length, 3); assert.ok(bulk.Deleted?.every(item => item.DeleteMarker)); const partial = await s3.send(new DeleteObjectsCommand({ Bucket: bucket, Delete: { Objects: [{ Key: "record", VersionId: "missing-version" }, { Key: "unrelated-missing" }], Quiet: false } })); assert.equal(partial.Errors?.[0].Code, "NoSuchVersion"); assert.equal(partial.Deleted?.[0].Key, "unrelated-missing"); versions = await s3.send(new ListObjectVersionsCommand({ Bucket: bucket })); assert.ok((versions.DeleteMarkers?.length ?? 0) >= 4); s3.destroy(); await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: active.dataDir, region: "eu-west-1", authMode: "off"}); await simulator.start(); s3 = client(simulator); assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "record", VersionId: one.VersionId })))).toString(), "one"); assert.equal((await bytes(await s3.send(new GetObjectCommand({ Bucket: bucket, Key: "restored-from-version" })))).toString(), "one"); assert.equal((await s3.send(new GetBucketVersioningCommand({ Bucket: bucket }))).Status, "Suspended");
  } finally { s3.destroy(); if (simulator !== active.simulator) await simulator.stop(); else await active.simulator.stop(); await rm(active.dataDir, { recursive: true, force: true }); }
});
