import assert from "node:assert/strict";
import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { CreateTableCommand, DynamoDBClient, GetItemCommand } from "@aws-sdk/client-dynamodb";
import { CreateEventBusCommand, EventBridgeClient, PutEventsCommand, PutRuleCommand, PutTargetsCommand } from "@aws-sdk/client-eventbridge";
import { CreateRoleCommand, IAMClient, PutRolePolicyCommand } from "@aws-sdk/client-iam";
import { CreateFunctionCommand, LambdaClient } from "@aws-sdk/client-lambda";
import { CreateTopicCommand, SNSClient, SubscribeCommand } from "@aws-sdk/client-sns";
import { CreateQueueCommand, ReceiveMessageCommand, SetQueueAttributesCommand, SQSClient } from "@aws-sdk/client-sqs";
import { CreateScheduleCommand, SchedulerClient } from "@aws-sdk/client-scheduler";
import {
  CreateActivityCommand, CreateStateMachineCommand, DeleteActivityCommand, DeleteStateMachineCommand, DescribeActivityCommand, DescribeExecutionCommand,
  GetActivityTaskCommand, GetExecutionHistoryCommand, ListActivitiesCommand, ListExecutionsCommand, ListStateMachinesCommand, ListTagsForResourceCommand, SendTaskFailureCommand, SendTaskHeartbeatCommand,
  SendTaskSuccessCommand, SFNClient, StartExecutionCommand, StopExecutionCommand, TagResourceCommand, ValidateStateMachineDefinitionCommand,
} from "@aws-sdk/client-sfn";
import { createZip } from "../src/core/zip-create.js";
import { TestClock } from "../src/core/clock.js";
import { AwsError } from "../src/errors.js";
import { StackSim } from "../src/server.js";
import { waitForTableActive } from "./support/dynamodb.js";

const region = "eu-west-1";
const credentials = { accessKeyId: "admin", secretAccessKey: "password" };
const clients = (simulator: StackSim) => {
  const options = { endpoint: `http://127.0.0.1:${simulator.port}`, region, credentials, maxAttempts: 1 };
  return { sfn: new SFNClient(options), iam: new IAMClient(options), lambda: new LambdaClient(options), dynamodb: new DynamoDBClient(options), sqs: new SQSClient(options), sns: new SNSClient(options), events: new EventBridgeClient(options) };
};
const destroy = (value: ReturnType<typeof clients>) => Object.values(value).forEach(client => client.destroy());
async function terminal(sfn: SFNClient, executionArn: string) {
  for (let attempt = 0; attempt < 400; attempt++) { const value = await sfn.send(new DescribeExecutionCommand({ executionArn })); if (value.status !== "RUNNING") return value; await new Promise(resolve => setTimeout(resolve, 5)); }
  throw new Error("execution did not become terminal");
}
async function waitForMessage(sqs: SQSClient, queueUrl: string, sfn?: SFNClient, executionArn?: string) {
  for (let attempt = 0; attempt < 400; attempt++) { const output = await sqs.send(new ReceiveMessageCommand({ QueueUrl: queueUrl, MaxNumberOfMessages: 1 })); if (output.Messages?.length) return output.Messages[0]; if (sfn && executionArn && attempt % 10 === 0) { const execution = await sfn.send(new DescribeExecutionCommand({ executionArn })); if (execution.status !== "RUNNING") throw new Error(`execution ended before callback: ${execution.status} ${execution.error} ${execution.cause}`); } await new Promise(resolve => setTimeout(resolve, 5)); }
  throw new Error("callback message was not accepted");
}

test("SFN-03 learning workflow uses real services and resumes an SQS callback exactly once across restart", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-sfn03-learning-")); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, authMode: "enforce", cdkBootstrap: true }); let api: ReturnType<typeof clients> | undefined;
  try {
    await simulator.start(); api = clients(simulator);
    const workflowRole = await api.iam.send(new CreateRoleCommand({ RoleName: "sfn03-workflow", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "states.amazonaws.com" }, Action: "sts:AssumeRole" }] }) }));
    const lambdaRole = await api.iam.send(new CreateRoleCommand({ RoleName: "sfn03-lambda", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "lambda.amazonaws.com" }, Action: "sts:AssumeRole" }] }) }));
    const fn = await api.lambda.send(new CreateFunctionCommand({ FunctionName: "sfn03-echo", Runtime: "nodejs22.x", Handler: "index.handler", Role: lambdaRole.Role!.Arn!, Code: { ZipFile: createZip([{ name: "index.js", content: "exports.handler = async event => ({ invoked: true, orderId: event.orderId });" }]) } }));
    await api.dynamodb.send(new CreateTableCommand({ TableName: "SfnOrders", BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "id", AttributeType: "S" }], KeySchema: [{ AttributeName: "id", KeyType: "HASH" }] }));
    await waitForTableActive(api.dynamodb, "SfnOrders");
    const queueUrl = (await api.sqs.send(new CreateQueueCommand({ QueueName: "sfn03-work" }))).QueueUrl!;
    const topicArn = (await api.sns.send(new CreateTopicCommand({ Name: "sfn03-events" }))).TopicArn!;
    const childDefinition = JSON.stringify({ StartAt: "ChildDone", States: { ChildDone: { Type: "Pass", Result: { nested: true }, End: true } } });
    const child = await api.sfn.send(new CreateStateMachineCommand({ name: "sfn03-child", definition: childDefinition, roleArn: workflowRole.Role!.Arn! }));
    await api.iam.send(new PutRolePolicyCommand({ RoleName: "sfn03-workflow", PolicyName: "least-privilege-integrations", PolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [
      { Effect: "Allow", Action: ["dynamodb:PutItem", "dynamodb:GetItem"], Resource: `arn:aws:dynamodb:${region}:000000000000:table/SfnOrders` },
      { Effect: "Allow", Action: "sqs:SendMessage", Resource: `arn:aws:sqs:${region}:000000000000:sfn03-work` },
      { Effect: "Allow", Action: "sns:Publish", Resource: topicArn },
      { Effect: "Allow", Action: "events:PutEvents", Resource: `arn:aws:events:${region}:000000000000:event-bus/default` },
      { Effect: "Allow", Action: "lambda:InvokeFunction", Resource: fn.FunctionArn },
      { Effect: "Allow", Action: "states:StartExecution", Resource: child.stateMachineArn },
      { Effect: "Allow", Action: ["states:DescribeExecution", "states:StopExecution"], Resource: `arn:aws:states:${region}:000000000000:execution:sfn03-child:*` },
    ] }) }));
    const definition = JSON.stringify({ StartAt: "Write", States: {
      Write: { Type: "Task", Resource: "arn:aws:states:::dynamodb:putItem", Parameters: { TableName: "SfnOrders", Item: { id: { S: "order-1" }, status: { S: "NEW" } } }, ResultPath: "$.write", Next: "Read" },
      Read: { Type: "Task", Resource: "arn:aws:states:::dynamodb:getItem", Parameters: { TableName: "SfnOrders", Key: { id: { S: "order-1" } }, ConsistentRead: true }, ResultPath: "$.read", Next: "Queue" },
      Queue: { Type: "Task", Resource: "arn:aws:states:::sqs:sendMessage", Parameters: { QueueUrl: queueUrl, MessageBody: "ordinary work" }, ResultPath: "$.queue", Next: "Topic" },
      Topic: { Type: "Task", Resource: "arn:aws:states:::sns:publish", Parameters: { TopicArn: topicArn, Message: "order created" }, ResultPath: "$.topic", Next: "Event" },
      Event: { Type: "Task", Resource: "arn:aws:states:::events:putEvents", Parameters: { Entries: [{ EventBusName: "default", Source: "learning.orders", DetailType: "OrderCreated", Detail: "{\"id\":\"order-1\"}" }] }, ResultPath: "$.event", Next: "Lambda" },
      Lambda: { Type: "Task", Resource: "arn:aws:states:::lambda:invoke", Parameters: { FunctionName: fn.FunctionArn, Payload: { orderId: "order-1" } }, ResultPath: "$.lambda", Next: "Nested" },
      Nested: { Type: "Task", Resource: "arn:aws:states:::states:startExecution.sync", Parameters: { StateMachineArn: child.stateMachineArn, Input: { source: "parent" } }, ResultPath: "$.nested", Next: "Callback" },
      Callback: { Type: "Task", Resource: "arn:aws:states:::sqs:sendMessage.waitForTaskToken", Parameters: { QueueUrl: queueUrl, "MessageBody.$": "$$.Task.Token" }, HeartbeatSeconds: 30, TimeoutSeconds: 120, ResultPath: "$.callback", End: true },
    } });
    assert.equal((await api.sfn.send(new ValidateStateMachineDefinitionCommand({ definition }))).result, "OK");
    const machine = await api.sfn.send(new CreateStateMachineCommand({ name: "sfn03-learning", definition, roleArn: workflowRole.Role!.Arn! }));
    let integrationEntries: any[] | undefined; const putEvents = simulator.eventbridge.PutEvents.bind(simulator.eventbridge);
    (simulator.eventbridge as any).PutEvents = (input: any, request: any, options: any) => { if (input.Entries?.[0]?.Source === "learning.orders") integrationEntries = structuredClone(input.Entries); return putEvents(input, request, options); };
    const started = await api.sfn.send(new StartExecutionCommand({ stateMachineArn: machine.stateMachineArn!, name: "restart-proof", input: "{}" }));
    let message; do { message = await waitForMessage(api.sqs, queueUrl, api.sfn, started.executionArn!); } while (message.Body === "ordinary work");
    const token = message.Body!; assert(token.length > 40);
    assert.equal((await api.dynamodb.send(new GetItemCommand({ TableName: "SfnOrders", Key: { id: { S: "order-1" } } }))).Item?.status?.S, "NEW");
    assert.deepEqual(integrationEntries?.[0]?.Resources?.slice(-2), [started.executionArn, machine.stateMachineArn]);
    const stateText = await readFile(join(root, "state.json"), "utf8"); assert(!stateText.includes(token), "raw task token is absent from control state");
    destroy(api); api = undefined; await simulator.stop();
    const executionDirectory = join(root, "data", "step-functions", "000000000000", region); for (const file of await readdir(executionDirectory)) { const contents = await readFile(join(executionDirectory, file)); assert(!contents.includes(Buffer.from(token)), `raw task token is absent from private execution file ${file}`); }

    simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, authMode: "enforce", cdkBootstrap: true }); await simulator.start(); api = clients(simulator);
    await assert.rejects(api.sfn.send(new SendTaskHeartbeatCommand({ taskToken: `${token.slice(0, -1)}x` })), (error: any) => error.name === "InvalidToken");
    const wrongRegion = new SFNClient({ endpoint: `http://127.0.0.1:${simulator.port}`, region: "us-east-1", credentials, maxAttempts: 1 }); await assert.rejects(wrongRegion.send(new SendTaskHeartbeatCommand({ taskToken: token })), (error: any) => error.name === "InvalidToken"); wrongRegion.destroy();
    const foreignRoot = join(root, "foreign-account"); const foreign = new StackSim({ port: 0, invokePort: 0, dataDir: foreignRoot, region, accountId: "111122223333", authMode: "off", cdkBootstrap: false }); await foreign.start(); const foreignSfn = new SFNClient({ endpoint: `http://127.0.0.1:${foreign.port}`, region, credentials, maxAttempts: 1 }); await assert.rejects(foreignSfn.send(new SendTaskHeartbeatCommand({ taskToken: token })), (error: any) => error.name === "InvalidToken"); foreignSfn.destroy(); await foreign.stop();
    await assert.rejects(api.sfn.send(new SendTaskSuccessCommand({ taskToken: token, output: JSON.stringify("x".repeat(262_145)) })), (error: any) => error.name === "InvalidOutput");
    await api.sfn.send(new SendTaskHeartbeatCommand({ taskToken: token }));
    await api.sfn.send(new SendTaskSuccessCommand({ taskToken: token, output: JSON.stringify({ approved: true }) }));
    await assert.rejects(api.sfn.send(new SendTaskSuccessCommand({ taskToken: token, output: "{}" })), (error: any) => error.name === "TaskDoesNotExist");
    const completed = await terminal(api.sfn, started.executionArn!); assert.equal(completed.status, "SUCCEEDED"); const output = JSON.parse(completed.output!); assert.equal(output.read.Item.status.S, "NEW"); assert.deepEqual(output.callback, { approved: true }); assert.equal(output.lambda.Payload.invoked, true); assert.equal(output.event.FailedEntryCount, 0); assert.equal(output.nested.Status, "SUCCEEDED");
    const history = (await api.sfn.send(new GetExecutionHistoryCommand({ executionArn: started.executionArn!, maxResults: 1000 }))).events ?? []; assert(history.filter(event => event.type === "TaskSucceeded").length >= 5); assert(history.some(event => event.type === "TaskScheduled")); assert(history.some(event => event.type === "TaskStarted")); assert(!JSON.stringify(history).includes(token), "task tokens are redacted from history");
  } finally { if (api) destroy(api); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("SFN-03 Activity lifecycle, leasing, heartbeat, tags, and completion survive restart", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-sfn03-activity-")); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, authMode: "off", cdkBootstrap: false }); let api: ReturnType<typeof clients> | undefined;
  try {
    await simulator.start(); api = clients(simulator); const role = await api.iam.send(new CreateRoleCommand({ RoleName: "activity-workflow", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "states.amazonaws.com" }, Action: "sts:AssumeRole" }] }) }));
    const activity = await api.sfn.send(new CreateActivityCommand({ name: "manual-review", tags: [{ key: "lab", value: "sfn03" }] })); const otherActivity = await api.sfn.send(new CreateActivityCommand({ name: "other-review" })); assert.equal((await api.sfn.send(new DescribeActivityCommand({ activityArn: activity.activityArn! }))).name, "manual-review"); assert.equal((await api.sfn.send(new ListActivitiesCommand({}))).activities?.length, 2);
    await api.sfn.send(new TagResourceCommand({ resourceArn: activity.activityArn!, tags: [{ key: "owner", value: "worker" }] })); assert.deepEqual((await api.sfn.send(new ListTagsForResourceCommand({ resourceArn: activity.activityArn! }))).tags?.map(tag => tag.key), ["lab", "owner"]);
    const definition = JSON.stringify({ StartAt: "Review", States: { Review: { Type: "Task", Resource: activity.activityArn, HeartbeatSeconds: 20, TimeoutSeconds: 120, End: true } } }); const machine = await api.sfn.send(new CreateStateMachineCommand({ name: "activity-proof", definition, roleArn: role.Role!.Arn! })); const wrongPoll = api.sfn.send(new GetActivityTaskCommand({ activityArn: otherActivity.activityArn!, workerName: "wrong-activity-worker" })); const workerPoll = api.sfn.send(new GetActivityTaskCommand({ activityArn: activity.activityArn!, workerName: "worker-a" })); await new Promise(resolve => setImmediate(resolve)); const started = await api.sfn.send(new StartExecutionCommand({ stateMachineArn: machine.stateMachineArn!, input: JSON.stringify({ orderId: "A-1" }) }));
    const [wrongClaim, claimed] = await Promise.all([wrongPoll, workerPoll]); assert.equal(wrongClaim.taskToken, "", "a long-polling worker cannot steal a task from another Activity"); assert(claimed.taskToken, "the waiting worker is woken when its Activity task is admitted"); assert.deepEqual(JSON.parse(claimed.input!), { orderId: "A-1" });
    destroy(api); api = undefined; await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, authMode: "off", cdkBootstrap: false }); await simulator.start(); api = clients(simulator);
    await api.sfn.send(new SendTaskHeartbeatCommand({ taskToken: claimed.taskToken! })); await api.sfn.send(new SendTaskSuccessCommand({ taskToken: claimed.taskToken!, output: JSON.stringify({ reviewed: true }) })); await assert.rejects(api.sfn.send(new SendTaskSuccessCommand({ taskToken: claimed.taskToken!, output: "{}" })), (error: any) => error.name === "TaskDoesNotExist"); const completed = await terminal(api.sfn, started.executionArn!); assert.equal(completed.status, "SUCCEEDED"); assert.deepEqual(JSON.parse(completed.output!), { reviewed: true }); const completedHistory = (await api.sfn.send(new GetExecutionHistoryCommand({ executionArn: started.executionArn!, maxResults: 1000 }))).events ?? []; assert(["ActivityScheduled", "ActivityStarted", "ActivitySucceeded"].every(type => completedHistory.some(event => event.type === type)));
    const rejected = await api.sfn.send(new StartExecutionCommand({ stateMachineArn: machine.stateMachineArn!, name: "rejected-review", input: "{}" })); const rejectedTask = await api.sfn.send(new GetActivityTaskCommand({ activityArn: activity.activityArn! })); await api.sfn.send(new SendTaskFailureCommand({ taskToken: rejectedTask.taskToken!, error: "ReviewRejected", cause: "reviewer declined" })); const rejectedResult = await terminal(api.sfn, rejected.executionArn!); assert.equal(rejectedResult.status, "FAILED"); assert.equal(rejectedResult.error, "ReviewRejected");
    const timeoutDefinition = JSON.stringify({ StartAt: "Review", States: { Review: { Type: "Task", Resource: activity.activityArn, HeartbeatSeconds: 1, TimeoutSeconds: 120, End: true } } }); const timeoutMachine = await api.sfn.send(new CreateStateMachineCommand({ name: "activity-timeout-proof", definition: timeoutDefinition, roleArn: role.Role!.Arn! })); const timed = await api.sfn.send(new StartExecutionCommand({ stateMachineArn: timeoutMachine.stateMachineArn!, input: "{}" })); const timedTask = await api.sfn.send(new GetActivityTaskCommand({ activityArn: activity.activityArn! })); await new Promise(resolve => setTimeout(resolve, 1_050)); await assert.rejects(api.sfn.send(new SendTaskHeartbeatCommand({ taskToken: timedTask.taskToken! })), (error: any) => error.name === "TaskTimedOut"); const timedResult = await terminal(api.sfn, timed.executionArn!); assert.equal(timedResult.status, "FAILED"); assert.equal(timedResult.error, "States.HeartbeatTimeout");
    await api.sfn.send(new DeleteActivityCommand({ activityArn: activity.activityArn! })); await api.sfn.send(new DeleteActivityCommand({ activityArn: otherActivity.activityArn! })); assert.deepEqual((await api.sfn.send(new ListActivitiesCommand({}))).activities, []);
  } finally { if (api) destroy(api); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("SFN-03 rejects unsupported integration patterns before state-machine mutation", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-sfn03-negative-")); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, authMode: "off", cdkBootstrap: false }); let api: ReturnType<typeof clients> | undefined;
  try {
    await simulator.start(); api = clients(simulator); const role = await api.iam.send(new CreateRoleCommand({ RoleName: "negative-workflow", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "states.amazonaws.com" }, Action: "sts:AssumeRole" }] }) }));
    const invalid = [
      { resource: "arn:aws:states:::dynamodb:transactWriteItems", parameters: {} },
      { resource: "arn:aws:states:::sqs:sendMessage.sync", parameters: { QueueUrl: "https://sqs.eu-west-1.amazonaws.com/000000000000/q", MessageBody: "x" } },
      { resource: "arn:aws:states:::aws-sdk:s3:getObject", parameters: { Bucket: "b", Key: "k" } },
      { resource: "arn:aws:states:::states:startExecution", parameters: { StateMachineArn: "arn:aws:states:eu-west-1:111122223333:stateMachine:foreign" } },
      { resource: "arn:aws:states:::sqs:sendMessage", parameters: { queueUrl: "https://sqs.eu-west-1.amazonaws.com/000000000000/q", MessageBody: "x" } },
    ];
    for (const [index, item] of invalid.entries()) { const definition = JSON.stringify({ StartAt: "Unsupported", States: { Unsupported: { Type: "Task", Resource: item.resource, Parameters: item.parameters, End: true } } }); const validation: any = await api.sfn.send(new ValidateStateMachineDefinitionCommand({ definition })); assert.equal(validation.result, "FAIL", item.resource); await assert.rejects(api.sfn.send(new CreateStateMachineCommand({ name: `invalid-${index}`, definition, roleArn: role.Role!.Arn! })), (error: any) => error.name === "InvalidDefinition"); }
    assert.deepEqual((await api.sfn.send(new ListStateMachinesCommand({}))).stateMachines, []);
  }
  finally { if (api) destroy(api); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("SFN-03 EventBridge and Scheduler producers use durable StartExecution admission", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-sfn03-producers-")); const startedAt = Date.now(); const clock = new TestClock(startedAt); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, clock, authMode: "enforce", cdkBootstrap: true }); let api: ReturnType<typeof clients> | undefined; let scheduler: SchedulerClient | undefined;
  try {
    await simulator.start(); api = clients(simulator); scheduler = new SchedulerClient({ endpoint: `http://127.0.0.1:${simulator.port}`, region, credentials, maxAttempts: 1 });
    const workflow = await api.iam.send(new CreateRoleCommand({ RoleName: "producer-workflow", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "states.amazonaws.com" }, Action: "sts:AssumeRole" }] }) }));
    const machine = await api.sfn.send(new CreateStateMachineCommand({ name: "producer-target", roleArn: workflow.Role!.Arn!, definition: JSON.stringify({ StartAt: "Done", States: { Done: { Type: "Succeed" } } }) }));
    const role = async (name: string, service: string) => { const created = await api!.iam.send(new CreateRoleCommand({ RoleName: name, AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: service }, Action: "sts:AssumeRole" }] }) })); await api!.iam.send(new PutRolePolicyCommand({ RoleName: name, PolicyName: "start", PolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Action: "states:StartExecution", Resource: machine.stateMachineArn }] }) })); return created.Role!.Arn!; };
    const eventsRole = await role("events-start-workflow", "events.amazonaws.com"); const schedulerRole = await role("scheduler-start-workflow", "scheduler.amazonaws.com");
    let eventAdmissions = 0; let schedulerAdmissions = 0; const admit = simulator.stepfunctions.startExecutionFromProducer.bind(simulator.stepfunctions); (simulator.stepfunctions as any).startExecutionFromProducer = async (input: any) => { const output = await admit(input); const schedulerSource = String(input.sourceArn).includes(":schedule/"); if (schedulerSource ? ++schedulerAdmissions === 1 : ++eventAdmissions === 1) throw new AwsError("InternalServerException", "simulated lost durable StartExecution response", 500); return output; };
    await api.events.send(new PutRuleCommand({ Name: "start-workflow", EventPattern: JSON.stringify({ source: ["learning.producer"] }) })); await api.events.send(new PutTargetsCommand({ Rule: "start-workflow", Targets: [{ Id: "workflow", Arn: machine.stateMachineArn!, RoleArn: eventsRole }] })); await api.events.send(new PutEventsCommand({ Entries: [{ Source: "learning.producer", DetailType: "Start", Detail: "{\"from\":\"events\"}" }] }));
    for (let attempt = 0; attempt < 200 && (await api.sfn.send(new ListExecutionsCommand({ stateMachineArn: machine.stateMachineArn! }))).executions?.length !== 1; attempt++) { clock.advance(0); await new Promise(resolve => setTimeout(resolve, 5)); }
    assert.equal((await api.sfn.send(new ListExecutionsCommand({ stateMachineArn: machine.stateMachineArn! }))).executions?.length, 1);
    clock.advance(2_000); for (let attempt = 0; attempt < 200 && eventAdmissions < 2; attempt++) { clock.advance(0); await new Promise(resolve => setTimeout(resolve, 5)); } assert.equal(eventAdmissions, 2); assert.equal((await api.sfn.send(new ListExecutionsCommand({ stateMachineArn: machine.stateMachineArn! }))).executions?.length, 1, "EventBridge retry reconciles the original durable admission");
    const at = new Date(startedAt + 60_000).toISOString().slice(0, 19); await scheduler.send(new CreateScheduleCommand({ Name: "start-workflow", ScheduleExpression: `at(${at})`, FlexibleTimeWindow: { Mode: "OFF" }, Target: { Arn: machine.stateMachineArn!, RoleArn: schedulerRole, Input: JSON.stringify({ from: "scheduler" }) } })); clock.advance(60_000);
    for (let attempt = 0; attempt < 200 && (await api.sfn.send(new ListExecutionsCommand({ stateMachineArn: machine.stateMachineArn! }))).executions?.length !== 2; attempt++) { clock.advance(0); await new Promise(resolve => setTimeout(resolve, 5)); }
    const executions = (await api.sfn.send(new ListExecutionsCommand({ stateMachineArn: machine.stateMachineArn! }))).executions ?? []; assert.equal(executions.length, 2); assert(executions.every(item => item.status === "SUCCEEDED" || item.status === "RUNNING"));
    for (let attempt = 0; attempt < 200 && !Object.values(simulator.store.regionState(region).eventScheduleOccurrences).some(item => item.attempts === 1 && item.status === "QUEUED"); attempt++) { clock.advance(0); await new Promise(resolve => setTimeout(resolve, 5)); } clock.advance(2_000); for (let attempt = 0; attempt < 200 && schedulerAdmissions < 2; attempt++) { clock.advance(0); await new Promise(resolve => setTimeout(resolve, 5)); } assert.equal(schedulerAdmissions, 2); assert.equal((await api.sfn.send(new ListExecutionsCommand({ stateMachineArn: machine.stateMachineArn! }))).executions?.length, 2, "Scheduler retry reconciles the original durable admission");
  } finally { scheduler?.destroy(); if (api) destroy(api); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("SFN-03 owning-service receipts reconcile receipt-backed acceptance faults without duplicate dispatch", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-sfn03-attempts-")); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, authMode: "off", cdkBootstrap: false }); let api: ReturnType<typeof clients> | undefined;
  const restart = async (beforeStart?: (next: StackSim) => void, afterStop?: () => Promise<void>) => { if (api) { destroy(api); api = undefined; } await simulator.stop(); await afterStop?.(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, authMode: "off", cdkBootstrap: false }); beforeStart?.(simulator); await simulator.start(); api = clients(simulator); };
  const waitFor = async (condition: () => boolean) => { for (let index = 0; index < 400; index++) { if (condition()) return; await new Promise(resolve => setTimeout(resolve, 5)); } throw new Error("fault seam was not reached"); };
  try {
    await simulator.start(); api = clients(simulator); const role = await api.iam.send(new CreateRoleCommand({ RoleName: "attempt-workflow", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "states.amazonaws.com" }, Action: "sts:AssumeRole" }] }) }));
    await api.dynamodb.send(new CreateTableCommand({ TableName: "AttemptOrders", BillingMode: "PAY_PER_REQUEST", AttributeDefinitions: [{ AttributeName: "id", AttributeType: "S" }], KeySchema: [{ AttributeName: "id", KeyType: "HASH" }] }));
    await waitForTableActive(api.dynamodb, "AttemptOrders");
    const queueUrl = (await api.sqs.send(new CreateQueueCommand({ QueueName: "attempt-work" }))).QueueUrl!;
    const topicArn = (await api.sns.send(new CreateTopicCommand({ Name: "attempt-topic" }))).TopicArn!;
    const lambdaRole = await api.iam.send(new CreateRoleCommand({ RoleName: "attempt-lambda", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "lambda.amazonaws.com" }, Action: "sts:AssumeRole" }] }) }));
    const fn = await api.lambda.send(new CreateFunctionCommand({ FunctionName: "attempt-echo", Runtime: "nodejs22.x", Handler: "index.handler", Role: lambdaRole.Role!.Arn!, Code: { ZipFile: createZip([{ name: "index.js", content: "exports.handler = async event => ({ accepted: true, value: event.value });" }]) } }));

    let dynamoAccepted = false; const putItem = simulator.dynamodb.PutItem.bind(simulator.dynamodb); (simulator.dynamodb as any).PutItem = async (...args: any[]) => { const output = await putItem(args[0], args[1]); if (!dynamoAccepted) { dynamoAccepted = true; simulator.stepfunctions.beginShutdown(); throw new Error("fault after DynamoDB durable acceptance"); } return output; };
    const dynamoMachine = await api.sfn.send(new CreateStateMachineCommand({ name: "attempt-dynamo", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Write", States: { Write: { Type: "Task", Resource: "arn:aws:states:::dynamodb:putItem", Parameters: { TableName: "AttemptOrders", Item: { id: { S: "one" }, count: { N: "1" }, private: { S: "classified-value" } } }, End: true } } }) }));
    const dynamoExecution = await api.sfn.send(new StartExecutionCommand({ stateMachineArn: dynamoMachine.stateMachineArn! })); await waitFor(() => dynamoAccepted); let recoveryInterrupted = false; await restart(next => { const reconcile = next.dynamodb.reconcileIntegrationAttempt.bind(next.dynamodb); (next.dynamodb as any).reconcileIntegrationAttempt = (...args: any[]) => { if (!recoveryInterrupted) { recoveryInterrupted = true; next.stepfunctions.beginShutdown(); throw new Error("fault during owning-service reconciliation"); } return reconcile(args[0]); }; }, async () => { const path = join(root, "state.json"); const legacy = JSON.parse(await readFile(path, "utf8")); const attempts = legacy.accounts["000000000000"].regions[region].dynamodbIntegrationAttempts; for (const descriptor of Object.values(attempts) as any[]) { descriptor.output = {}; delete descriptor.outputDigest; } await writeFile(path, JSON.stringify(legacy)); const receiptPath = join(root, "data", "dynamodb", "000000000000", region, "integration-attempts.sqlite"); await rm(receiptPath, { force: true }); await rm(`${receiptPath}-wal`, { force: true }); await rm(`${receiptPath}-shm`, { force: true }); }); await waitFor(() => recoveryInterrupted); const migratedState = JSON.parse(await readFile(join(root, "state.json"), "utf8")); assert(Object.values(migratedState.accounts["000000000000"].regions[region].dynamodbIntegrationAttempts).every((attempt: any) => !Object.hasOwn(attempt, "output") && typeof attempt.outputDigest === "string"), "legacy v85 inline receipts migrate to private payload storage"); await restart(); assert.equal((await terminal(api!.sfn, dynamoExecution.executionArn!)).status, "SUCCEEDED"); assert.equal((await api!.dynamodb.send(new GetItemCommand({ TableName: "AttemptOrders", Key: { id: { S: "one" } } }))).Item?.count?.N, "1");

    let readAccepted = false; const getItem = simulator.dynamodb.GetItem.bind(simulator.dynamodb); (simulator.dynamodb as any).GetItem = async (...args: any[]) => { const output = await getItem(args[0], args[1]); if (!readAccepted) { readAccepted = true; simulator.stepfunctions.beginShutdown(); throw new Error("fault after private DynamoDB result receipt"); } return output; }; const readMachine = await api!.sfn.send(new CreateStateMachineCommand({ name: "attempt-dynamo-private-read", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Read", States: { Read: { Type: "Task", Resource: "arn:aws:states:::dynamodb:getItem", Parameters: { TableName: "AttemptOrders", Key: { id: { S: "one" } } }, End: true } } }) })); const readExecution = await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: readMachine.stateMachineArn! })); await waitFor(() => readAccepted); const controlState = JSON.parse(await readFile(join(root, "state.json"), "utf8")); const receiptDescriptors = controlState.accounts["000000000000"].regions[region].dynamodbIntegrationAttempts; assert(Object.values(receiptDescriptors).every((receipt: any) => !Object.hasOwn(receipt, "output"))); assert(!JSON.stringify(receiptDescriptors).includes("classified-value"), "DynamoDB receipt payload is excluded from its control descriptors"); await restart(); const readResult = await terminal(api!.sfn, readExecution.executionArn!); assert.equal(JSON.parse(readResult.output!).Item.private.S, "classified-value");

    let updateAccepted = false; const updateItem = simulator.dynamodb.UpdateItem.bind(simulator.dynamodb); (simulator.dynamodb as any).UpdateItem = async (...args: any[]) => { const output = await updateItem(args[0], args[1]); if (!updateAccepted) { updateAccepted = true; simulator.stepfunctions.beginShutdown(); throw new Error("fault after DynamoDB UpdateItem durable acceptance"); } return output; }; const updateMachine = await api!.sfn.send(new CreateStateMachineCommand({ name: "attempt-dynamo-update", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Update", States: { Update: { Type: "Task", Resource: "arn:aws:states:::dynamodb:updateItem", Parameters: { TableName: "AttemptOrders", Key: { id: { S: "one" } }, UpdateExpression: "SET #count = :count", ExpressionAttributeNames: { "#count": "count" }, ExpressionAttributeValues: { ":count": { N: "2" } }, ReturnValues: "ALL_NEW" }, End: true } } }) })); const updateExecution = await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: updateMachine.stateMachineArn! })); await waitFor(() => updateAccepted); await restart(); const updateResult = await terminal(api!.sfn, updateExecution.executionArn!); assert.equal(JSON.parse(updateResult.output!).Attributes.count.N, "2"); assert.equal((await api!.dynamodb.send(new GetItemCommand({ TableName: "AttemptOrders", Key: { id: { S: "one" } } }))).Item?.count?.N, "2");

    let deleteAccepted = false; const deleteItem = simulator.dynamodb.DeleteItem.bind(simulator.dynamodb); (simulator.dynamodb as any).DeleteItem = async (...args: any[]) => { const output = await deleteItem(args[0], args[1]); if (!deleteAccepted) { deleteAccepted = true; simulator.stepfunctions.beginShutdown(); throw new Error("fault after DynamoDB DeleteItem durable acceptance"); } return output; }; const deleteMachine = await api!.sfn.send(new CreateStateMachineCommand({ name: "attempt-dynamo-delete", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Delete", States: { Delete: { Type: "Task", Resource: "arn:aws:states:::dynamodb:deleteItem", Parameters: { TableName: "AttemptOrders", Key: { id: { S: "one" } }, ReturnValues: "ALL_OLD" }, End: true } } }) })); const deleteExecution = await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: deleteMachine.stateMachineArn! })); await waitFor(() => deleteAccepted); await restart(); const deleteResult = await terminal(api!.sfn, deleteExecution.executionArn!); assert.equal(JSON.parse(deleteResult.output!).Attributes.private.S, "classified-value"); assert.equal((await api!.dynamodb.send(new GetItemCommand({ TableName: "AttemptOrders", Key: { id: { S: "one" } } }))).Item, undefined);

    const beforeQueueUrl = (await api!.sqs.send(new CreateQueueCommand({ QueueName: "attempt-before-dispatch" }))).QueueUrl!; let beforeDispatch = false; (simulator.sqs as any).SendMessageToArn = async () => { beforeDispatch = true; simulator.stepfunctions.beginShutdown(); throw new Error("fault before SQS dispatch"); }; const beforeMachine = await api!.sfn.send(new CreateStateMachineCommand({ name: "attempt-before", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Send", States: { Send: { Type: "Task", Resource: "arn:aws:states:::sqs:sendMessage", Parameters: { QueueUrl: beforeQueueUrl, MessageBody: "after-recovery" }, End: true } } }) })); const beforeExecution = await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: beforeMachine.stateMachineArn! })); await waitFor(() => beforeDispatch); await restart(); assert.equal((await terminal(api!.sfn, beforeExecution.executionArn!)).status, "SUCCEEDED"); assert.deepEqual(((await api!.sqs.send(new ReceiveMessageCommand({ QueueUrl: beforeQueueUrl, MaxNumberOfMessages: 10 }))).Messages ?? []).map(item => item.Body), ["after-recovery"]);

    let sqsAccepted = false; const sendMessage = simulator.sqs.SendMessageToArn.bind(simulator.sqs); (simulator.sqs as any).SendMessageToArn = async (...args: any[]) => { const output = await sendMessage(args[0], args[1], args[2]); if (!sqsAccepted) { sqsAccepted = true; simulator.stepfunctions.beginShutdown(); throw new Error("fault after SQS durable acceptance"); } return output; };
    const sqsMachine = await api!.sfn.send(new CreateStateMachineCommand({ name: "attempt-sqs", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Send", States: { Send: { Type: "Task", Resource: "arn:aws:states:::sqs:sendMessage", Parameters: { QueueUrl: queueUrl, MessageBody: "once" }, End: true } } }) }));
    const sqsExecution = await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: sqsMachine.stateMachineArn! })); await waitFor(() => sqsAccepted); const sqsStorage = (simulator.sqs as any).storage; await restart(undefined, async () => { await sqsStorage.createQueue(`arn:aws:sqs:${region}:000000000000:attempt-work`, true); }); assert.equal((await terminal(api!.sfn, sqsExecution.executionArn!)).status, "SUCCEEDED", "a queue recreation cannot erase the owning receipt for an already committed send"); const messages = (await api!.sqs.send(new ReceiveMessageCommand({ QueueUrl: queueUrl, MaxNumberOfMessages: 10 }))).Messages ?? []; assert.deepEqual(messages.map(item => item.Body), [], "the recreated queue correctly has no messages from the deleted generation");

    let lambdaAccepted = false; const invoke = simulator.lambda.invoke.bind(simulator.lambda); (simulator.lambda as any).invoke = async (...args: any[]) => { const output = await invoke(args[0], args[1], args[2], args[3]); if (!lambdaAccepted) { lambdaAccepted = true; simulator.stepfunctions.beginShutdown(); throw new Error("fault after Lambda completion receipt"); } return output; };
    const lambdaMachine = await api!.sfn.send(new CreateStateMachineCommand({ name: "attempt-lambda", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Invoke", States: { Invoke: { Type: "Task", Resource: "arn:aws:states:::lambda:invoke", Parameters: { FunctionName: fn.FunctionArn, Payload: { value: 7 } }, End: true } } }) }));
    const lambdaExecution = await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: lambdaMachine.stateMachineArn! })); await waitFor(() => lambdaAccepted); await restart(); const lambdaResult = await terminal(api!.sfn, lambdaExecution.executionArn!); assert.equal(lambdaResult.status, "SUCCEEDED"); assert.deepEqual(JSON.parse(lambdaResult.output!).Payload, { accepted: true, value: 7 });

    let lambdaDispatchBoundary = false; (simulator.lambda as any).invoke = async () => { lambdaDispatchBoundary = true; simulator.stepfunctions.beginShutdown(); throw new Error("fault at unknowable Lambda dispatch boundary"); }; const ambiguousMachine = await api!.sfn.send(new CreateStateMachineCommand({ name: "attempt-lambda-ambiguous", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Invoke", States: { Invoke: { Type: "Task", Resource: "arn:aws:states:::lambda:invoke", Parameters: { FunctionName: fn.FunctionArn, Payload: { value: 8 } }, End: true } } }) })); const ambiguousExecution = await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: ambiguousMachine.stateMachineArn! })); await waitFor(() => lambdaDispatchBoundary); await restart(); const ambiguousResult = await terminal(api!.sfn, ambiguousExecution.executionArn!); assert.equal(ambiguousResult.status, "FAILED"); assert.equal(ambiguousResult.error, "States.TaskFailed"); assert.match(ambiguousResult.cause!, /without an owning-service completion receipt|without.*receipt/i);

    let snsAccepted = false; const publish = simulator.sns.publishAuthorized.bind(simulator.sns); (simulator.sns as any).publishAuthorized = async (...args: any[]) => { const output = await publish(args[0], args[1], args[2]); if (!snsAccepted) { snsAccepted = true; simulator.stepfunctions.beginShutdown(); throw new Error("fault after SNS durable acceptance"); } return output; };
    const snsMachine = await api!.sfn.send(new CreateStateMachineCommand({ name: "attempt-sns", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Publish", States: { Publish: { Type: "Task", Resource: "arn:aws:states:::sns:publish", Parameters: { TopicArn: topicArn, Message: "once" }, End: true } } }) })); const snsExecution = await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: snsMachine.stateMachineArn! })); await waitFor(() => snsAccepted); await restart(); assert.equal((await terminal(api!.sfn, snsExecution.executionArn!)).status, "SUCCEEDED");

    await api!.events.send(new CreateEventBusCommand({ Name: "attempt-bus" })); await api!.events.send(new PutRuleCommand({ Name: "attempt-event-rule", EventBusName: "attempt-bus", EventPattern: JSON.stringify({ source: ["attempt.test"] }) })); await api!.events.send(new PutTargetsCommand({ Rule: "attempt-event-rule", EventBusName: "attempt-bus", Targets: [{ Id: "attempt-target", Arn: `arn:aws:sqs:${region}:000000000000:attempt-work` }] })); let eventAccepted = false; const eventDeliveries = (simulator.eventbridge as any).deliveries; const putMany = eventDeliveries.putMany.bind(eventDeliveries); eventDeliveries.putMany = async (...args: any[]) => { const output = await putMany(...args); if (!eventAccepted && String(args[2]?.attemptId ?? "").includes(":entry:")) { eventAccepted = true; (simulator.eventbridge as any).stopped = true; simulator.stepfunctions.beginShutdown(); throw new Error("fault after atomic EventBridge entry acceptance and before parent receipt"); } return output; };
    const eventMachine = await api!.sfn.send(new CreateStateMachineCommand({ name: "attempt-event", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Put", States: { Put: { Type: "Task", Resource: "arn:aws:states:::events:putEvents", Parameters: { Entries: [{ EventBusName: "attempt-bus", Source: "attempt.test", DetailType: "Once", Detail: "{}" }] }, End: true } } }) })); const eventExecution = await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: eventMachine.stateMachineArn! })); await waitFor(() => eventAccepted); await restart(undefined, async () => { const path = join(root, "state.json"); const state = JSON.parse(await readFile(path, "utf8")); delete state.accounts["000000000000"].regions[region].eventBuses["attempt-bus"]; await writeFile(path, JSON.stringify(state)); }); const eventResult = await terminal(api!.sfn, eventExecution.executionArn!); assert.equal(eventResult.status, "SUCCEEDED", `${eventResult.error}: ${eventResult.cause}`); assert.equal(JSON.parse(eventResult.output!).FailedEntryCount, 0); const eventJournal = (await readFile(join(root, "data", "eventbridge", "000000000000", region, "deliveries.jsonl"), "utf8")).trim().split(/\r?\n/).map(line => JSON.parse(line)); const acceptedDeliveries = eventJournal.flatMap(record => record.op === "accept-integration-entry" ? record.deliveries : record.op === "put" ? [record.delivery] : []).filter((delivery: any) => String(delivery?.originalEvent).includes("attempt.test")); assert.equal(new Set(acceptedDeliveries.map((delivery: any) => delivery.id)).size, 1, "recovery reuses the one durably admitted delivery identity even after target deletion"); const entryReceipts = eventJournal.flatMap(record => record.op === "accept-integration-entry" ? [record.attempt] : record.op === "integration-attempt" ? [record.attempt] : []).filter((attempt: any) => String(attempt?.attemptId).includes(":entry:")); assert.equal(new Set(entryReceipts.map((attempt: any) => attempt.attemptId)).size >= 1, true);
    await new Promise(resolve => setImmediate(resolve)); assert.deepEqual(simulator.store.regionState(region).dynamodbIntegrationAttempts, {}, "terminal DynamoDB receipts are released"); assert.equal((simulator.eventbridge as any).deliveries.integrationAttempts.size, 0, "terminal EventBridge receipt trees are released"); assert.deepEqual(Object.keys((await (simulator.sns as any).storage.snapshot()).integrationAttempts), [], "terminal SNS receipts are released"); for (const queueArn of [`arn:aws:sqs:${region}:000000000000:attempt-work`, `arn:aws:sqs:${region}:000000000000:attempt-before-dispatch`]) assert.deepEqual(Object.keys((await (simulator.sqs as any).storage.readQueue(queueArn)).integrationAttempts ?? {}), [], `terminal SQS receipts are released for ${queueArn}`); const executionStore = (simulator.stepfunctions as any).executionStore; for (const execution of Object.values(simulator.store.regionState(region).stepFunctions.executions) as any[]) for (const journal of Object.values(execution.taskJournal ?? {}) as any[]) if (journal.service === "LAMBDA" && ["SUCCEEDED", "FAILED", "AMBIGUOUS"].includes(journal.status)) assert.equal(executionStore.integrationAttempt(journal.taskId), undefined, "terminal Lambda receipts are released");
  } finally { if (api) destroy(api); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("SFN-03 optimized Lambda and SNS callbacks redact tokens and resume success or failure after restart", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-sfn03-callback-forms-")); const tokenFile = join(root, "lambda-token.json"); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, authMode: "off", cdkBootstrap: false }); let api: ReturnType<typeof clients> | undefined;
  try {
    await simulator.start(); api = clients(simulator); const workflowRole = await api.iam.send(new CreateRoleCommand({ RoleName: "callback-forms-workflow", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "states.amazonaws.com" }, Action: "sts:AssumeRole" }] }) })); const lambdaRole = await api.iam.send(new CreateRoleCommand({ RoleName: "callback-forms-lambda", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "lambda.amazonaws.com" }, Action: "sts:AssumeRole" }] }) }));
    const fn = await api.lambda.send(new CreateFunctionCommand({ FunctionName: "callback-token-sink", Runtime: "nodejs22.x", Handler: "index.handler", Role: lambdaRole.Role!.Arn!, Environment: { Variables: { TOKEN_FILE: tokenFile } }, Code: { ZipFile: createZip([{ name: "index.js", content: "const { writeFileSync } = require('node:fs'); exports.handler = async event => { writeFileSync(process.env.TOKEN_FILE, JSON.stringify(event)); return { accepted: true }; };" }]) } }));
    const callbackQueueUrl = (await api.sqs.send(new CreateQueueCommand({ QueueName: "sns-callback-tokens" }))).QueueUrl!; const callbackQueueArn = `arn:aws:sqs:${region}:000000000000:sns-callback-tokens`; const topicArn = (await api.sns.send(new CreateTopicCommand({ Name: "callback-token-topic" }))).TopicArn!; await api.sqs.send(new SetQueueAttributesCommand({ QueueUrl: callbackQueueUrl, Attributes: { Policy: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "sns.amazonaws.com" }, Action: "sqs:SendMessage", Resource: callbackQueueArn, Condition: { ArnEquals: { "aws:SourceArn": topicArn } } }] }) } })); await api.sns.send(new SubscribeCommand({ TopicArn: topicArn, Protocol: "sqs", Endpoint: callbackQueueArn, Attributes: { RawMessageDelivery: "true" } }));
    const lambdaMachine = await api.sfn.send(new CreateStateMachineCommand({ name: "lambda-callback-form", roleArn: workflowRole.Role!.Arn!, definition: JSON.stringify({ StartAt: "Invoke", States: { Invoke: { Type: "Task", Resource: "arn:aws:states:::lambda:invoke.waitForTaskToken", Parameters: { FunctionName: fn.FunctionArn, Payload: { "token.$": "$$.Task.Token" } }, HeartbeatSeconds: 30, TimeoutSeconds: 120, End: true } } }) })); const snsMachine = await api.sfn.send(new CreateStateMachineCommand({ name: "sns-callback-form", roleArn: workflowRole.Role!.Arn!, definition: JSON.stringify({ StartAt: "Publish", States: { Publish: { Type: "Task", Resource: "arn:aws:states:::sns:publish.waitForTaskToken", Parameters: { TopicArn: topicArn, "Message.$": "$$.Task.Token" }, HeartbeatSeconds: 30, TimeoutSeconds: 120, End: true } } }) }));
    const lambdaExecution = await api.sfn.send(new StartExecutionCommand({ stateMachineArn: lambdaMachine.stateMachineArn! })); const snsExecution = await api.sfn.send(new StartExecutionCommand({ stateMachineArn: snsMachine.stateMachineArn! })); let lambdaToken = ""; for (let index = 0; index < 400 && !lambdaToken; index++) { try { lambdaToken = JSON.parse(await readFile(tokenFile, "utf8")).token; } catch { await new Promise(resolve => setTimeout(resolve, 5)); } } assert(lambdaToken); const snsToken = (await waitForMessage(api.sqs, callbackQueueUrl, api.sfn, snsExecution.executionArn!)).Body!; assert(snsToken.length > 40);
    await api.sfn.send(new SendTaskHeartbeatCommand({ taskToken: lambdaToken })); await api.sfn.send(new SendTaskHeartbeatCommand({ taskToken: snsToken })); let callbackDispatchesDurable = false; for (let index = 0; index < 400 && !callbackDispatchesDurable; index++) { const executions = simulator.store.regionState(region).stepFunctions.executions; callbackDispatchesDurable = [lambdaExecution.executionArn!, snsExecution.executionArn!].every(arn => Object.values(executions[arn]?.callbackTasks ?? {}).some(task => task.status === "PENDING") && Object.values(executions[arn]?.taskJournal ?? {}).some(journal => journal.status === "SUCCEEDED")); if (!callbackDispatchesDurable) await new Promise(resolve => setTimeout(resolve, 5)); } assert(callbackDispatchesDurable, "both callback handoffs are durable before restart"); const stateText = await readFile(join(root, "state.json"), "utf8"); assert(!stateText.includes(lambdaToken)); assert(!stateText.includes(snsToken)); const executionDirectory = join(root, "data", "step-functions", "000000000000", region); for (const file of await readdir(executionDirectory)) { const contents = await readFile(join(executionDirectory, file)); assert(!contents.includes(Buffer.from(lambdaToken)), `Lambda callback token is absent from ${file}`); assert(!contents.includes(Buffer.from(snsToken)), `SNS callback token is absent from ${file}`); }
    destroy(api); api = undefined; await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, authMode: "off", cdkBootstrap: false }); await simulator.start(); api = clients(simulator); await api.sfn.send(new SendTaskHeartbeatCommand({ taskToken: lambdaToken })); await api.sfn.send(new SendTaskHeartbeatCommand({ taskToken: snsToken })); await api.sfn.send(new SendTaskFailureCommand({ taskToken: lambdaToken, error: "LambdaCallbackRejected", cause: "worker rejected callback" })); await api.sfn.send(new SendTaskSuccessCommand({ taskToken: snsToken, output: JSON.stringify({ accepted: true }) })); const lambdaResult = await terminal(api.sfn, lambdaExecution.executionArn!); const snsResult = await terminal(api.sfn, snsExecution.executionArn!); assert.equal(lambdaResult.status, "FAILED"); assert.equal(lambdaResult.error, "LambdaCallbackRejected"); assert.equal(snsResult.status, "SUCCEEDED"); assert.deepEqual(JSON.parse(snsResult.output!), { accepted: true }); await assert.rejects(api.sfn.send(new SendTaskSuccessCommand({ taskToken: snsToken, output: "{}" })), (error: any) => error.name === "TaskDoesNotExist");
  } finally { if (api) destroy(api); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("SFN-03 nested request and sync admission recover, cancel children, and reject recursion or excess depth", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-sfn03-nested-recovery-")); const clock = new TestClock(Date.now()); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, clock, authMode: "off", cdkBootstrap: false }); let api: ReturnType<typeof clients> | undefined;
  const settle = async (sfn: SFNClient, executionArn: string) => { for (let index = 0; index < 600; index++) { const result = await sfn.send(new DescribeExecutionCommand({ executionArn })); if (result.status !== "RUNNING") return result; clock.advance(1_000); await new Promise(resolve => setImmediate(resolve)); } throw new Error("nested execution did not settle"); };
  const restart = async () => { if (api) { destroy(api); api = undefined; } await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, clock, authMode: "off", cdkBootstrap: false }); await simulator.start(); api = clients(simulator); };
  try {
    await simulator.start(); api = clients(simulator); const role = await api.iam.send(new CreateRoleCommand({ RoleName: "nested-recovery-role", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "states.amazonaws.com" }, Action: "sts:AssumeRole" }] }) }));
    const child = await api.sfn.send(new CreateStateMachineCommand({ name: "nested-recovery-child", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Wait", States: { Wait: { Type: "Wait", Seconds: 30, Next: "Done" }, Done: { Type: "Succeed" } } }) }));
    const requestParent = await api.sfn.send(new CreateStateMachineCommand({ name: "nested-request-parent", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Child", States: { Child: { Type: "Task", Resource: "arn:aws:states:::states:startExecution", Parameters: { StateMachineArn: child.stateMachineArn, Input: { mode: "request" } }, End: true } } }) }));
    let admissionLost = false; const startExecution = simulator.stepfunctions.StartExecution.bind(simulator.stepfunctions); (simulator.stepfunctions as any).StartExecution = async (input: any) => { const result = await startExecution(input); if (Array.isArray(input.__lineage) && !admissionLost) { admissionLost = true; simulator.stepfunctions.beginShutdown(); throw new Error("fault after nested StartExecution durable admission"); } return result; }; const requestExecution = await api.sfn.send(new StartExecutionCommand({ stateMachineArn: requestParent.stateMachineArn! })); for (let index = 0; index < 400 && !admissionLost; index++) await new Promise(resolve => setTimeout(resolve, 5)); assert(admissionLost); await api.sfn.send(new DeleteStateMachineCommand({ stateMachineArn: child.stateMachineArn! })); await restart(); const requestResult = await settle(api!.sfn, requestExecution.executionArn!); assert.equal(requestResult.status, "SUCCEEDED", `${requestResult.error}: ${requestResult.cause}`); const requestChildren = Object.values(simulator.store.regionState(region).stepFunctions.executions).filter(execution => execution.stateMachineArn === child.stateMachineArn); assert.equal(requestChildren.length, 1, "recovery reconciles the one durably admitted child after target deletion"); assert.deepEqual(requestChildren[0].lineage, [requestParent.stateMachineArn, child.stateMachineArn], "nested lineage is exact"); await api!.sfn.send(new CreateStateMachineCommand({ name: "nested-recovery-child", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Wait", States: { Wait: { Type: "Wait", Seconds: 30, Next: "Done" }, Done: { Type: "Succeed" } } }) }));

    const syncParent = await api!.sfn.send(new CreateStateMachineCommand({ name: "nested-sync-parent", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Child", States: { Child: { Type: "Task", Resource: "arn:aws:states:::states:startExecution.sync", Parameters: { StateMachineArn: child.stateMachineArn, Input: { mode: "sync" } }, End: true } } }) })); const syncExecution = await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: syncParent.stateMachineArn! })); let syncChildArn = ""; for (let index = 0; index < 400 && !syncChildArn; index++) { syncChildArn = simulator.store.regionState(region).stepFunctions.executions[syncExecution.executionArn!]?.nestedExecutions ? Object.values(simulator.store.regionState(region).stepFunctions.executions[syncExecution.executionArn!].nestedExecutions!)[0]?.executionArn ?? "" : ""; if (!syncChildArn) await new Promise(resolve => setTimeout(resolve, 5)); } assert(syncChildArn); await restart(); const syncResult = await settle(api!.sfn, syncExecution.executionArn!); assert.equal(syncResult.status, "SUCCEEDED", `${syncResult.error}: ${syncResult.cause}`); assert.equal((await api!.sfn.send(new DescribeExecutionCommand({ executionArn: syncChildArn }))).status, "SUCCEEDED");

    const cancelled = await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: syncParent.stateMachineArn!, name: "cancel-parent" })); let cancelledChildArn = ""; for (let index = 0; index < 400 && !cancelledChildArn; index++) { cancelledChildArn = Object.values(simulator.store.regionState(region).stepFunctions.executions[cancelled.executionArn!]?.nestedExecutions ?? {})[0]?.executionArn ?? ""; if (!cancelledChildArn) await new Promise(resolve => setTimeout(resolve, 5)); } assert(cancelledChildArn); await api!.sfn.send(new StopExecutionCommand({ executionArn: cancelled.executionArn!, error: "CancelledByTest" })); assert.equal((await api!.sfn.send(new DescribeExecutionCommand({ executionArn: cancelled.executionArn! }))).status, "ABORTED"); assert.equal((await api!.sfn.send(new DescribeExecutionCommand({ executionArn: cancelledChildArn }))).status, "ABORTED");

    const selfArn = `arn:aws:states:${region}:000000000000:stateMachine:nested-self`; const self = await api!.sfn.send(new CreateStateMachineCommand({ name: "nested-self", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Again", States: { Again: { Type: "Task", Resource: "arn:aws:states:::states:startExecution.sync", Parameters: { StateMachineArn: selfArn }, End: true } } }) })); const selfResult = await settle(api!.sfn, (await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: self.stateMachineArn! }))).executionArn!); assert.equal(selfResult.status, "FAILED"); assert.match(`${selfResult.error} ${selfResult.cause}`, /recursion|ExceedToleratedFailureThreshold/i);

    const depthNames = Array.from({ length: 33 }, (_value, index) => `nested-depth-${index}`); for (const [index, name] of depthNames.entries()) { const nextArn = `arn:aws:states:${region}:000000000000:stateMachine:${depthNames[index + 1]}`; const definition = index === depthNames.length - 1 ? { StartAt: "Done", States: { Done: { Type: "Succeed" } } } : { StartAt: "Next", States: { Next: { Type: "Task", Resource: "arn:aws:states:::states:startExecution.sync", Parameters: { StateMachineArn: nextArn }, End: true } } }; await api!.sfn.send(new CreateStateMachineCommand({ name, roleArn: role.Role!.Arn!, definition: JSON.stringify(definition) })); } const depthResult = await settle(api!.sfn, (await api!.sfn.send(new StartExecutionCommand({ stateMachineArn: `arn:aws:states:${region}:000000000000:stateMachine:${depthNames[0]}` }))).executionArn!); assert.equal(depthResult.status, "FAILED"); assert.match(`${depthResult.error} ${depthResult.cause}`, /depth|recursion|ExceedToleratedFailureThreshold|ExecutionFailed/i);
  } finally { if (api) destroy(api); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});

test("SFN-03 nested callback materializes its token only at the encrypted downstream boundary", async () => {
  const root = await mkdtemp(join(tmpdir(), "stacksim-sfn03-nested-callback-")); let simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, authMode: "off", cdkBootstrap: false }); let api: ReturnType<typeof clients> | undefined;
  try {
    await simulator.start(); api = clients(simulator); const role = await api.iam.send(new CreateRoleCommand({ RoleName: "nested-callback-role", AssumeRolePolicyDocument: JSON.stringify({ Version: "2012-10-17", Statement: [{ Effect: "Allow", Principal: { Service: "states.amazonaws.com" }, Action: "sts:AssumeRole" }] }) })); const queueUrl = (await api.sqs.send(new CreateQueueCommand({ QueueName: "nested-callback-token" }))).QueueUrl!;
    const child = await api.sfn.send(new CreateStateMachineCommand({ name: "nested-callback-child", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Deliver", States: { Deliver: { Type: "Task", Resource: "arn:aws:states:::sqs:sendMessage", Parameters: { QueueUrl: queueUrl, "MessageBody.$": "$.token" }, End: true } } }) }));
    const parent = await api.sfn.send(new CreateStateMachineCommand({ name: "nested-callback-parent", roleArn: role.Role!.Arn!, definition: JSON.stringify({ StartAt: "Child", States: { Child: { Type: "Task", Resource: "arn:aws:states:::states:startExecution.waitForTaskToken", Parameters: { StateMachineArn: child.stateMachineArn, Input: { "token.$": "$$.Task.Token" } }, End: true } } }) }));
    const started = await api.sfn.send(new StartExecutionCommand({ stateMachineArn: parent.stateMachineArn! })); const message = await waitForMessage(api.sqs, queueUrl, api.sfn, started.executionArn!); const token = message.Body!; assert(token.length > 40); const executionDirectory = join(root, "data", "step-functions", "000000000000", region); for (const file of await readdir(executionDirectory)) { const contents = await readFile(join(executionDirectory, file)); assert(!contents.includes(Buffer.from(token)), `nested callback token is absent from ${file}`); }
    const childExecution = (await api.sfn.send(new ListExecutionsCommand({ stateMachineArn: child.stateMachineArn! }))).executions?.[0]; assert(childExecution); const childHistory = await api.sfn.send(new GetExecutionHistoryCommand({ executionArn: childExecution!.executionArn!, maxResults: 1000 })); assert(!JSON.stringify(childHistory).includes(token));
    destroy(api); api = undefined; await simulator.stop(); simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region, authMode: "off", cdkBootstrap: false }); await simulator.start(); api = clients(simulator); await api.sfn.send(new SendTaskSuccessCommand({ taskToken: token, output: JSON.stringify({ nested: "done" }) })); const completed = await terminal(api.sfn, started.executionArn!); assert.equal(completed.status, "SUCCEEDED"); assert.deepEqual(JSON.parse(completed.output!), { nested: "done" });
  } finally { if (api) destroy(api); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true }); }
});
