import { rest } from "../api-client.js";
import { emptyState, escapeHtml, formatDate, pageHeader } from "../components.js";
import { session as ui } from "../state.js";

const sections = [
  ["Develop", [["routes", "Routes"], ["authorization", "Authorization"], ["integrations", "Integrations"], ["cors", "CORS"]]],
  ["Deploy", [["stages", "Stages"]]],
  ["Monitor", [["monitor", "Monitor"]]],
];

const apiHref = (apiId, section = "routes") => `#/apigateway/http-apis/${encodeURIComponent(apiId)}/${section}`;
const lines = value => String(value ?? "").split(/[\n,]/).map(item => item.trim()).filter(Boolean);

function httpNavigation(apiId, active) {
  return `<nav class="http-api-nav" aria-label="HTTP API navigation">${sections.map(([group, items]) => `<div class="http-api-nav-group"><div class="http-api-nav-label">${group}</div>${items.map(([key, label]) => `<a href="${apiHref(apiId, key)}" class="${active === key ? "active" : ""}" ${active === key ? 'aria-current="page"' : ""}>${label}</a>`).join("")}</div>`).join("")}</nav>`;
}

function detailHeader(api, actions = "") {
  return pageHeader(api.name, `HTTP API · ${escapeHtml(api.apiId)}`, `<button class="button" data-action="edit-http-api">Edit</button><button class="button danger" data-action="delete-http-api">Delete</button>${actions}`);
}

export function createHttpApiModal(context) {
  const { showModal, toast } = context;
  showModal("Create HTTP API", `<div class="alert info"><strong>Build an HTTP API</strong><br>Create a low-latency API with route-based Lambda or HTTP proxy integrations. Add an integration now for a managed $default stage, or start empty.</div><div class="field"><label>API name</label><input name="name" required placeholder="orders-http-api"></div><div class="field"><label>Description <span class="muted small">– optional</span></label><textarea name="description"></textarea></div><div class="field"><label>Quick-create integration target <span class="muted small">– optional</span></label><input name="target" class="mono" placeholder="Lambda ARN or leave empty"><span class="hint">A target creates a managed route and auto-deploying $default stage.</span></div><div class="field"><label>Route key</label><input name="routeKey" class="mono" value="$default" placeholder="GET /orders"></div><div class="field"><label>CORS allowed origins <span class="muted small">– optional</span></label><input name="origins" placeholder="https://app.example, https://admin.example"></div><label class="field"><span><input type="checkbox" name="disableEndpoint" value="true"> Disable the default execute-api endpoint</span></label><div class="field"><label>Tags (JSON)</label><textarea name="tags">{}</textarea></div>`, "Create HTTP API", async data => { const target = String(data.get("target") || "").trim(); const origins = lines(data.get("origins")); const api = await rest("/v2/apis", "POST", { name: data.get("name"), protocolType: "HTTP", description: data.get("description") || undefined, ...(target ? { target, routeKey: data.get("routeKey") || "$default" } : {}), ...(origins.length ? { corsConfiguration: { allowOrigins: origins, allowMethods: ["*"] } } : {}), disableExecuteApiEndpoint: data.get("disableEndpoint") === "true", tags: JSON.parse(String(data.get("tags") || "{}")) }); toast("HTTP API created"); location.hash = apiHref(api.apiId); }, true);
}

export async function httpApiDetail(id, section, context) {
  const { main, setChrome, showModal, toast, confirmDeletion, bindTableFilter, route } = context; const active = new Set(sections.flatMap(([, items]) => items.map(([key]) => key))).has(section) ? section : "routes";
  setChrome("apigateway", ["API Gateway", "APIs", id]);
  const [api, routesResult, integrationsResult, authorizersResult, stagesResult, deploymentsResult] = await Promise.all([rest(`/v2/apis/${id}`), rest(`/v2/apis/${id}/routes?maxResults=500`), rest(`/v2/apis/${id}/integrations?maxResults=500`), rest(`/v2/apis/${id}/authorizers?maxResults=500`), rest(`/v2/apis/${id}/stages?maxResults=500`), rest(`/v2/apis/${id}/deployments?maxResults=500`)]); const routes = routesResult.items ?? []; const integrations = integrationsResult.items ?? []; const authorizers = authorizersResult.items ?? []; const stages = stagesResult.items ?? []; const deployments = deploymentsResult.items ?? [];
  const view = active === "routes" ? routesView(routes, integrations, authorizers) : active === "authorization" ? authorizationView(authorizers, routes) : active === "integrations" ? integrationsView(integrations, routes) : active === "cors" ? corsView(api) : active === "stages" ? stagesView(stages, deployments) : monitorView(api, stages, routes);
  main.innerHTML = `<div class="page-width">${detailHeader(api, `<button class="button primary" data-action="deploy-http-api">Deploy</button>`)}<div class="http-api-shell">${httpNavigation(id, active)}<div class="http-api-content">${view}</div></div></div>`;
  bindTableFilter(); bindCommon(); if (active === "routes") bindRoutes(); else if (active === "authorization") bindAuthorization(); else if (active === "integrations") bindIntegrations(); else if (active === "cors") bindCors(); else if (active === "stages") bindStages();

  function routesView(values, targets, auth) {
    const integrationName = target => targets.find(value => `integrations/${value.integrationId}` === target)?.description || target?.split("/").at(-1) || "Not attached"; const authorizationName = routeValue => routeValue.authorizationType === "CUSTOM" || routeValue.authorizationType === "JWT" ? auth.find(value => value.authorizerId === routeValue.authorizerId)?.name || routeValue.authorizationType : routeValue.authorizationType;
    return `<section class="card"><div class="card-header"><div><h2>Routes <span class="muted">(${values.length})</span></h2><p class="muted small">API Gateway evaluates exact routes before greedy routes and $default.</p></div><button class="button primary" data-action="create-http-route">Create</button></div><div class="toolbar"><label class="filter"><span>⌕</span><input data-filter-table placeholder="Find routes"></label></div><div class="table-wrap">${values.length ? `<table><thead><tr><th>Route key</th><th>Authorization</th><th>Integration</th><th>Route ID</th><th>Actions</th></tr></thead><tbody>${values.map(value => `<tr data-search-row="${escapeHtml(`${value.routeKey} ${value.authorizationType}`.toLowerCase())}"><td class="mono"><strong>${escapeHtml(value.routeKey)}</strong>${value.apiGatewayManaged ? ' <span class="muted small">Managed</span>' : ""}</td><td>${escapeHtml(authorizationName(value))}</td><td>${escapeHtml(integrationName(value.target))}</td><td class="mono">${escapeHtml(value.routeId)}</td><td><div class="actions"><button class="button" data-edit-http-route="${escapeHtml(value.routeId)}">Edit</button><button class="button danger" data-delete-http-route="${escapeHtml(value.routeId)}">Delete</button></div></td></tr>`).join("")}</tbody></table>` : emptyState("⇢", "No routes", "Create a route key and connect it to an integration.", '<button class="button primary" data-action="create-http-route">Create route</button>')}</div></section>`;
  }

  function routeFields(value) { return `<div class="field"><label>Route key</label><input name="routeKey" required class="mono" value="${escapeHtml(value?.routeKey || "GET /")}" placeholder="GET /orders/{id}"><span class="hint">Use METHOD /path, ANY /path, or $default.</span></div><div class="field"><label>Integration</label><select name="target"><option value="">Not attached</option>${integrations.map(integration => `<option value="integrations/${escapeHtml(integration.integrationId)}" ${value?.target === `integrations/${integration.integrationId}` ? "selected" : ""}>${escapeHtml(integration.description || integration.integrationUri)} · ${escapeHtml(integration.integrationId)}</option>`).join("")}</select></div><div class="field"><label>Authorization</label><select name="authorizationType"><option ${value?.authorizationType === "NONE" ? "selected" : ""}>NONE</option><option ${value?.authorizationType === "AWS_IAM" ? "selected" : ""}>AWS_IAM</option><option value="CUSTOM" ${value?.authorizationType === "CUSTOM" ? "selected" : ""}>Lambda authorizer</option><option value="JWT" ${value?.authorizationType === "JWT" ? "selected" : ""}>JWT authorizer</option></select></div><div class="field"><label>Authorizer</label><select name="authorizerId"><option value="">None</option>${authorizers.map(authorizer => `<option value="${escapeHtml(authorizer.authorizerId)}" ${value?.authorizerId === authorizer.authorizerId ? "selected" : ""}>${escapeHtml(authorizer.name)} · ${escapeHtml(authorizer.authorizerType)}</option>`).join("")}</select></div><div class="field"><label>Authorization scopes</label><input name="scopes" value="${escapeHtml((value?.authorizationScopes ?? []).join(", "))}" placeholder="orders:read, orders:write"></div>`; }

  function bindRoutes() {
    const open = value => showModal(value ? `Edit route · ${value.routeKey}` : "Create route", routeFields(value), value ? "Save" : "Create", async data => { const body = { routeKey: data.get("routeKey"), target: data.get("target") || undefined, authorizationType: data.get("authorizationType"), authorizerId: data.get("authorizerId") || undefined, authorizationScopes: lines(data.get("scopes")) }; await rest(value ? `/v2/apis/${id}/routes/${value.routeId}` : `/v2/apis/${id}/routes`, value ? "PATCH" : "POST", body); toast(`Route ${value ? "updated" : "created"}`); }); document.querySelectorAll('[data-action="create-http-route"]').forEach(button => button.addEventListener("click", () => open())); document.querySelectorAll("[data-edit-http-route]").forEach(button => button.addEventListener("click", () => open(routes.find(value => value.routeId === button.dataset.editHttpRoute)))); document.querySelectorAll("[data-delete-http-route]").forEach(button => button.addEventListener("click", () => { const value = routes.find(routeValue => routeValue.routeId === button.dataset.deleteHttpRoute); if (value) confirmDeletion(value.routeKey, `Delete route ${value.routeKey}? Auto-deploy stages receive a new deployment.`, async () => { await rest(`/v2/apis/${id}/routes/${value.routeId}`, "DELETE"); toast("Route deleted"); }); }));
  }

  function authorizationView(values, routeValues) { const usage = authorizerId => routeValues.filter(value => value.authorizerId === authorizerId).length; return `<div class="alert info"><strong>Cognito JWT integration</strong><br>For an authoritative local user pool, configure a JWT authorizer with the exact issuer shown on the <a href="#/cognito/user-pools">Cognito pool overview</a> and one or more app-client IDs as audiences. Resolution is in process and never requires the loopback JWKS URL or network access. If both <span class="mono">aud</span> and <span class="mono">client_id</span> are present, <span class="mono">aud</span> takes precedence.</div><section class="card"><div class="card-header"><div><h2>Authorization <span class="muted">(${values.length})</span></h2><p class="muted small">Manage Lambda request and JWT authorizers, then attach them to routes.</p></div><button class="button primary" data-action="create-http-authorizer">Create</button></div><div class="table-wrap">${values.length ? `<table><thead><tr><th>Name</th><th>Type</th><th>Identity source</th><th>Cache TTL</th><th>Routes</th><th>Actions</th></tr></thead><tbody>${values.map(value => `<tr><td><strong>${escapeHtml(value.name)}</strong></td><td>${escapeHtml(value.authorizerType)}</td><td class="mono">${escapeHtml((value.identitySource ?? []).join(", "))}</td><td>${value.authorizerResultTtlInSeconds ?? 0} sec</td><td>${usage(value.authorizerId)}</td><td><div class="actions"><button class="button" data-edit-http-authorizer="${escapeHtml(value.authorizerId)}">Edit</button><button class="button danger" data-delete-http-authorizer="${escapeHtml(value.authorizerId)}">Delete</button></div></td></tr>`).join("")}</tbody></table>` : emptyState("◆", "No authorizers", "Create a Lambda request authorizer or JWT authorizer.", '<button class="button primary" data-action="create-http-authorizer">Create authorizer</button>')}</div></section>`; }

  function authorizerFields(value) { return `<div class="field"><label>Name</label><input name="name" required value="${escapeHtml(value?.name || "")}"></div><div class="field"><label>Authorizer type</label><select name="type"><option value="REQUEST" ${value?.authorizerType === "REQUEST" ? "selected" : ""}>Lambda</option><option value="JWT" ${value?.authorizerType === "JWT" ? "selected" : ""}>JWT</option></select></div><div class="field"><label>Identity source</label><input name="identity" class="mono" value="${escapeHtml((value?.identitySource ?? ["$request.header.Authorization"]).join(", "))}"></div><h3>Lambda authorizer</h3><div class="field"><label>Authorizer URI</label><input name="uri" class="mono" value="${escapeHtml(value?.authorizerUri || "")}" placeholder="arn:aws:apigateway:region:lambda:path/2015-03-31/functions/.../invocations"></div><div class="field-row"><div class="field"><label>Payload format version</label><select name="payload"><option ${value?.authorizerPayloadFormatVersion === "1.0" ? "selected" : ""}>1.0</option><option ${value?.authorizerPayloadFormatVersion !== "1.0" ? "selected" : ""}>2.0</option></select></div><div class="field"><label>Cache TTL (seconds)</label><input name="ttl" type="number" min="0" max="3600" value="${value?.authorizerResultTtlInSeconds ?? 300}"></div></div><label class="field"><span><input type="checkbox" name="simple" value="true" ${value?.enableSimpleResponses ? "checked" : ""}> Enable simple responses</span></label><h3>JWT authorizer</h3><div class="alert info">Cognito: copy the exact pool issuer and use app-client IDs as audiences. ID and access tokens can both pass generic JWT validation; add route scopes when you require access-token-style authorization.</div><div class="field"><label>Issuer URL</label><input name="issuer" value="${escapeHtml(value?.jwtConfiguration?.issuer || "")}" placeholder="https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_AbCdEf123"></div><div class="field"><label>Audience</label><input name="audience" value="${escapeHtml((value?.jwtConfiguration?.audience ?? []).join(", "))}" placeholder="app-client-id"></div>`; }

  function bindAuthorization() { const open = value => showModal(value ? `Edit authorizer · ${value.name}` : "Create authorizer", authorizerFields(value), value ? "Save" : "Create", async data => { const type = String(data.get("type")); const body = { name: data.get("name"), authorizerType: type, identitySource: lines(data.get("identity")), authorizerResultTtlInSeconds: Number(data.get("ttl")), ...(type === "REQUEST" ? { authorizerUri: data.get("uri"), authorizerPayloadFormatVersion: data.get("payload"), enableSimpleResponses: data.get("simple") === "true" } : { jwtConfiguration: { issuer: data.get("issuer"), audience: lines(data.get("audience")) } }) }; await rest(value ? `/v2/apis/${id}/authorizers/${value.authorizerId}` : `/v2/apis/${id}/authorizers`, value ? "PATCH" : "POST", body); toast(`Authorizer ${value ? "updated" : "created"}`); }); document.querySelectorAll('[data-action="create-http-authorizer"]').forEach(button => button.addEventListener("click", () => open())); document.querySelectorAll("[data-edit-http-authorizer]").forEach(button => button.addEventListener("click", () => open(authorizers.find(value => value.authorizerId === button.dataset.editHttpAuthorizer)))); document.querySelectorAll("[data-delete-http-authorizer]").forEach(button => button.addEventListener("click", () => { const value = authorizers.find(item => item.authorizerId === button.dataset.deleteHttpAuthorizer); if (value) confirmDeletion(value.name, `Delete authorizer ${value.name}? Remove it from routes first.`, async () => { await rest(`/v2/apis/${id}/authorizers/${value.authorizerId}`, "DELETE"); toast("Authorizer deleted"); }); })); }

  function integrationsView(values, routeValues) { const usage = integrationId => routeValues.filter(value => value.target === `integrations/${integrationId}`).length; return `<section class="card"><div class="card-header"><div><h2>Integrations <span class="muted">(${values.length})</span></h2><p class="muted small">Connect routes to Lambda functions or public HTTP endpoints.</p></div><button class="button primary" data-action="create-http-integration">Create</button></div><div class="toolbar"><label class="filter"><span>⌕</span><input data-filter-table placeholder="Find integrations"></label></div><div class="table-wrap">${values.length ? `<table><thead><tr><th>Integration</th><th>Type</th><th>Payload</th><th>Routes</th><th>Timeout</th><th>Actions</th></tr></thead><tbody>${values.map(value => `<tr data-search-row="${escapeHtml(`${value.description ?? ""} ${value.integrationUri} ${value.integrationType}`.toLowerCase())}"><td><strong>${escapeHtml(value.description || value.integrationId)}</strong><div class="muted small mono integration-uri">${escapeHtml(value.integrationUri)}</div></td><td>${escapeHtml(value.integrationType)}</td><td>${escapeHtml(value.payloadFormatVersion)}</td><td>${usage(value.integrationId)}</td><td>${value.timeoutInMillis} ms</td><td><div class="actions"><button class="button" data-edit-http-integration="${escapeHtml(value.integrationId)}">Edit</button><button class="button danger" data-delete-http-integration="${escapeHtml(value.integrationId)}">Delete</button></div></td></tr>`).join("")}</tbody></table>` : emptyState("⌁", "No integrations", "Create a Lambda proxy or HTTP proxy integration.", '<button class="button primary" data-action="create-http-integration">Create integration</button>')}</div></section>`; }

  function integrationFields(value) { return `<div class="field"><label>Integration type</label><select name="type"><option value="AWS_PROXY" ${value?.integrationType === "AWS_PROXY" ? "selected" : ""}>Lambda function</option><option value="HTTP_PROXY" ${value?.integrationType === "HTTP_PROXY" ? "selected" : ""}>HTTP endpoint</option></select></div><div class="field"><label>Integration target</label><input name="uri" required class="mono" value="${escapeHtml(value?.integrationUri || "")}" placeholder="Lambda ARN or https://service.example/path"></div><div class="field"><label>Description</label><input name="description" value="${escapeHtml(value?.description || "")}"></div><div class="field-row"><div class="field"><label>Integration method</label><select name="method">${["ANY", "GET", "POST", "PUT", "PATCH", "DELETE"].map(method => `<option ${value?.integrationMethod === method ? "selected" : ""}>${method}</option>`).join("")}</select></div><div class="field"><label>Payload format version</label><select name="payload"><option ${value?.payloadFormatVersion === "1.0" ? "selected" : ""}>1.0</option><option ${value?.payloadFormatVersion !== "1.0" ? "selected" : ""}>2.0</option></select></div></div><div class="field"><label>Timeout (milliseconds)</label><input name="timeout" type="number" min="50" max="30000" value="${value?.timeoutInMillis ?? 30000}"></div><div class="field"><label>Request parameter mappings (JSON)</label><textarea name="requestParameters" class="code-editor">${escapeHtml(JSON.stringify(value?.requestParameters ?? {}, null, 2))}</textarea></div><div class="field"><label>Response parameter mappings (JSON)</label><textarea name="responseParameters" class="code-editor">${escapeHtml(JSON.stringify(value?.responseParameters ?? {}, null, 2))}</textarea></div>`; }

  function bindIntegrations() { const open = value => showModal(value ? `Edit integration · ${value.description || value.integrationId}` : "Create integration", integrationFields(value), value ? "Save" : "Create", async data => { const type = String(data.get("type")); await rest(value ? `/v2/apis/${id}/integrations/${value.integrationId}` : `/v2/apis/${id}/integrations`, value ? "PATCH" : "POST", { integrationType: type, integrationUri: data.get("uri"), description: data.get("description") || undefined, integrationMethod: data.get("method"), payloadFormatVersion: type === "HTTP_PROXY" ? "1.0" : data.get("payload"), timeoutInMillis: Number(data.get("timeout")), requestParameters: JSON.parse(String(data.get("requestParameters") || "{}")), responseParameters: JSON.parse(String(data.get("responseParameters") || "{}")) }); toast(`Integration ${value ? "updated" : "created"}`); }); document.querySelectorAll('[data-action="create-http-integration"]').forEach(button => button.addEventListener("click", () => open())); document.querySelectorAll("[data-edit-http-integration]").forEach(button => button.addEventListener("click", () => open(integrations.find(value => value.integrationId === button.dataset.editHttpIntegration)))); document.querySelectorAll("[data-delete-http-integration]").forEach(button => button.addEventListener("click", () => { const value = integrations.find(item => item.integrationId === button.dataset.deleteHttpIntegration); if (value) confirmDeletion(value.description || value.integrationId, "Delete this integration? Remove it from routes first.", async () => { await rest(`/v2/apis/${id}/integrations/${value.integrationId}`, "DELETE"); toast("Integration deleted"); }); })); }

  function corsView(value) { const cors = value.corsConfiguration ?? {}; return `<section class="card"><div class="card-header"><div><h2>Cross-origin resource sharing</h2><p class="muted small">API Gateway answers preflight requests and replaces backend CORS headers.</p></div>${value.corsConfiguration ? '<button class="button danger" data-action="delete-http-cors">Clear</button>' : ""}</div><form id="http-cors-form" class="card-body"><div class="field"><label>Access-Control-Allow-Origin</label><textarea name="origins" placeholder="https://app.example">${escapeHtml((cors.allowOrigins ?? []).join("\n"))}</textarea></div><div class="field"><label>Access-Control-Allow-Headers</label><input name="headers" value="${escapeHtml((cors.allowHeaders ?? []).join(", "))}"></div><div class="field"><label>Access-Control-Allow-Methods</label><input name="methods" value="${escapeHtml((cors.allowMethods ?? []).join(", "))}" placeholder="GET, POST, OPTIONS"></div><div class="field"><label>Access-Control-Expose-Headers</label><input name="expose" value="${escapeHtml((cors.exposeHeaders ?? []).join(", "))}"></div><div class="field-row"><div class="field"><label>Max age (seconds)</label><input name="maxAge" type="number" min="0" max="86400" value="${cors.maxAge ?? ""}"></div><label class="field checkbox-label"><input type="checkbox" name="credentials" value="true" ${cors.allowCredentials ? "checked" : ""}> Allow credentials</label></div><div class="actions"><button class="button primary" type="submit">Save</button></div></form></section>`; }
  function bindCors() { document.querySelector("#http-cors-form")?.addEventListener("submit", async event => { event.preventDefault(); const data = new FormData(event.currentTarget); const origins = lines(data.get("origins")); if (data.get("credentials") === "true" && origins.includes("*")) throw new Error("Wildcard origins cannot be combined with credentials"); await rest(`/v2/apis/${id}`, "PATCH", { corsConfiguration: { allowOrigins: origins, allowHeaders: lines(data.get("headers")), allowMethods: lines(data.get("methods")), exposeHeaders: lines(data.get("expose")), ...(String(data.get("maxAge") || "") ? { maxAge: Number(data.get("maxAge")) } : {}), allowCredentials: data.get("credentials") === "true" } }); toast("CORS configuration saved"); route(); }); document.querySelector('[data-action="delete-http-cors"]')?.addEventListener("click", () => confirmDeletion("CORS", "Clear the HTTP API CORS configuration? Backend CORS headers will pass through again.", async () => { await rest(`/v2/apis/${id}/cors`, "DELETE"); toast("CORS configuration cleared"); })); }

  function stagesView(values, deploymentValues) { const deployment = deploymentId => deploymentValues.find(value => value.deploymentId === deploymentId); return `<section class="card"><div class="card-header"><div><h2>Stages <span class="muted">(${values.length})</span></h2><p class="muted small">A stage points to an immutable deployment snapshot. Auto-deploy stages track configuration changes.</p></div><button class="button primary" data-action="create-http-stage">Create</button></div><div class="table-wrap">${values.length ? `<table><thead><tr><th>Stage</th><th>Deployment</th><th>Auto-deploy</th><th>Last updated</th><th>Access logging</th><th>Actions</th></tr></thead><tbody>${values.map(value => `<tr><td><strong>${escapeHtml(value.stageName)}</strong>${value.apiGatewayManaged ? ' <span class="muted small">Managed</span>' : ""}</td><td class="mono">${escapeHtml(value.deploymentId || "–")}<div class="muted small">${escapeHtml(deployment(value.deploymentId)?.description || "")}</div></td><td>${value.autoDeploy ? '<span class="status-badge success">On</span>' : "Off"}</td><td>${formatDate(value.lastUpdatedDate)}</td><td>${value.accessLogSettings ? "Enabled" : "Disabled"}</td><td><div class="actions"><button class="button" data-edit-http-stage="${escapeHtml(value.stageName)}">Edit</button><button class="button danger" data-delete-http-stage="${escapeHtml(value.stageName)}">Delete</button></div></td></tr>`).join("")}</tbody></table>` : emptyState("◫", "No stages", "Create a named stage or an auto-deploying $default stage.", '<button class="button primary" data-action="create-http-stage">Create stage</button>')}</div></section>`; }
  function stageFields(value) { return `<div class="field"><label>Stage name</label><input name="name" required value="${escapeHtml(value?.stageName || "")}" placeholder="$default or dev" ${value ? "disabled" : ""}></div><label class="field"><span><input type="checkbox" name="autoDeploy" value="true" ${value?.autoDeploy ? "checked" : ""}> Auto-deploy</span></label><div class="field"><label>Deployment</label><select name="deploymentId"><option value="">None</option>${deployments.map(deployment => `<option value="${escapeHtml(deployment.deploymentId)}" ${value?.deploymentId === deployment.deploymentId ? "selected" : ""}>${escapeHtml(deployment.deploymentId)} · ${escapeHtml(deployment.description || "No description")}</option>`).join("")}</select></div><div class="field"><label>Description</label><input name="description" value="${escapeHtml(value?.description || "")}"></div><div class="field"><label>Stage variables (JSON)</label><textarea name="variables">${escapeHtml(JSON.stringify(value?.stageVariables ?? {}, null, 2))}</textarea></div><h3>Default route settings</h3><div class="field-row"><div class="field"><label>Throttle rate</label><input name="rate" type="number" min="0" value="${value?.defaultRouteSettings?.throttlingRateLimit ?? ""}"></div><div class="field"><label>Throttle burst</label><input name="burst" type="number" min="0" value="${value?.defaultRouteSettings?.throttlingBurstLimit ?? ""}"></div></div><label class="field"><span><input type="checkbox" name="metrics" value="true" ${value?.defaultRouteSettings?.detailedMetricsEnabled ? "checked" : ""}> Enable detailed metrics</span></label><h3>Access logging</h3><div class="field"><label>Log group destination ARN</label><input name="destination" class="mono" value="${escapeHtml(value?.accessLogSettings?.destinationArn || "")}"></div><div class="field"><label>Log format</label><textarea name="format">${escapeHtml(value?.accessLogSettings?.format || "$context.requestId $context.routeKey $context.status $context.responseLength")}</textarea></div>`; }
  function bindStages() { const open = value => showModal(value ? `Edit stage · ${value.stageName}` : "Create stage", stageFields(value), value ? "Save" : "Create", async data => { const settings = { detailedMetricsEnabled: data.get("metrics") === "true", ...(String(data.get("rate") || "") ? { throttlingRateLimit: Number(data.get("rate")) } : {}), ...(String(data.get("burst") || "") ? { throttlingBurstLimit: Number(data.get("burst")) } : {}) }; const destination = String(data.get("destination") || ""); await rest(value ? `/v2/apis/${id}/stages/${encodeURIComponent(value.stageName)}` : `/v2/apis/${id}/stages`, value ? "PATCH" : "POST", { ...(!value ? { stageName: data.get("name") } : {}), description: data.get("description") || undefined, autoDeploy: data.get("autoDeploy") === "true", deploymentId: data.get("deploymentId") || undefined, stageVariables: JSON.parse(String(data.get("variables") || "{}")), defaultRouteSettings: settings, ...(destination ? { accessLogSettings: { destinationArn: destination, format: data.get("format") } } : {}) }); toast(`Stage ${value ? "updated" : "created"}`); }); document.querySelectorAll('[data-action="create-http-stage"]').forEach(button => button.addEventListener("click", () => open())); document.querySelectorAll("[data-edit-http-stage]").forEach(button => button.addEventListener("click", () => open(stages.find(value => value.stageName === button.dataset.editHttpStage)))); document.querySelectorAll("[data-delete-http-stage]").forEach(button => button.addEventListener("click", () => { const value = stages.find(item => item.stageName === button.dataset.deleteHttpStage); if (value) confirmDeletion(value.stageName, `Delete stage ${value.stageName}? Its deployments remain available.`, async () => { await rest(`/v2/apis/${id}/stages/${encodeURIComponent(value.stageName)}`, "DELETE"); toast("Stage deleted"); }); })); }

  function monitorView(value, stageValues, routeValues) { const detailed = stageValues.filter(stage => stage.defaultRouteSettings?.detailedMetricsEnabled || Object.values(stage.routeSettings ?? {}).some(setting => setting.detailedMetricsEnabled)).length; const logged = stageValues.filter(stage => stage.accessLogSettings).length; return `<div class="detail-grid http-monitor-summary"><section class="card"><div class="card-header"><h2>Metrics</h2></div><div class="card-body"><strong class="http-monitor-number">${detailed}</strong><p>of ${stageValues.length} stages have detailed route metrics enabled.</p><a class="button" href="#/cloudwatch/metrics">View CloudWatch metrics</a></div></section><section class="card"><div class="card-header"><h2>Access logs</h2></div><div class="card-body"><strong class="http-monitor-number">${logged}</strong><p>stages write structured request records to CloudWatch Logs.</p><a class="button" href="#/cloudwatch/log-groups">View log groups</a></div></section><section class="card"><div class="card-header"><h2>Configuration</h2></div><div class="card-body"><dl class="key-value"><dt>Routes</dt><dd>${routeValues.length}</dd><dt>Stages</dt><dd>${stageValues.length}</dd><dt>Endpoint</dt><dd class="mono">${escapeHtml(value.apiEndpoint)}</dd></dl></div></section></div><section class="card"><div class="card-header"><div><h2>HTTP API metrics</h2><p class="muted small">Count, 4xx, 5xx, Latency, IntegrationLatency, and DataProcessed publish after local invocations.</p></div></div><div class="card-body"><div class="chart-placeholder" role="img" aria-label="HTTP API metric preview">Invoke a route, then open CloudWatch metrics to graph the resulting series.</div></div></section>`; }

  function bindCommon() {
    document.querySelector('[data-action="delete-http-api"]')?.addEventListener("click", () => confirmDeletion(api.name, `Delete HTTP API ${api.name}? Stages, routes, integrations, deployments, and domain mappings are removed.`, async () => { await rest(`/v2/apis/${id}`, "DELETE"); toast("HTTP API deleted"); location.hash = "#/apigateway/apis"; }));
    document.querySelector('[data-action="edit-http-api"]')?.addEventListener("click", () => showModal("Edit HTTP API", `<div class="field"><label>API name</label><input name="name" value="${escapeHtml(api.name)}" required></div><div class="field"><label>Description</label><textarea name="description">${escapeHtml(api.description || "")}</textarea></div><label class="field"><span><input type="checkbox" name="disableEndpoint" value="true" ${api.disableExecuteApiEndpoint ? "checked" : ""}> Disable the default execute-api endpoint</span></label>`, "Save", async data => { await rest(`/v2/apis/${id}`, "PATCH", { name: data.get("name"), description: data.get("description") || undefined, disableExecuteApiEndpoint: data.get("disableEndpoint") === "true" }); toast("HTTP API updated"); }));
    document.querySelector('[data-action="deploy-http-api"]')?.addEventListener("click", () => { const manual = stages.filter(stage => !stage.autoDeploy); showModal("Deploy HTTP API", `${manual.length ? "" : '<div class="alert info">Create a stage with auto-deploy turned off before making a manual deployment.</div>'}<div class="field"><label>Stage</label><select name="stage" ${manual.length ? "" : "disabled"}>${manual.map(stage => `<option value="${escapeHtml(stage.stageName)}">${escapeHtml(stage.stageName)}</option>`).join("")}</select></div><div class="field"><label>Description</label><input name="description" placeholder="Release description"></div>`, "Deploy", async data => { if (!manual.length) throw new Error("No manual stage is available"); const deployment = await rest(`/v2/apis/${id}/deployments`, "POST", { description: data.get("description") || undefined }); await rest(`/v2/apis/${id}/stages/${encodeURIComponent(String(data.get("stage")))}`, "PATCH", { deploymentId: deployment.deploymentId }); toast("HTTP API deployed"); location.hash = apiHref(id, "stages"); }, true); });
  }
}
