export const EVENTBRIDGE_ACTION_INVENTORY_SOURCE = {
  url: "https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_Operations.html",
  verifiedAt: "2026-08-08",
  protocol: "AWS JSON 1.1",
  targetPrefix: "AWSEvents.",
} as const;

export const EVENTBRIDGE_EVB01_ACTIONS = [
  "CreateEventBus", "DeleteEventBus", "DeleteRule", "DescribeEventBus", "DescribeRule", "DisableRule", "EnableRule",
  "ListEventBuses", "ListRuleNamesByTarget", "ListRules", "ListTagsForResource", "ListTargetsByRule", "PutEvents",
  "PutRule", "PutTargets", "RemoveTargets", "TagResource", "TestEventPattern", "UntagResource",
] as const;

export const EVENTBRIDGE_EVB04_ACTIONS = [
  "CancelReplay", "CreateArchive", "DeleteArchive", "DescribeArchive", "DescribeReplay", "ListArchives", "ListReplays", "StartReplay", "UpdateArchive",
] as const;

export const EVENTBRIDGE_ACTION_INVENTORY = [
  { action: "ActivateEventSource", phase: "EVB-08" },
  { action: "CancelReplay", phase: "EVB-04" },
  { action: "CreateApiDestination", phase: "EVB-06" },
  { action: "CreateArchive", phase: "EVB-04" },
  { action: "CreateConnection", phase: "EVB-06" },
  { action: "CreateEndpoint", phase: "EVB-08" },
  { action: "CreateEventBus", phase: "EVB-01" },
  { action: "CreatePartnerEventSource", phase: "EVB-08" },
  { action: "DeactivateEventSource", phase: "EVB-08" },
  { action: "DeauthorizeConnection", phase: "EVB-06" },
  { action: "DeleteApiDestination", phase: "EVB-06" },
  { action: "DeleteArchive", phase: "EVB-04" },
  { action: "DeleteConnection", phase: "EVB-06" },
  { action: "DeleteEndpoint", phase: "EVB-08" },
  { action: "DeleteEventBus", phase: "EVB-01" },
  { action: "DeletePartnerEventSource", phase: "EVB-08" },
  { action: "DeleteRule", phase: "EVB-01" },
  { action: "DescribeApiDestination", phase: "EVB-06" },
  { action: "DescribeArchive", phase: "EVB-04" },
  { action: "DescribeConnection", phase: "EVB-06" },
  { action: "DescribeEndpoint", phase: "EVB-08" },
  { action: "DescribeEventBus", phase: "EVB-01" },
  { action: "DescribeEventSource", phase: "EVB-08" },
  { action: "DescribePartnerEventSource", phase: "EVB-08" },
  { action: "DescribeReplay", phase: "EVB-04" },
  { action: "DescribeRule", phase: "EVB-01" },
  { action: "DisableRule", phase: "EVB-01" },
  { action: "EnableRule", phase: "EVB-01" },
  { action: "ListApiDestinations", phase: "EVB-06" },
  { action: "ListArchives", phase: "EVB-04" },
  { action: "ListConnections", phase: "EVB-06" },
  { action: "ListEndpoints", phase: "EVB-08" },
  { action: "ListEventBuses", phase: "EVB-01" },
  { action: "ListEventSources", phase: "EVB-08" },
  { action: "ListPartnerEventSourceAccounts", phase: "EVB-08" },
  { action: "ListPartnerEventSources", phase: "EVB-08" },
  { action: "ListReplays", phase: "EVB-04" },
  { action: "ListRuleNamesByTarget", phase: "EVB-01" },
  { action: "ListRules", phase: "EVB-01" },
  { action: "ListTagsForResource", phase: "EVB-01" },
  { action: "ListTargetsByRule", phase: "EVB-01" },
  { action: "PutEvents", phase: "EVB-01" },
  { action: "PutPartnerEvents", phase: "EVB-08" },
  { action: "PutPermission", phase: "EVB-06" },
  { action: "PutRule", phase: "EVB-01" },
  { action: "PutTargets", phase: "EVB-01" },
  { action: "RemovePermission", phase: "EVB-06" },
  { action: "RemoveTargets", phase: "EVB-01" },
  { action: "StartReplay", phase: "EVB-04" },
  { action: "TagResource", phase: "EVB-01" },
  { action: "TestEventPattern", phase: "EVB-01" },
  { action: "UntagResource", phase: "EVB-01" },
  { action: "UpdateApiDestination", phase: "EVB-06" },
  { action: "UpdateArchive", phase: "EVB-04" },
  { action: "UpdateConnection", phase: "EVB-06" },
  { action: "UpdateEndpoint", phase: "EVB-08" },
  { action: "UpdateEventBus", phase: "EVB-08" },
] as const;
