export const CLOUDFORMATION_ACTION_INVENTORY_SOURCE = {
  sdkVersion: "3.1079.0",
  apiVersion: "2010-05-15",
  protocol: "AWS Query",
} as const;

export type CloudFormationActionClassification = "implemented" | "dependency" | "non-goal";

export interface CloudFormationActionInventoryEntry {
  action: string;
  classification: CloudFormationActionClassification;
}

export const CLOUDFORMATION_ACTION_INVENTORY = [
  { action: "ActivateOrganizationsAccess", classification: "non-goal" },
  { action: "ActivateType", classification: "non-goal" },
  { action: "BatchDescribeTypeConfigurations", classification: "non-goal" },
  { action: "CancelUpdateStack", classification: "implemented" },
  { action: "ContinueUpdateRollback", classification: "implemented" },
  { action: "CreateChangeSet", classification: "implemented" },
  { action: "CreateGeneratedTemplate", classification: "dependency" },
  { action: "CreateStack", classification: "implemented" },
  { action: "CreateStackInstances", classification: "non-goal" },
  { action: "CreateStackRefactor", classification: "dependency" },
  { action: "CreateStackSet", classification: "non-goal" },
  { action: "DeactivateOrganizationsAccess", classification: "non-goal" },
  { action: "DeactivateType", classification: "non-goal" },
  { action: "DeleteChangeSet", classification: "implemented" },
  { action: "DeleteGeneratedTemplate", classification: "dependency" },
  { action: "DeleteStack", classification: "implemented" },
  { action: "DeleteStackInstances", classification: "non-goal" },
  { action: "DeleteStackSet", classification: "non-goal" },
  { action: "DeregisterType", classification: "non-goal" },
  { action: "DescribeAccountLimits", classification: "dependency" },
  { action: "DescribeChangeSet", classification: "implemented" },
  { action: "DescribeChangeSetHooks", classification: "non-goal" },
  { action: "DescribeEvents", classification: "dependency" },
  { action: "DescribeGeneratedTemplate", classification: "dependency" },
  { action: "DescribeOrganizationsAccess", classification: "non-goal" },
  { action: "DescribePublisher", classification: "non-goal" },
  { action: "DescribeResourceScan", classification: "dependency" },
  { action: "DescribeStackDriftDetectionStatus", classification: "dependency" },
  { action: "DescribeStackEvents", classification: "implemented" },
  { action: "DescribeStackInstance", classification: "non-goal" },
  { action: "DescribeStackRefactor", classification: "dependency" },
  { action: "DescribeStackResource", classification: "implemented" },
  { action: "DescribeStackResourceDrifts", classification: "dependency" },
  { action: "DescribeStackResources", classification: "implemented" },
  { action: "DescribeStacks", classification: "implemented" },
  { action: "DescribeStackSet", classification: "non-goal" },
  { action: "DescribeStackSetOperation", classification: "non-goal" },
  { action: "DescribeType", classification: "non-goal" },
  { action: "DescribeTypeRegistration", classification: "non-goal" },
  { action: "DetectStackDrift", classification: "dependency" },
  { action: "DetectStackResourceDrift", classification: "dependency" },
  { action: "DetectStackSetDrift", classification: "non-goal" },
  { action: "EstimateTemplateCost", classification: "non-goal" },
  { action: "ExecuteChangeSet", classification: "implemented" },
  { action: "ExecuteStackRefactor", classification: "dependency" },
  { action: "GetGeneratedTemplate", classification: "dependency" },
  { action: "GetHookResult", classification: "non-goal" },
  { action: "GetStackPolicy", classification: "dependency" },
  { action: "GetTemplate", classification: "implemented" },
  { action: "GetTemplateSummary", classification: "implemented" },
  { action: "ImportStacksToStackSet", classification: "non-goal" },
  { action: "ListChangeSets", classification: "implemented" },
  { action: "ListExports", classification: "implemented" },
  { action: "ListGeneratedTemplates", classification: "dependency" },
  { action: "ListHookResults", classification: "non-goal" },
  { action: "ListImports", classification: "implemented" },
  { action: "ListResourceScanRelatedResources", classification: "dependency" },
  { action: "ListResourceScanResources", classification: "dependency" },
  { action: "ListResourceScans", classification: "dependency" },
  { action: "ListStackInstanceResourceDrifts", classification: "non-goal" },
  { action: "ListStackInstances", classification: "non-goal" },
  { action: "ListStackRefactorActions", classification: "dependency" },
  { action: "ListStackRefactors", classification: "dependency" },
  { action: "ListStackResources", classification: "implemented" },
  { action: "ListStacks", classification: "implemented" },
  { action: "ListStackSetAutoDeploymentTargets", classification: "non-goal" },
  { action: "ListStackSetOperationResults", classification: "non-goal" },
  { action: "ListStackSetOperations", classification: "non-goal" },
  { action: "ListStackSets", classification: "non-goal" },
  { action: "ListTypeRegistrations", classification: "non-goal" },
  { action: "ListTypes", classification: "non-goal" },
  { action: "ListTypeVersions", classification: "non-goal" },
  { action: "PublishType", classification: "non-goal" },
  { action: "RecordHandlerProgress", classification: "non-goal" },
  { action: "RegisterPublisher", classification: "non-goal" },
  { action: "RegisterType", classification: "non-goal" },
  { action: "RollbackStack", classification: "implemented" },
  { action: "SetStackPolicy", classification: "dependency" },
  { action: "SetTypeConfiguration", classification: "non-goal" },
  { action: "SetTypeDefaultVersion", classification: "non-goal" },
  { action: "SignalResource", classification: "dependency" },
  { action: "StartResourceScan", classification: "dependency" },
  { action: "StopStackSetOperation", classification: "non-goal" },
  { action: "TestType", classification: "non-goal" },
  { action: "UpdateGeneratedTemplate", classification: "dependency" },
  { action: "UpdateStack", classification: "implemented" },
  { action: "UpdateStackInstances", classification: "non-goal" },
  { action: "UpdateStackSet", classification: "non-goal" },
  { action: "UpdateTerminationProtection", classification: "implemented" },
  { action: "ValidateTemplate", classification: "implemented" },
] as const satisfies readonly CloudFormationActionInventoryEntry[];
