export const CLOUDFORMATION_RESOURCE_INVENTORY = [
  "AWS::ApiGateway::Account", "AWS::ApiGateway::ApiKey", "AWS::ApiGateway::Authorizer", "AWS::ApiGateway::BasePathMapping", "AWS::ApiGateway::BasePathMappingV2",
  "AWS::ApiGateway::ClientCertificate", "AWS::ApiGateway::Deployment", "AWS::ApiGateway::DocumentationPart", "AWS::ApiGateway::DocumentationVersion",
  "AWS::ApiGateway::DomainName", "AWS::ApiGateway::DomainNameAccessAssociation", "AWS::ApiGateway::DomainNameV2", "AWS::ApiGateway::GatewayResponse",
  "AWS::ApiGateway::Method", "AWS::ApiGateway::Model", "AWS::ApiGateway::RequestValidator", "AWS::ApiGateway::Resource", "AWS::ApiGateway::RestApi",
  "AWS::ApiGateway::Stage", "AWS::ApiGateway::UsagePlan", "AWS::ApiGateway::UsagePlanKey", "AWS::ApiGateway::VpcLink",
  "AWS::ApiGatewayV2::Api", "AWS::ApiGatewayV2::ApiMapping", "AWS::ApiGatewayV2::Authorizer", "AWS::ApiGatewayV2::Deployment", "AWS::ApiGatewayV2::DomainName",
  "AWS::ApiGatewayV2::Integration", "AWS::ApiGatewayV2::IntegrationResponse", "AWS::ApiGatewayV2::Model", "AWS::ApiGatewayV2::Route", "AWS::ApiGatewayV2::RouteResponse", "AWS::ApiGatewayV2::Stage",
  "AWS::AppSync::ApiKey", "AWS::AppSync::DataSource", "AWS::AppSync::FunctionConfiguration", "AWS::AppSync::GraphQLApi", "AWS::AppSync::GraphQLSchema", "AWS::AppSync::Resolver",
  "AWS::CDK::Metadata", "AWS::CloudFormation::CustomResource", "AWS::CloudFormation::Stack",
  "AWS::CloudFront::Distribution", "AWS::CloudFront::Function", "AWS::CloudFront::OriginAccessControl", "AWS::CloudFront::ResponseHeadersPolicy",
  "AWS::CloudWatch::Alarm", "AWS::CloudWatch::AnomalyDetector", "AWS::CloudWatch::CompositeAlarm", "AWS::CloudWatch::Dashboard", "AWS::CloudWatch::InsightRule", "AWS::CloudWatch::MetricStream",
  "AWS::Cognito::UserPool", "AWS::Cognito::UserPoolClient", "AWS::Cognito::UserPoolDomain", "AWS::Cognito::UserPoolGroup",
  "AWS::Cognito::UserPoolIdentityProvider", "AWS::Cognito::UserPoolResourceServer", "AWS::Cognito::UserPoolUser", "AWS::Cognito::UserPoolUserToGroupAttachment",
  "AWS::DynamoDB::GlobalTable", "AWS::DynamoDB::Table", "AWS::Events::EventBus", "AWS::Events::Rule", "AWS::IAM::ManagedPolicy", "AWS::IAM::Policy", "AWS::IAM::Role",
  "AWS::Lambda::Alias", "AWS::Lambda::CodeSigningConfig", "AWS::Lambda::EventInvokeConfig", "AWS::Lambda::EventSourceMapping", "AWS::Lambda::Function",
  "AWS::Lambda::LayerVersion", "AWS::Lambda::LayerVersionPermission", "AWS::Lambda::Permission", "AWS::Lambda::Url", "AWS::Lambda::Version",
  "AWS::Logs::Destination", "AWS::Logs::LogGroup", "AWS::Logs::LogStream", "AWS::Logs::MetricFilter", "AWS::Logs::QueryDefinition", "AWS::Logs::ResourcePolicy", "AWS::Logs::SubscriptionFilter",
  "AWS::RDS::DBInstance", "AWS::RDS::DBParameterGroup", "AWS::S3::Bucket", "AWS::S3::BucketPolicy",
  "AWS::SES::ConfigurationSet", "AWS::SES::ConfigurationSetEventDestination", "AWS::SES::ContactList",
  "AWS::SES::CustomVerificationEmailTemplate", "AWS::SES::EmailIdentity", "AWS::SES::Template",
  "AWS::SNS::Subscription", "AWS::SNS::Topic", "AWS::SNS::TopicInlinePolicy", "AWS::SNS::TopicPolicy",
  "AWS::SQS::Queue", "AWS::SQS::QueuePolicy", "AWS::SecretsManager::ResourcePolicy", "AWS::SecretsManager::RotationSchedule", "AWS::SecretsManager::Secret", "AWS::SecretsManager::SecretTargetAttachment", "AWS::SSM::Parameter", "AWS::StepFunctions::StateMachine",
  "Custom::AmplifyDynamoDBTable", "Custom::CDKBucketDeployment", "Custom::S3AutoDeleteObjects",
] as const;
