/** Current API Gateway v1 operation inventory, audited against the official API Operations index on 2026-07-16. */
export const API_GATEWAY_V1_ACTIONS = [
  "CreateApiKey", "CreateAuthorizer", "CreateBasePathMapping", "CreateDeployment", "CreateDocumentationPart", "CreateDocumentationVersion", "CreateDomainName", "CreateDomainNameAccessAssociation", "CreateModel", "CreateRequestValidator", "CreateResource", "CreateRestApi", "CreateStage", "CreateUsagePlan", "CreateUsagePlanKey", "CreateVpcLink",
  "DeleteApiKey", "DeleteAuthorizer", "DeleteBasePathMapping", "DeleteClientCertificate", "DeleteDeployment", "DeleteDocumentationPart", "DeleteDocumentationVersion", "DeleteDomainName", "DeleteDomainNameAccessAssociation", "DeleteGatewayResponse", "DeleteIntegration", "DeleteIntegrationResponse", "DeleteMethod", "DeleteMethodResponse", "DeleteModel", "DeleteRequestValidator", "DeleteResource", "DeleteRestApi", "DeleteStage", "DeleteUsagePlan", "DeleteUsagePlanKey", "DeleteVpcLink",
  "FlushStageAuthorizersCache", "FlushStageCache", "GenerateClientCertificate", "GetAccount", "GetApiKey", "GetApiKeys", "GetAuthorizer", "GetAuthorizers", "GetBasePathMapping", "GetBasePathMappings", "GetClientCertificate", "GetClientCertificates", "GetDeployment", "GetDeployments", "GetDocumentationPart", "GetDocumentationParts", "GetDocumentationVersion", "GetDocumentationVersions", "GetDomainName", "GetDomainNameAccessAssociations", "GetDomainNames", "GetExport", "GetGatewayResponse", "GetGatewayResponses", "GetIntegration", "GetIntegrationResponse", "GetMethod", "GetMethodResponse", "GetModel", "GetModels", "GetModelTemplate", "GetRequestValidator", "GetRequestValidators", "GetResource", "GetResources", "GetRestApi", "GetRestApis", "GetSdk", "GetSdkType", "GetSdkTypes", "GetStage", "GetStages", "GetTags", "GetUsage", "GetUsagePlan", "GetUsagePlanKey", "GetUsagePlanKeys", "GetUsagePlans", "GetVpcLink", "GetVpcLinks",
  "ImportApiKeys", "ImportDocumentationParts", "ImportRestApi", "PutGatewayResponse", "PutIntegration", "PutIntegrationResponse", "PutMethod", "PutMethodResponse", "PutRestApi", "RejectDomainNameAccessAssociation", "TagResource", "TestInvokeAuthorizer", "TestInvokeMethod", "UntagResource", "UpdateAccount", "UpdateApiKey", "UpdateAuthorizer", "UpdateBasePathMapping", "UpdateClientCertificate", "UpdateDeployment", "UpdateDocumentationPart", "UpdateDocumentationVersion", "UpdateDomainName", "UpdateGatewayResponse", "UpdateIntegration", "UpdateIntegrationResponse", "UpdateMethod", "UpdateMethodResponse", "UpdateModel", "UpdateRequestValidator", "UpdateResource", "UpdateRestApi", "UpdateStage", "UpdateUsage", "UpdateUsagePlan", "UpdateVpcLink",
] as const;

export type ApiGatewayV1Action = typeof API_GATEWAY_V1_ACTIONS[number];

export const APIGATEWAY_V1_EXTERNAL_BOUNDARIES: Partial<Record<ApiGatewayV1Action, string>> = {
  CreateVpcLink: "Control state is local; runtime traffic requires an explicit load-balancer ARN to local HTTP-origin mapping.",
  GenerateClientCertificate: "Self-signed local generation requires explicit opt-in; the private key is not exposed or used to fabricate upstream mTLS.",
  GetSdk: "The original minimal JavaScript ZIP is generated locally; Java, Android, Objective-C, Swift, and Ruby generators are dependency-blocked.",
};
