import { mkdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { chromium } from "playwright";
import { CloudWatchClient, PutDashboardCommand, PutMetricAlarmCommand, PutMetricDataCommand, SetAlarmStateCommand } from "@aws-sdk/client-cloudwatch";
import { CloudWatchLogsClient, CreateLogGroupCommand, CreateLogStreamCommand, PutLogEventsCommand } from "@aws-sdk/client-cloudwatch-logs";
import { StackSim } from "../dist/src/server.js";

const root = await mkdtemp(join(tmpdir(), "stacksim-cw06-capture-")); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1" }); const viewports = [["desktop-1440x900.jpg", 1440, 900], ["desktop-1280x800.jpg", 1280, 800], ["mobile-390x844.jpg", 390, 844]]; let browser; let cloudwatch; let logs;
try {
  await simulator.start(); const options = { endpoint: `http://127.0.0.1:${simulator.port}`, region: "eu-west-1", credentials: { accessKeyId: "admin", secretAccessKey: "password" } }; cloudwatch = new CloudWatchClient(options); logs = new CloudWatchLogsClient(options); const now = Date.now();
  await cloudwatch.send(new PutMetricDataCommand({ Namespace: "Learning/Checkout", MetricData: Array.from({ length: 10 }, (_, index) => ({ MetricName: "Latency", Dimensions: [{ Name: "Route", Value: "/checkout" }], Unit: "Milliseconds", Timestamp: new Date(now - (9 - index) * 60_000), Value: 126 + index * 13 + (index % 3) * 18 })).concat(Array.from({ length: 10 }, (_, index) => ({ MetricName: "Requests", Dimensions: [{ Name: "Route", Value: "/checkout" }], Unit: "Count", Timestamp: new Date(now - (9 - index) * 60_000), Value: 82 + index * 4 })), [
    { MetricName: "Errors", Dimensions: [{ Name: "Service", Value: "checkout" }], Unit: "Count", Timestamp: new Date(now), Value: 8 },
    { MetricName: "Errors", Dimensions: [{ Name: "Service", Value: "billing" }], Unit: "Count", Timestamp: new Date(now), Value: 3 },
    { MetricName: "Errors", Dimensions: [{ Name: "Service", Value: "inventory" }], Unit: "Count", Timestamp: new Date(now), Value: 5 },
  ]) }));
  for (let index = 0; index < 8; index++) await simulator.metrics.publish({ namespace: "AWS/Lambda", metricName: "Invocations", dimensions: { FunctionName: index % 2 ? "checkout-worker" : "billing-worker" }, unit: "Count", timestamp: now - (7 - index) * 60_000, value: 18 + index * 2 });
  await cloudwatch.send(new PutMetricAlarmCommand({ AlarmName: "checkout-high-latency", AlarmDescription: "Checkout latency is above the local learning threshold.", Namespace: "Learning/Checkout", MetricName: "Latency", Dimensions: [{ Name: "Route", Value: "/checkout" }], Period: 60, Statistic: "Average", EvaluationPeriods: 3, DatapointsToAlarm: 2, Threshold: 200, ComparisonOperator: "GreaterThanThreshold" })); await cloudwatch.send(new SetAlarmStateCommand({ AlarmName: "checkout-high-latency", StateValue: "ALARM", StateReason: "2 of 3 recent datapoints exceeded 200 ms" }));
  await cloudwatch.send(new PutMetricAlarmCommand({ AlarmName: "checkout-request-volume", Namespace: "Learning/Checkout", MetricName: "Requests", Dimensions: [{ Name: "Route", Value: "/checkout" }], Period: 60, Statistic: "Sum", EvaluationPeriods: 1, Threshold: 50, ComparisonOperator: "LessThanThreshold" })); await cloudwatch.send(new SetAlarmStateCommand({ AlarmName: "checkout-request-volume", StateValue: "OK", StateReason: "Traffic is within the expected range" }));
  const group = "/learning/checkout"; await logs.send(new CreateLogGroupCommand({ logGroupName: group })); await logs.send(new CreateLogStreamCommand({ logGroupName: group, logStreamName: "application" })); await logs.send(new PutLogEventsCommand({ logGroupName: group, logStreamName: "application", logEvents: [
    { timestamp: now - 4000, message: "status=ok duration=142 service=checkout route=/checkout" }, { timestamp: now - 3000, message: "status=error duration=248 service=checkout route=/checkout" }, { timestamp: now - 2000, message: "status=ok duration=168 service=checkout route=/checkout" }, { timestamp: now - 1000, message: "status=error duration=231 service=checkout route=/checkout" },
  ] }));
  const operationsBody = { start: "-PT3H", periodOverride: "inherit", variables: [{ type: "property", property: "Route", inputType: "select", id: "route", label: "Checkout route", defaultValue: "/checkout", values: [{ label: "Checkout", value: "/checkout" }, { label: "Health", value: "/health" }] }], widgets: [
    { type: "text", x: 0, y: 0, width: 24, height: 2, properties: { markdown: "# Checkout operations\nLive local telemetry for the payments learning environment." } },
    { type: "metric", x: 0, y: 2, width: 12, height: 6, properties: { title: "Checkout latency", region: "eu-west-1", view: "timeSeries", stat: "Average", period: 60, metrics: [["Learning/Checkout", "Latency", "Route", "/checkout", { id: "latency", label: "pacing · /checkout" }]], annotations: { horizontal: [{ label: "Alarm threshold", value: 200, color: "#d13212" }] } } },
    { type: "metric", x: 12, y: 2, width: 6, height: 6, properties: { title: "Latest latency", region: "eu-west-1", view: "singleValue", period: 60, metrics: [["Learning/Checkout", "Latency", "Route", "/checkout", { label: "Milliseconds" }]] } },
    { type: "metric", x: 18, y: 2, width: 6, height: 6, properties: { title: "Latency gauge", region: "eu-west-1", view: "gauge", period: 60, yAxis: { left: { min: 0, max: 300 } }, metrics: [["Learning/Checkout", "Latency", "Route", "/checkout", { label: "Checkout" }]] } },
    { type: "log", x: 0, y: 8, width: 14, height: 6, properties: { title: "Recent application events", region: "eu-west-1", query: `SOURCE '${group}' | fields @timestamp, @message | sort @timestamp desc | limit 20` } },
    { type: "alarm", x: 14, y: 8, width: 10, height: 6, properties: { title: "Checkout alarms", alarms: ["arn:aws:cloudwatch:eu-west-1:000000000000:alarm:checkout-high-latency", "arn:aws:cloudwatch:eu-west-1:000000000000:alarm:checkout-request-volume"] } },
    { type: "metric", x: 0, y: 14, width: 12, height: 6, properties: { title: "Errors by service", region: "eu-west-1", view: "bar", metrics: [["Learning/Checkout", "Errors", "Service", "checkout", { label: "Checkout" }], ["...", "billing", { label: "Billing" }], ["...", "inventory", { label: "Inventory" }]] } },
    { type: "metric", x: 12, y: 14, width: 12, height: 6, properties: { title: "Error share", region: "eu-west-1", view: "pie", metrics: [["Learning/Checkout", "Errors", "Service", "checkout", { label: "Checkout" }], ["...", "billing", { label: "Billing" }], ["...", "inventory", { label: "Inventory" }]] } },
    { type: "explorer", x: 0, y: 20, width: 24, height: 6, properties: { title: "Lambda invocation explorer", period: 60, metrics: [{ metricName: "Invocations", resourceType: "AWS::Lambda::Function", stat: "Sum" }], labels: ["FunctionName"], widgetOptions: { view: "timeSeries" } } },
  ] };
  await cloudwatch.send(new PutDashboardCommand({ DashboardName: "checkout_operations", DashboardBody: JSON.stringify(operationsBody) })); await cloudwatch.send(new PutDashboardCommand({ DashboardName: "service_health", DashboardBody: JSON.stringify({ start: "-PT1H", widgets: [{ type: "text", x: 0, y: 0, width: 24, height: 3, properties: { markdown: "# Service health\nA compact landing page for local services." } }] }) }));
  const pages = [
    { route: "/cloudwatch/dashboards", output: "catalog", wait: page => page.getByRole("link", { name: "checkout_operations" }).waitFor() },
    { route: "/cloudwatch/dashboards/checkout_operations", output: "cross-source-view", wait: async page => { await page.getByText("pacing · /checkout", { exact: true }).waitFor(); await page.getByText("checkout-high-latency", { exact: true }).waitFor(); await page.getByText(/status=error duration=248/).waitFor(); } },
    { route: "/cloudwatch/dashboards/checkout_operations", output: "editable-grid", wait: async page => { await page.getByText("pacing · /checkout", { exact: true }).waitFor(); await page.getByRole("button", { name: "Edit", exact: true }).click(); await page.getByRole("button", { name: "Add widget" }).waitFor(); } },
  ];
  browser = await chromium.launch({ channel: "chrome", headless: true, args: ["--disable-gpu"] });
  for (const pageSpec of pages) { const output = resolve("docs/ui-reference/2026-07-16/cloudwatch/cw06", pageSpec.output, "final"); await mkdir(output, { recursive: true }); for (const [name, width, height] of viewports) { const page = await browser.newPage({ viewport: { width, height } }); await page.goto(`http://127.0.0.1:${simulator.port}/_stacksim/console#${pageSpec.route}`); await pageSpec.wait(page); await page.evaluate(() => new Promise(resolvePaint => requestAnimationFrame(() => requestAnimationFrame(resolvePaint)))); await page.screenshot({ path: join(output, name), type: "jpeg", quality: 88, fullPage: true }); await page.close(); } }
} finally { cloudwatch?.destroy(); logs?.destroy(); await browser?.close(); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 20 }); }
