import { mkdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { chromium } from "playwright";
import { CloudWatchClient, PutMetricAlarmCommand, PutMetricDataCommand, SetAlarmStateCommand } from "@aws-sdk/client-cloudwatch";
import { StackSim } from "../dist/src/server.js";

const root = await mkdtemp(join(tmpdir(), "stacksim-cw05-capture-")); const simulator = new StackSim({ port: 0, invokePort: 0, dataDir: root, region: "eu-west-1" }); const viewports = [["desktop-1440x900.jpg", 1440, 900], ["desktop-1280x800.jpg", 1280, 800], ["mobile-390x844.jpg", 390, 844]]; let browser; let cloudwatch;
try {
  await simulator.start(); cloudwatch = new CloudWatchClient({ endpoint: `http://127.0.0.1:${simulator.port}`, region: "eu-west-1", credentials: { accessKeyId: "admin", secretAccessKey: "password" } }); const now = Date.now();
  await cloudwatch.send(new PutMetricDataCommand({ Namespace: "Learning/Checkout", MetricData: Array.from({ length: 8 }, (_, index) => ({ MetricName: "Latency", Dimensions: [{ Name: "Route", Value: "/checkout" }], Unit: "Milliseconds", Timestamp: new Date(now - (7 - index) * 60_000), Value: 140 + index * 18 })).concat(Array.from({ length: 8 }, (_, index) => ({ MetricName: "Requests", Dimensions: [{ Name: "Route", Value: "/checkout" }], Unit: "Count", Timestamp: new Date(now - (7 - index) * 60_000), Value: 30 + index * 3 }))) }));
  await cloudwatch.send(new PutMetricAlarmCommand({ AlarmName: "checkout-high-latency", AlarmDescription: "Checkout latency breached the learning environment threshold.", Namespace: "Learning/Checkout", MetricName: "Latency", Dimensions: [{ Name: "Route", Value: "/checkout" }], Unit: "Milliseconds", Period: 60, Statistic: "Average", EvaluationPeriods: 3, DatapointsToAlarm: 2, Threshold: 200, ComparisonOperator: "GreaterThanThreshold", TreatMissingData: "missing", AlarmActions: ["arn:aws:sns:eu-west-1:000000000000:checkout-alerts"], Tags: [{ Key: "team", Value: "payments" }, { Key: "environment", Value: "learning" }] }));
  await cloudwatch.send(new SetAlarmStateCommand({ AlarmName: "checkout-high-latency", StateValue: "ALARM", StateReason: "2 of the last 3 datapoints were above 200 ms" })); await cloudwatch.send(new SetAlarmStateCommand({ AlarmName: "checkout-high-latency", StateValue: "OK", StateReason: "Latency briefly recovered" })); await cloudwatch.send(new SetAlarmStateCommand({ AlarmName: "checkout-high-latency", StateValue: "ALARM", StateReason: "Latency returned above the threshold" }));
  await cloudwatch.send(new PutMetricAlarmCommand({ AlarmName: "checkout-request-volume", AlarmDescription: "Request traffic remains above the minimum expected volume.", Namespace: "Learning/Checkout", MetricName: "Requests", Dimensions: [{ Name: "Route", Value: "/checkout" }], Unit: "Count", Period: 60, Statistic: "Sum", EvaluationPeriods: 1, Threshold: 20, ComparisonOperator: "LessThanThreshold", TreatMissingData: "breaching" })); await cloudwatch.send(new SetAlarmStateCommand({ AlarmName: "checkout-request-volume", StateValue: "OK", StateReason: "Request volume is within the expected range" }));
  await cloudwatch.send(new PutMetricAlarmCommand({ AlarmName: "checkout-worker-heartbeat", AlarmDescription: "No heartbeat samples have arrived yet.", Namespace: "Learning/Checkout", MetricName: "WorkerHeartbeat", Unit: "Count", Period: 60, Statistic: "Sum", EvaluationPeriods: 2, DatapointsToAlarm: 2, Threshold: 1, ComparisonOperator: "LessThanThreshold", TreatMissingData: "missing" }));
  const pages = [
    { route: "/cloudwatch/alarms", output: "all" },
    { route: "/cloudwatch/alarms", output: "create", prepare: async page => { await page.getByRole("button", { name: "Create alarm" }).click(); const dialog = page.getByRole("dialog"); await dialog.getByLabel(/Latency.*Learning\/Checkout/).check(); await dialog.getByRole("button", { name: "Next" }).click(); await dialog.getByRole("button", { name: "Next" }).click(); await dialog.getByLabel("Action ARN (optional)").fill("arn:aws:sns:eu-west-1:000000000000:checkout-alerts"); await dialog.getByLabel("Alarm name").fill("checkout-latency-warning"); await dialog.getByRole("img", { name: "Alarm metric preview" }).waitFor(); } },
    { route: "/cloudwatch/alarms/checkout-high-latency", output: "detail" },
  ];
  browser = await chromium.launch({ channel: "chrome", headless: true });
  for (const pageSpec of pages) { const output = resolve("docs/ui-reference/2026-07-15/cloudwatch/alarms", pageSpec.output, "final"); await mkdir(output, { recursive: true }); for (const [name, width, height] of viewports) { const page = await browser.newPage({ viewport: { width, height } }); await page.goto(`http://127.0.0.1:${simulator.port}/_stacksim/console#${pageSpec.route}`); await page.locator("main").waitFor(); await pageSpec.prepare?.(page); await page.screenshot({ path: join(output, name), type: "jpeg", quality: 88, fullPage: true }); await page.close(); } }
} finally { cloudwatch?.destroy(); await browser?.close(); await simulator.stop().catch(() => undefined); await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 20 }); }
